# MySQL creation script for INDUCKS data model, generated by DIZNI version 2008-1210a
# DO NOT EDIT THIS FILE

# create database if not exists coa;
use gcd_dev;

# SQL for re-creating and filling table inducks_storyversion
DROP TABLE IF EXISTS inducks_storyversion_temp;
CREATE TABLE inducks_storyversion_temp (
    storyversioncode varchar(20),
    storycode varchar(20),
    entirepages int(7),
    brokenpagenumerator int(7),
    brokenpagedenominator int(7),
    brokenpageunspecified char(1),
    kind varchar(100),
    rowsperpage int(7),
    columnsperpage int(7),
    appisxapp char(1),
    what varchar(100),
    appsummary text,
    plotsummary text,
    writsummary text,
    artsummary text,
    inksummary text,
    keywordsummary text,
    FULLTEXT(appsummary,plotsummary,writsummary,artsummary,inksummary,keywordsummary),
    KEY pk0 (storyversioncode),
    KEY fk1 (storycode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_storyversion.isv" INTO TABLE inducks_storyversion_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_storyversion;
RENAME TABLE inducks_storyversion_temp TO inducks_storyversion;

# SQL for re-creating and filling table inducks_herocharacter
DROP TABLE IF EXISTS inducks_herocharacter_temp;
CREATE TABLE inducks_herocharacter_temp (
    storycode varchar(20),
    charactercode varchar(100),
    number int(7),
    KEY pk0 (storycode, charactercode),
    KEY fk0 (charactercode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_herocharacter.isv" INTO TABLE inducks_herocharacter_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_herocharacter;
RENAME TABLE inducks_herocharacter_temp TO inducks_herocharacter;

# SQL for re-creating and filling table inducks_appearance
DROP TABLE IF EXISTS inducks_appearance_temp;
CREATE TABLE inducks_appearance_temp (
    storyversioncode varchar(20),
    charactercode varchar(100),
    number int(7),
    appearancecomment text,
    FULLTEXT(appearancecomment),
    KEY pk0 (storyversioncode, charactercode),
    KEY fk0 (charactercode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_appearance.isv" INTO TABLE inducks_appearance_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_appearance;
RENAME TABLE inducks_appearance_temp TO inducks_appearance;

# SQL for re-creating and filling table inducks_storyjob
DROP TABLE IF EXISTS inducks_storyjob_temp;
CREATE TABLE inducks_storyjob_temp (
    storyversioncode varchar(20),
    personcode varchar(100),
    plotwritartink varchar(100),
    storyjobcomment text,
    indirect char(1),
    FULLTEXT(storyjobcomment),
    KEY pk0 (storyversioncode, personcode, plotwritartink),
    KEY fk0 (personcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_storyjob.isv" INTO TABLE inducks_storyjob_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_storyjob;
RENAME TABLE inducks_storyjob_temp TO inducks_storyjob;

# SQL for re-creating and filling table inducks_story
DROP TABLE IF EXISTS inducks_story_temp;
CREATE TABLE inducks_story_temp (
    storycode varchar(20),
    originalstoryversioncode varchar(20),
    superstorycode varchar(20),
    part varchar(100),
    creationdate varchar(100),
    firstpublicationdate varchar(10),
    endpublicationdate varchar(10),
    title text,
    usedifferentcode varchar(100),
    storycomment text,
    errormessage text,
    repcountrysummary text,
    FULLTEXT(title,storycomment,errormessage,repcountrysummary),
    KEY pk0 (storycode),
    KEY fk0 (originalstoryversioncode),
    KEY fk1 (superstorycode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_story.isv" INTO TABLE inducks_story_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_story;
RENAME TABLE inducks_story_temp TO inducks_story;

# SQL for re-creating and filling table inducks_storysubseries
DROP TABLE IF EXISTS inducks_storysubseries_temp;
CREATE TABLE inducks_storysubseries_temp (
    storycode varchar(20),
    subseriescode varchar(100),
    storysubseriescomment text,
    FULLTEXT(storysubseriescomment),
    KEY pk0 (storycode, subseriescode),
    KEY fk0 (subseriescode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_storysubseries.isv" INTO TABLE inducks_storysubseries_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_storysubseries;
RENAME TABLE inducks_storysubseries_temp TO inducks_storysubseries;

# SQL for re-creating and filling table inducks_storycodes
DROP TABLE IF EXISTS inducks_storycodes_temp;
CREATE TABLE inducks_storycodes_temp (
    storycode varchar(20),
    alternativecode varchar(100),
    unpackedcode varchar(100),
    codecomment text,
    FULLTEXT(codecomment),
    KEY pk0 (storycode, alternativecode),
    KEY fk0 (alternativecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_storycodes.isv" INTO TABLE inducks_storycodes_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_storycodes;
RENAME TABLE inducks_storycodes_temp TO inducks_storycodes;

# SQL for re-creating and filling table inducks_storydescription
DROP TABLE IF EXISTS inducks_storydescription_temp;
CREATE TABLE inducks_storydescription_temp (
    storyversioncode varchar(20),
    languagecode varchar(100),
    desctext text,
    FULLTEXT(desctext),
    KEY pk0 (storyversioncode, languagecode),
    KEY fk0 (languagecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_storydescription.isv" INTO TABLE inducks_storydescription_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_storydescription;
RENAME TABLE inducks_storydescription_temp TO inducks_storydescription;

# SQL for re-creating and filling table inducks_storyreference
DROP TABLE IF EXISTS inducks_storyreference_temp;
CREATE TABLE inducks_storyreference_temp (
    fromstorycode varchar(20),
    tostorycode varchar(20),
    referencereasonid int(7),
    KEY pk0 (fromstorycode, tostorycode),
    KEY fk0 (tostorycode),
    KEY fk1 (referencereasonid)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_storyreference.isv" INTO TABLE inducks_storyreference_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_storyreference;
RENAME TABLE inducks_storyreference_temp TO inducks_storyreference;

# SQL for re-creating and filling table inducks_referencereason
DROP TABLE IF EXISTS inducks_referencereason_temp;
CREATE TABLE inducks_referencereason_temp (
    referencereasonid int(7),
    reasontext varchar(100),
    KEY pk0 (referencereasonid)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_referencereason.isv" INTO TABLE inducks_referencereason_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_referencereason;
RENAME TABLE inducks_referencereason_temp TO inducks_referencereason;

# SQL for re-creating and filling table inducks_movie
DROP TABLE IF EXISTS inducks_movie_temp;
CREATE TABLE inducks_movie_temp (
    moviecode varchar(20),
    creationdate varchar(10),
    publicationdate varchar(10),
    title text,
    genre varchar(100),
    tim varchar(100),
    orderer varchar(100),
    distributor varchar(100),
    aka varchar(100),
    source varchar(100),
    moviedescription text,
    moviecomment text,
    appsummary text,
    moviejobsummary text,
    FULLTEXT(title,moviedescription,moviecomment,appsummary,moviejobsummary),
    KEY pk0 (moviecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_movie.isv" INTO TABLE inducks_movie_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_movie;
RENAME TABLE inducks_movie_temp TO inducks_movie;

# SQL for re-creating and filling table inducks_moviejob
DROP TABLE IF EXISTS inducks_moviejob_temp;
CREATE TABLE inducks_moviejob_temp (
    moviecode varchar(20),
    personcode varchar(100),
    role varchar(100),
    moviejobcomment text,
    FULLTEXT(moviejobcomment),
    KEY pk0 (moviecode, personcode, role),
    KEY fk0 (personcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_moviejob.isv" INTO TABLE inducks_moviejob_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_moviejob;
RENAME TABLE inducks_moviejob_temp TO inducks_moviejob;

# SQL for re-creating and filling table inducks_moviereference
DROP TABLE IF EXISTS inducks_moviereference_temp;
CREATE TABLE inducks_moviereference_temp (
    storycode varchar(20),
    moviecode varchar(20),
    referencereasonid int(7),
    frommovietostory char(1),
    KEY pk0 (storycode, moviecode),
    KEY fk0 (moviecode),
    KEY fk1 (referencereasonid)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_moviereference.isv" INTO TABLE inducks_moviereference_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_moviereference;
RENAME TABLE inducks_moviereference_temp TO inducks_moviereference;

# SQL for re-creating and filling table inducks_moviecharacter
DROP TABLE IF EXISTS inducks_moviecharacter_temp;
CREATE TABLE inducks_moviecharacter_temp (
    moviecode varchar(20),
    charactercode varchar(100),
    istitlecharacter char(1),
    KEY pk0 (moviecode, charactercode),
    KEY fk0 (charactercode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_moviecharacter.isv" INTO TABLE inducks_moviecharacter_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_moviecharacter;
RENAME TABLE inducks_moviecharacter_temp TO inducks_moviecharacter;

# SQL for re-creating and filling table inducks_entry
DROP TABLE IF EXISTS inducks_entry_temp;
CREATE TABLE inducks_entry_temp (
    entrycode varchar(20),
    issuecode varchar(20),
    storyversioncode varchar(20),
    languagecode varchar(100),
    includedinentrycode varchar(20),
    position varchar(100),
    printedcode varchar(100),
    guessedcode varchar(100),
    title text,
    reallytitle char(1),
    changes text,
    minorchanges text,
    missingpanels varchar(100),
    mirrored char(1),
    sideways char(1),
    startdate varchar(10),
    enddate varchar(10),
    identificationuncertain char(1),
    alsoreprint varchar(100),
    part varchar(100),
    entrycomment text,
    errormessage text,
    FULLTEXT(title,changes,minorchanges,entrycomment,errormessage),
    KEY pk0 (entrycode),
    KEY fk0 (issuecode),
    KEY fk1 (storyversioncode),
    KEY fk2 (languagecode),
    KEY fk3 (includedinentrycode),
    KEY fk4 (position)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_entry.isv" INTO TABLE inducks_entry_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_entry;
RENAME TABLE inducks_entry_temp TO inducks_entry;

# SQL for re-creating and filling table inducks_logocharacter
DROP TABLE IF EXISTS inducks_logocharacter_temp;
CREATE TABLE inducks_logocharacter_temp (
    entrycode varchar(20),
    charactercode varchar(100),
    reallyintitle char(1),
    number int(7),
    logocharactercomment text,
    FULLTEXT(logocharactercomment),
    KEY pk0 (entrycode, charactercode),
    KEY fk0 (charactercode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_logocharacter.isv" INTO TABLE inducks_logocharacter_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_logocharacter;
RENAME TABLE inducks_logocharacter_temp TO inducks_logocharacter;

# SQL for re-creating and filling table inducks_entrycharactername
DROP TABLE IF EXISTS inducks_entrycharactername_temp;
CREATE TABLE inducks_entrycharactername_temp (
    entrycode varchar(20),
    charactercode varchar(100),
    charactername varchar(100),
    KEY pk0 (entrycode, charactercode),
    KEY fk0 (charactercode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_entrycharactername.isv" INTO TABLE inducks_entrycharactername_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_entrycharactername;
RENAME TABLE inducks_entrycharactername_temp TO inducks_entrycharactername;

# SQL for re-creating and filling table inducks_entryjob
DROP TABLE IF EXISTS inducks_entryjob_temp;
CREATE TABLE inducks_entryjob_temp (
    entrycode varchar(20),
    personcode varchar(100),
    transletcol varchar(100),
    entryjobcomment text,
    FULLTEXT(entryjobcomment),
    KEY pk0 (entrycode, personcode, transletcol),
    KEY fk0 (personcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_entryjob.isv" INTO TABLE inducks_entryjob_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_entryjob;
RENAME TABLE inducks_entryjob_temp TO inducks_entryjob;

# SQL for re-creating and filling table inducks_language
DROP TABLE IF EXISTS inducks_language_temp;
CREATE TABLE inducks_language_temp (
    languagecode varchar(100),
    defaultlanguagecode varchar(100),
    languagename varchar(100),
    KEY pk0 (languagecode),
    KEY fk0 (defaultlanguagecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_language.isv" INTO TABLE inducks_language_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_language;
RENAME TABLE inducks_language_temp TO inducks_language;

# SQL for re-creating and filling table inducks_languagename
DROP TABLE IF EXISTS inducks_languagename_temp;
CREATE TABLE inducks_languagename_temp (
    desclanguagecode varchar(100),
    languagecode varchar(100),
    languagename varchar(100),
    KEY pk0 (desclanguagecode, languagecode),
    KEY fk0 (languagecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_languagename.isv" INTO TABLE inducks_languagename_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_languagename;
RENAME TABLE inducks_languagename_temp TO inducks_languagename;

# SQL for re-creating and filling table inducks_countryname
DROP TABLE IF EXISTS inducks_countryname_temp;
CREATE TABLE inducks_countryname_temp (
    countrycode varchar(100),
    languagecode varchar(100),
    countryname varchar(100),
    KEY pk0 (countrycode, languagecode),
    KEY fk0 (languagecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_countryname.isv" INTO TABLE inducks_countryname_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_countryname;
RENAME TABLE inducks_countryname_temp TO inducks_countryname;

# SQL for re-creating and filling table inducks_country
DROP TABLE IF EXISTS inducks_country_temp;
CREATE TABLE inducks_country_temp (
    countrycode varchar(100),
    countryname varchar(100),
    defaultlanguage varchar(100),
    KEY pk0 (countrycode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_country.isv" INTO TABLE inducks_country_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_country;
RENAME TABLE inducks_country_temp TO inducks_country;

# SQL for re-creating and filling table inducks_issue
DROP TABLE IF EXISTS inducks_issue_temp;
CREATE TABLE inducks_issue_temp (
    issuecode varchar(20),
    issuerangecode varchar(20),
    publicationcode varchar(20),
    issuenumber varchar(100),
    title text,
    size varchar(100),
    pages varchar(100),
    price varchar(100),
    attached text,
    oldestdate varchar(10),
    fullyindexed char(1),
    issuecomment text,
    errormessage text,
    owner varchar(100),
    FULLTEXT(title,attached,issuecomment,errormessage),
    KEY pk0 (issuecode),
    KEY fk0 (issuerangecode),
    KEY fk1 (publicationcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_issue.isv" INTO TABLE inducks_issue_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_issue;
RENAME TABLE inducks_issue_temp TO inducks_issue;

# SQL for re-creating and filling table inducks_issuejob
DROP TABLE IF EXISTS inducks_issuejob_temp;
CREATE TABLE inducks_issuejob_temp (
    issuecode varchar(20),
    personcode varchar(100),
    inxtransletcol varchar(100),
    issuejobcomment text,
    FULLTEXT(issuejobcomment),
    KEY pk0 (issuecode, personcode, inxtransletcol),
    KEY fk0 (personcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_issuejob.isv" INTO TABLE inducks_issuejob_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_issuejob;
RENAME TABLE inducks_issuejob_temp TO inducks_issuejob;

# SQL for re-creating and filling table inducks_issuedate
DROP TABLE IF EXISTS inducks_issuedate_temp;
CREATE TABLE inducks_issuedate_temp (
    issuecode varchar(20),
    date varchar(10),
    kindofdate varchar(100),
    KEY pk0 (issuecode, date)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_issuedate.isv" INTO TABLE inducks_issuedate_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_issuedate;
RENAME TABLE inducks_issuedate_temp TO inducks_issuedate;

# SQL for re-creating and filling table inducks_issuecollecting
DROP TABLE IF EXISTS inducks_issuecollecting_temp;
CREATE TABLE inducks_issuecollecting_temp (
    collectingissuecode varchar(20),
    collectedissuecode varchar(20),
    KEY pk0 (collectingissuecode, collectedissuecode),
    KEY fk0 (collectedissuecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_issuecollecting.isv" INTO TABLE inducks_issuecollecting_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_issuecollecting;
RENAME TABLE inducks_issuecollecting_temp TO inducks_issuecollecting;

# SQL for re-creating and filling table inducks_equiv
DROP TABLE IF EXISTS inducks_equiv_temp;
CREATE TABLE inducks_equiv_temp (
    issuecode varchar(20),
    equivid int(7),
    KEY pk0 (issuecode, equivid),
    KEY fk0 (equivid)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_equiv.isv" INTO TABLE inducks_equiv_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_equiv;
RENAME TABLE inducks_equiv_temp TO inducks_equiv;

# SQL for re-creating and filling table inducks_issuerange
DROP TABLE IF EXISTS inducks_issuerange_temp;
CREATE TABLE inducks_issuerange_temp (
    issuerangecode varchar(20),
    publicationcode varchar(20),
    title text,
    issuerangecomment text,
    errormessage text,
    FULLTEXT(title,issuerangecomment,errormessage),
    KEY pk0 (issuerangecode),
    KEY fk0 (publicationcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_issuerange.isv" INTO TABLE inducks_issuerange_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_issuerange;
RENAME TABLE inducks_issuerange_temp TO inducks_issuerange;

# SQL for re-creating and filling table inducks_publication
DROP TABLE IF EXISTS inducks_publication_temp;
CREATE TABLE inducks_publication_temp (
    publicationcode varchar(20),
    countrycode varchar(100),
    languagecode varchar(100),
    title text,
    size varchar(100),
    publicationcomment text,
    errormessage text,
    FULLTEXT(title,publicationcomment,errormessage),
    KEY pk0 (publicationcode),
    KEY fk0 (countrycode),
    KEY fk1 (languagecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_publication.isv" INTO TABLE inducks_publication_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_publication;
RENAME TABLE inducks_publication_temp TO inducks_publication;

# SQL for re-creating and filling table inducks_publicationcategory
DROP TABLE IF EXISTS inducks_publicationcategory_temp;
CREATE TABLE inducks_publicationcategory_temp (
    publicationcode varchar(20),
    category varchar(100),
    KEY pk0 (publicationcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_publicationcategory.isv" INTO TABLE inducks_publicationcategory_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_publicationcategory;
RENAME TABLE inducks_publicationcategory_temp TO inducks_publicationcategory;

# SQL for re-creating and filling table inducks_publicationname
DROP TABLE IF EXISTS inducks_publicationname_temp;
CREATE TABLE inducks_publicationname_temp (
    publicationcode varchar(20),
    publicationname text,
    FULLTEXT(publicationname),
    KEY pk0 (publicationcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_publicationname.isv" INTO TABLE inducks_publicationname_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_publicationname;
RENAME TABLE inducks_publicationname_temp TO inducks_publicationname;

# SQL for re-creating and filling table inducks_publisher
DROP TABLE IF EXISTS inducks_publisher_temp;
CREATE TABLE inducks_publisher_temp (
    publisherid varchar(100),
    publishername text,
    FULLTEXT(publishername),
    KEY pk0 (publisherid)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_publisher.isv" INTO TABLE inducks_publisher_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_publisher;
RENAME TABLE inducks_publisher_temp TO inducks_publisher;

# SQL for re-creating and filling table inducks_publishingjob
DROP TABLE IF EXISTS inducks_publishingjob_temp;
CREATE TABLE inducks_publishingjob_temp (
    publisherid varchar(100),
    issuecode varchar(20),
    publishingjobcomment text,
    FULLTEXT(publishingjobcomment),
    KEY pk0 (publisherid, issuecode),
    KEY fk0 (issuecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_publishingjob.isv" INTO TABLE inducks_publishingjob_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_publishingjob;
RENAME TABLE inducks_publishingjob_temp TO inducks_publishingjob;

# SQL for re-creating and filling table inducks_character
DROP TABLE IF EXISTS inducks_character_temp;
CREATE TABLE inducks_character_temp (
    charactercode varchar(100),
    charactername varchar(100),
    official char(1),
    onetime char(1),
    heroonly char(1),
    charactercomment text,
    FULLTEXT(charactercomment),
    KEY pk0 (charactercode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_character.isv" INTO TABLE inducks_character_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_character;
RENAME TABLE inducks_character_temp TO inducks_character;

# SQL for re-creating and filling table inducks_charactername
DROP TABLE IF EXISTS inducks_charactername_temp;
CREATE TABLE inducks_charactername_temp (
    charactercode varchar(100),
    languagecode varchar(100),
    charactername varchar(100),
    preferred char(1),
    characternamecomment text,
    FULLTEXT(characternamecomment),
    KEY pk0 (charactercode, languagecode, charactername),
    KEY fk0 (languagecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_charactername.isv" INTO TABLE inducks_charactername_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_charactername;
RENAME TABLE inducks_charactername_temp TO inducks_charactername;

# SQL for re-creating and filling table inducks_characteralias
DROP TABLE IF EXISTS inducks_characteralias_temp;
CREATE TABLE inducks_characteralias_temp (
    charactercode varchar(100),
    charactername varchar(100),
    KEY pk0 (charactername),
    KEY fk0 (charactercode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_characteralias.isv" INTO TABLE inducks_characteralias_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_characteralias;
RENAME TABLE inducks_characteralias_temp TO inducks_characteralias;

# SQL for re-creating and filling table inducks_characterdetail
DROP TABLE IF EXISTS inducks_characterdetail_temp;
CREATE TABLE inducks_characterdetail_temp (
    charactername varchar(100),
    charactercode varchar(100),
    number int(7),
    KEY pk0 (charactercode),
    KEY fk0 (charactername)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_characterdetail.isv" INTO TABLE inducks_characterdetail_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_characterdetail;
RENAME TABLE inducks_characterdetail_temp TO inducks_characterdetail;

# SQL for re-creating and filling table inducks_subseries
DROP TABLE IF EXISTS inducks_subseries_temp;
CREATE TABLE inducks_subseries_temp (
    subseriescode varchar(100),
    subseriesname text,
    official char(1),
    important char(1),
    subseriescomment text,
    FULLTEXT(subseriesname,subseriescomment),
    KEY pk0 (subseriescode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_subseries.isv" INTO TABLE inducks_subseries_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_subseries;
RENAME TABLE inducks_subseries_temp TO inducks_subseries;

# SQL for re-creating and filling table inducks_subseriesname
DROP TABLE IF EXISTS inducks_subseriesname_temp;
CREATE TABLE inducks_subseriesname_temp (
    subseriescode varchar(100),
    languagecode varchar(100),
    subseriesname text,
    FULLTEXT(subseriesname),
    KEY pk0 (subseriescode, languagecode),
    KEY fk0 (languagecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_subseriesname.isv" INTO TABLE inducks_subseriesname_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_subseriesname;
RENAME TABLE inducks_subseriesname_temp TO inducks_subseriesname;

# SQL for re-creating and filling table inducks_universe
DROP TABLE IF EXISTS inducks_universe_temp;
CREATE TABLE inducks_universe_temp (
    universecode varchar(100),
    universecomment text,
    FULLTEXT(universecomment),
    KEY pk0 (universecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_universe.isv" INTO TABLE inducks_universe_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_universe;
RENAME TABLE inducks_universe_temp TO inducks_universe;

# SQL for re-creating and filling table inducks_ucrelation
DROP TABLE IF EXISTS inducks_ucrelation_temp;
CREATE TABLE inducks_ucrelation_temp (
    universecode varchar(100),
    charactercode varchar(100),
    KEY pk0 (universecode, charactercode),
    KEY fk0 (charactercode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_ucrelation.isv" INTO TABLE inducks_ucrelation_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_ucrelation;
RENAME TABLE inducks_ucrelation_temp TO inducks_ucrelation;

# SQL for re-creating and filling table inducks_universename
DROP TABLE IF EXISTS inducks_universename_temp;
CREATE TABLE inducks_universename_temp (
    universecode varchar(100),
    languagecode varchar(100),
    universename varchar(100),
    KEY pk0 (universecode, languagecode),
    KEY fk0 (languagecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_universename.isv" INTO TABLE inducks_universename_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_universename;
RENAME TABLE inducks_universename_temp TO inducks_universename;

# SQL for re-creating and filling table inducks_person
DROP TABLE IF EXISTS inducks_person_temp;
CREATE TABLE inducks_person_temp (
    personcode varchar(100),
    nationalitycountrycode varchar(100),
    fullname text,
    birthname text,
    official char(1),
    personcomment text,
    borndate varchar(10),
    bornplace varchar(100),
    deceaseddate varchar(10),
    deceasedplace varchar(100),
    education text,
    moviestext text,
    comicstext text,
    othertext text,
    photofilename varchar(100),
    photocomment text,
    photosource text,
    personrefs text,
    unknownstudiomember char(1),
    FULLTEXT(fullname,birthname,personcomment,education,moviestext,comicstext,othertext,photocomment,photosource,personrefs),
    KEY pk0 (personcode),
    KEY fk0 (nationalitycountrycode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_person.isv" INTO TABLE inducks_person_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_person;
RENAME TABLE inducks_person_temp TO inducks_person;

# SQL for re-creating and filling table inducks_personalias
DROP TABLE IF EXISTS inducks_personalias_temp;
CREATE TABLE inducks_personalias_temp (
    personcode varchar(100),
    surname varchar(100),
    givenname text,
    official char(1),
    FULLTEXT(givenname),
    KEY fk0 (personcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_personalias.isv" INTO TABLE inducks_personalias_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_personalias;
RENAME TABLE inducks_personalias_temp TO inducks_personalias;

# SQL for re-creating and filling table inducks_studio
DROP TABLE IF EXISTS inducks_studio_temp;
CREATE TABLE inducks_studio_temp (
    studiocode varchar(100),
    countrycode varchar(100),
    studioname varchar(100),
    city varchar(100),
    description text,
    othertext text,
    photofilename varchar(100),
    photocomment text,
    photosource text,
    studiorefs text,
    FULLTEXT(description,othertext,photocomment,photosource,studiorefs),
    KEY pk0 (studiocode),
    KEY fk0 (countrycode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_studio.isv" INTO TABLE inducks_studio_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_studio;
RENAME TABLE inducks_studio_temp TO inducks_studio;

# SQL for re-creating and filling table inducks_studiowork
DROP TABLE IF EXISTS inducks_studiowork_temp;
CREATE TABLE inducks_studiowork_temp (
    studiocode varchar(100),
    personcode varchar(100),
    KEY pk0 (studiocode, personcode),
    KEY fk0 (personcode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_studiowork.isv" INTO TABLE inducks_studiowork_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_studiowork;
RENAME TABLE inducks_studiowork_temp TO inducks_studiowork;

# SQL for re-creating and filling table inducks_site
DROP TABLE IF EXISTS inducks_site_temp;
CREATE TABLE inducks_site_temp (
    sitecode varchar(20),
    urlbase text,
    images char(1),
    sitename varchar(100),
    sitelogo varchar(100),
    FULLTEXT(urlbase),
    KEY pk0 (sitecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_site.isv" INTO TABLE inducks_site_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_site;
RENAME TABLE inducks_site_temp TO inducks_site;

# SQL for re-creating and filling table inducks_entryurl
DROP TABLE IF EXISTS inducks_entryurl_temp;
CREATE TABLE inducks_entryurl_temp (
    entrycode varchar(20),
    sitecode varchar(20),
    pagenumber int(7),
    url text,
    FULLTEXT(url),
    KEY fk0 (entrycode),
    KEY fk1 (sitecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_entryurl.isv" INTO TABLE inducks_entryurl_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_entryurl;
RENAME TABLE inducks_entryurl_temp TO inducks_entryurl;

# SQL for re-creating and filling table inducks_publicationurl
DROP TABLE IF EXISTS inducks_publicationurl_temp;
CREATE TABLE inducks_publicationurl_temp (
    publicationcode varchar(20),
    sitecode varchar(20),
    url text,
    FULLTEXT(url),
    KEY pk0 (publicationcode, sitecode),
    KEY fk0 (sitecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_publicationurl.isv" INTO TABLE inducks_publicationurl_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_publicationurl;
RENAME TABLE inducks_publicationurl_temp TO inducks_publicationurl;

# SQL for re-creating and filling table inducks_issueurl
DROP TABLE IF EXISTS inducks_issueurl_temp;
CREATE TABLE inducks_issueurl_temp (
    issuecode varchar(20),
    sitecode varchar(20),
    url text,
    FULLTEXT(url),
    KEY pk0 (issuecode, sitecode),
    KEY fk0 (sitecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_issueurl.isv" INTO TABLE inducks_issueurl_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_issueurl;
RENAME TABLE inducks_issueurl_temp TO inducks_issueurl;

# SQL for re-creating and filling table inducks_personurl
DROP TABLE IF EXISTS inducks_personurl_temp;
CREATE TABLE inducks_personurl_temp (
    personcode varchar(100),
    sitecode varchar(20),
    url text,
    FULLTEXT(url),
    KEY pk0 (personcode, sitecode),
    KEY fk0 (sitecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_personurl.isv" INTO TABLE inducks_personurl_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_personurl;
RENAME TABLE inducks_personurl_temp TO inducks_personurl;

# SQL for re-creating and filling table inducks_characterurl
DROP TABLE IF EXISTS inducks_characterurl_temp;
CREATE TABLE inducks_characterurl_temp (
    charactercode varchar(100),
    sitecode varchar(20),
    url text,
    FULLTEXT(url),
    KEY pk0 (charactercode, sitecode),
    KEY fk0 (sitecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_characterurl.isv" INTO TABLE inducks_characterurl_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_characterurl;
RENAME TABLE inducks_characterurl_temp TO inducks_characterurl;

# SQL for re-creating and filling table inducks_storyurl
DROP TABLE IF EXISTS inducks_storyurl_temp;
CREATE TABLE inducks_storyurl_temp (
    storycode varchar(20),
    sitecode varchar(20),
    url text,
    FULLTEXT(url),
    KEY pk0 (storycode, sitecode),
    KEY fk0 (sitecode)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

LOAD DATA LOCAL INFILE "./isv/inducks_storyurl.isv" INTO TABLE inducks_storyurl_temp CHARACTER SET utf8 FIELDS TERMINATED BY '^' IGNORE 1 LINES;
DROP TABLE IF EXISTS inducks_storyurl;
RENAME TABLE inducks_storyurl_temp TO inducks_storyurl;

# End of file
