# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0002_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gcd', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('count', models.IntegerField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stddata.Country')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stddata.Language')),
            ],
            options={
                'db_table': 'stats_count_stats',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentIndexedIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.Issue')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stddata.Language')),
            ],
            options={
                'db_table': 'stats_recent_indexed_issue',
            },
        ),
    ]
