"""Generate the user guide from verified reader workflows."""

from pathlib import Path
from urllib.parse import urlsplit

import pytest
from django.core.management import call_command
from playwright.sync_api import expect, sync_playwright

from apps.gcd.models import Character, Creator, Feature, Group, Issue, Series
from apps.stddata.models import Date


def markdown(text):
    text = ' '.join(text.split())
    for character in '\\`*_[]<>':
        text = text.replace(character, '\\' + character)
    return text


class WikiGuide:
    """Record browser actions as Markdown instructions and screenshots."""

    def __init__(self, page, base_url):
        self.page = page
        self.base_url = base_url
        self.images = {}
        self.lines = [
            '<style>',
            ':root {',
            '  --md-primary-fg-color: #6666ee;',
            '  --md-primary-fg-color--light: #b3cff8;',
            '  --md-primary-fg-color--dark: #444444;',
            '  --md-accent-fg-color: #a9302a;',
            '  --md-typeset-a-color: #0000ee;',
            '}',
            '</style>', '',
            '# GCD user guide', '',
            'These instructions and screenshots are generated together from '
            'tested browser actions and the current interface labels.', '',
        ]
        self.steps = []

    def document(self, filename, title):
        self.current_title = title
        self.lines.extend([f'## {title}', ''])
        self.steps = []

    def open(self, path):
        response = self.page.goto(self.base_url + path)
        assert response.status == 200
        self.steps.append(f'Open **{markdown(self.page.title())}** '
                          f'(`{path}`).')

    @staticmethod
    def label(locator, fallback):
        return locator.evaluate('''(element) => {
            const label = element.labels && element.labels[0];
            return element.getAttribute('aria-label') ||
                (label && label.innerText) ||
                element.getAttribute('placeholder') ||
                element.innerText || element.value || element.name || '';
        }''').strip() or fallback

    def select(self, locator, value):
        locator.select_option(value)
        option = locator.locator('option:checked').inner_text()
        self.steps.append(
            f'Select **{markdown(option)}** in the search selector.')

    def fill(self, locator, value):
        label = self.label(locator, 'field')
        locator.fill(value)
        if locator.get_attribute('type') == 'password':
            self.steps.append(f'Enter your password in **{markdown(label)}**.')
        else:
            self.steps.append(f'Enter **{markdown(value)}** '
                              f'in **{markdown(label)}**.')

    def click(self, locator, fallback='button'):
        label = self.label(locator, fallback)
        locator.click()
        self.steps.append(f'Select **{markdown(label)}**.')

    def capture(self, name, fields=False):
        self.page.wait_for_load_state('load')
        self.page.evaluate('document.fonts.ready')
        assert self.page.evaluate('document.styleSheets.length') > 0
        title = markdown(self.page.title().strip() or
                         self.current_title)
        self.lines.extend([f'### {title}', ''])
        self.lines.extend(f'{number}. {step}' for number, step in
                          enumerate(self.steps, start=1))
        self.lines.extend(['', f'![{title}](images/{name}.png)', ''])
        if fields:
            labels = self.page.locator(
                'form label:visible').all_text_contents()
            labels = list(dict.fromkeys(markdown(label) for label in labels
                                        if label.strip()))
            if labels:
                self.lines.extend(['Fields shown on this page:', ''])
                self.lines.extend(f'- {label}' for label in labels)
                self.lines.append('')
        self.images[name] = self.page.screenshot(
            full_page=True, animations='disabled', caret='hide')
        self.steps = []

    def write(self):
        root = Path(__file__).resolve().parents[2] / 'docs/wiki'
        (root / 'images').mkdir(parents=True, exist_ok=True)
        notice = '<!-- Generated by tests/wiki. Do not edit by hand. -->\n\n'
        self.lines.extend([
            '## Coverage', '',
            'The examples use fictional records marked **[GCD DEV]** and '
            'placeholder covers; search for real names on the public site.',
            '',
            'Coverage is limited to the workflows listed above. Editing, '
            'approval, cover uploads, administration and My Comics are not '
            'yet included. Business rules cannot be inferred from page '
            'labels.', '',
        ])
        (root / 'index.md').write_text(
            notice + '\n'.join(self.lines), encoding='utf-8')
        for name, data in self.images.items():
            (root / 'images' / f'{name}.png').write_bytes(data)


@pytest.fixture(scope='session')
def browser_context_args():
    return {
        'viewport': {'width': 1440, 'height': 1000},
        'locale': 'en-US',
        'timezone_id': 'UTC',
        'color_scheme': 'light',
        'reduced_motion': 'reduce',
        'device_scale_factor': 1,
    }


@pytest.fixture
def wiki_catalog(transactional_db, settings, tmp_path):
    settings.MEDIA_ROOT = str(tmp_path / 'media')
    settings.COMPRESS_ENABLED = False
    settings.LANGUAGE_CODE = 'en'
    settings.USE_TEMPLATESADMIN = False
    settings.ADVERTISING = False
    settings.USE_ELASTICSEARCH = False
    call_command('seed_development_data', verbosity=0)
    creator = Creator.objects.get(gcd_official_name='[GCD DEV] Alex Example')
    creator.birth_date = Date.objects.create(year='1970', month='01', day='01')
    creator.death_date = Date.objects.create()
    creator.save(update_fields=['birth_date', 'death_date'])
    series = Series.objects.get(name='[GCD DEV] Adventures')
    issue = Issue.objects.get(series=series, sort_code=1)
    return {
        'series': series.get_absolute_url(),
        'issue': issue.get_absolute_url(),
        'sections': [
            ('publisher', series.publisher.get_absolute_url(),
             '[GCD DEV] Example Comics'),
            ('creator', creator.get_absolute_url(), '[GCD DEV] Alex Example'),
            ('character', Character.objects.get(
                name='[GCD DEV] Captain Example').get_absolute_url(),
             '[GCD DEV] Captain Example'),
            ('group', Group.objects.get(
                name='[GCD DEV] Example League').get_absolute_url(),
             '[GCD DEV] Example League'),
            ('feature', Feature.objects.get(
                name='[GCD DEV] Feature').get_absolute_url(),
             '[GCD DEV] Feature'),
        ],
    }


@pytest.fixture
def page(wiki_catalog, live_server, browser_name, browser_type_launch_args,
         browser_context_args):
    # Start Playwright only after database setup and stop it before teardown.
    with sync_playwright() as playwright:
        browser = getattr(playwright, browser_name).launch(
            **browser_type_launch_args)
        try:
            yield browser.new_page(**browser_context_args)
        finally:
            browser.close()


def test_catalog_tutorial(wiki_catalog, live_server, page):
    origin = urlsplit(live_server.url).netloc
    failed_requests = []

    def local_requests_only(route):
        if urlsplit(route.request.url).netloc == origin:
            route.continue_()
        else:
            route.abort()

    def check_response(response):
        if (response.status >= 400 and
                response.request.resource_type in
                ('document', 'stylesheet', 'script')):
            failed_requests.append(response.url)

    page.route('**/*', local_requests_only)
    page.on('response', check_response)
    guide = WikiGuide(page, live_server.url)

    def search_for(kind, query):
        guide.open('/')
        search = page.locator('form[action="/search/"]').first
        guide.select(search.locator('select[name="search_type"]'), kind)
        guide.fill(search.locator('input[name="query"]'), query)
        guide.click(search.locator('[type="submit"]'), 'search button')

    guide.document('search', 'Search the catalog')
    guide.open('/')
    expect(page.locator('input[name="query"]')).to_be_visible()
    guide.capture('search-home')
    search_for('series', '[GCD DEV] Adventures')
    series_link = page.locator(f'a[href="{wiki_catalog["series"]}"]').first
    expect(series_link).to_be_visible()
    guide.capture('search-results')

    guide.document('catalog', 'Explore publishers, series and issues')
    search_for('series', '[GCD DEV] Adventures')
    guide.click(series_link)
    expect(page).to_have_url(live_server.url + wiki_catalog['series'])
    issue_link = page.locator(f'a[href="{wiki_catalog["issue"]}"]').first
    expect(issue_link).to_be_visible()
    guide.capture('series')
    guide.click(issue_link)
    expect(page).to_have_url(live_server.url + wiki_catalog['issue'])
    expect(page.locator('body')).to_contain_text('[GCD DEV] Adventures')
    guide.capture('issue')

    for kind, path, title in wiki_catalog['sections']:
        if kind == 'creator':
            guide.document('people-and-characters',
                           'Find creators, characters, groups and features')
        search_for(kind, title)
        link = page.locator(f'a[href="{path}"]').first
        expect(link).to_be_visible()
        guide.click(link)
        expect(page).to_have_url(live_server.url + path)
        expect(page.locator('body')).to_contain_text(title)
        guide.capture(kind)

    guide.document('advanced-search', 'Use advanced queries')
    guide.open('/')
    guide.click(page.locator('a[href="/search/advanced/"]:visible').first)
    expect(page.locator('#advanced_search_form')).to_be_visible()
    guide.capture('advanced-search', fields=True)

    guide.document('account', 'Open the sign-in form')
    guide.open('/')
    guide.click(page.locator('button.dropdown-toggle:visible').first,
                'account menu')
    guide.click(page.locator('input[name="login"]:visible').first)
    expect(page.locator('input[name="username"]')).to_be_visible()
    expect(page.locator('input[name="password"]')).to_be_visible()
    guide.capture('login', fields=True)

    assert not failed_requests, failed_requests
    guide.write()
