# -*- coding: utf-8 -*-
# translations of genre names. Once we have real considerations about
# internationalization this probably will be elsewhere
GENRES = {
    'de': ['Abenteuer',
           'Drama',
           'Humor',
           'Sachgeschichten',
           'Fürsprache',
           'Tier',
           'Anthropomorph',
           'Flieger',
           'Biografie',
           'Auto',
           'Kinder',
           'Verbrechen',
           'Detektive',
           'Familienleben',
           'Erotik',
           'Fantasy',
           'Mode',
           'Historie',
           'Geschichte',
           'Horror/Spannung',
           'Dschungel',
           'Kampfkunst',
           'Mathematik und Naturwissenschaft',
           'Arzt',
           'Militär',
           'Natur',
           'Religion',
           'Liebe',
           'Satire/Parodie',
           'Science-Fiction',
           'Sport',
           'Spionage',
           'Superhelden',
           'Heroische Fantasy',
           'Jugendliche',
           'Krieg',
           'Western'],
    'el': ['περιπέτεια',
           'δραματικό',
           'χιούμορ',
           'όχι μυθοπλασίας',
           '',
           'ζώα',
           'ανθρωπομορφικά ζώα',
           'αεροπορικό',
           'ιογραφικό',
           'αυτοκίνητα',
           'παιδικό',
           'αστυνομικό',
           'μυστήριο-νουάρ',
           'οικιακό',
           'ερωτικό',
           'φαντασία',
           'μόδα',
           'ιστορική φαντασία',
           'ιστορικό',
           'τρόμος-σασπένς',
           'ζούγκλα',
           'πολεμικές τέχνες',
           'φυσική και μαθηματικά',
           'ιατρικό',
           'στρατιωτικό',
           'φύση',
           'θρησκευτικό',
           'αισθηματικό',
           'σάτιρα-παρωδία',
           'επιστημονική φαντασία',
           'αθλητικό',
           'κατασκοπίας',
           'υπερηρωικό',
           'ηρωική φαντασία',
           'νεανικό',
           'πολεμικό',
           'γουέστερν'],
    'en': ['adventure',
           'drama',
           'humor',
           'non-fiction',
           'advocacy',
           'animal',
           'anthropomorphic-funny animals',
           'aviation',
           'biography',
           'car',
           'children',
           'crime',
           'detective-mystery',
           'domestic',
           'erotica',
           'fantasy',
           'fashion',
           'historical',
           'history',
           'horror-suspense',
           'jungle',
           'martial arts',
           'math & science',
           'medical',
           'military',
           'nature',
           'religious',
           'romance',
           'satire-parody',
           'science fiction',
           'sports',
           'spy',
           'superhero',
           'sword and sorcery',
           'teen',
           'war',
           'western-frontier'],
    'es': ['aventura',
           'drama',
           'humor',
           'hechos',
           'propaganda',
           'animales',
           'antropomorfo',
           'aviación',
           'biografía',
           'autos',
           'infantil',
           'crimen',
           'policíaco',
           'doméstico',
           'erótico',
           'fantasía',
           'moda',
           'histórico',
           'historia',
           'terror-suspenso',
           'jungla',
           'artes marciales',
           'científico',
           'medicina',
           'militar',
           'naturaleza',
           'religión',
           'amoroso',
           'sátira-parodia',
           'ciencia ficción',
           'deportes',
           'espionaje',
           'super-héroes',
           'espada y brujería',
           'juvenil',
           'guerra',
           'oeste'],
    'fr': ['aventure',
           'drame',
           'humour',
           'non fictif',
           'juridique',
           'animaux',
           'animaux anthropomorphes drôles',
           'aviation',
           'biographique',
           'automobile',
           'enfants',
           'criminel',
           'polar; policier',
           'domestique',
           'érotique',
           'fantasy',
           'mode',
           'historique',
           'histoire',
           'horreur-suspense',
           'jungle',
           'arts martiaux',
           'mathématiques et sciences',
           'médical',
           'militaire',
           'nature',
           'religieux',
           'roman d\'amour',
           'satire/parodie',
           'science-fiction',
           'sport',
           'espionnage',
           'super-héros',
           'heroic fantasy',
           'adolescents',
           'guerre',
           'western'],
    'it': ['avventura',
           '',
           'umoristico',
           'documentale',
           '',
           'animali',
           '',
           '',
           'biografico',
           '',
           '',
           'nero',
           'poliziesco',
           '',
           'erotico',
           'fantastico',
           '',
           'storico',
           '',
           'orrore',
           'giungla',
           '',
           'scienza',
           '',
           '',
           '',
           'religioso',
           'romantico',
           'satira-parodia',
           'fantascienza',
           'sportive',
           'spionaggio',
           'supereroe',
           '',
           '',
           'guerra',
           ''],
    'nl': ['avontuur',
           'drama',
           'humor',
           'feit',
           'voorspraak',
           'dieren',
           'antropomorfisch',
           'vliegeniers',
           'biografisch',
           'voertuigen',
           'kinderen',
           'misdaad',
           'detective',
           'gezinsleven',
           'erotika',
           'fantasy',
           'mode',
           'historisch',
           'geschiedenis',
           'horror/spanning',
           'jungle',
           'vechtkunst',
           'wetenschap',
           'medisch',
           'militair',
           'natuur',
           'religie',
           'romantiek',
           'satire/parodie',
           'science-fiction',
           'sport',
           'spionage',
           'superhelden',
           'sword-and-sorcery',
           'tiener',
           'oorlog',
           'wilde westen'],
    'no': ['eventyr',
           'drama',
           'humor',
           'fakta',
           '',
           'dyr',
           'antropomorfisme-funny animals',
           'fly',
           'biografi',
           'automobil',
           'barn',
           'krim',
           'detektiv-mysterium',
           '',
           'erotikk',
           'fantasy-overnaturlig',
           'mote',
           'historisk',
           'historie',
           'skrekk',
           'jungel',
           'kampsport',
           'matematikk og vitenskap',
           'legeroman',
           'militær',
           'natur',
           'religion',
           'romantikk',
           'satire-parodi',
           'science fiction',
           'sport',
           'spionasje',
           'superhelt',
           'sword and sorcery',
           'ungdom',
           'krig',
           'western'],
    'pt': ['aventura',
           'drama',
           'humor',
           'não-ficção',
           'direito',
           'animal',
           'antropomorfismo',
           'aviação',
           'biografia',
           'automóvel',
           'infantil',
           'crime',
           'detective-mistério',
           'doméstico',
           'erotismo',
           'fantasia',
           'moda',
           'histórico',
           'história',
           'terror-suspense',
           'selva',
           'artes marciais',
           'matemática e ciência',
           'medicina',
           'militar',
           'natureza',
           'religião',
           'romance',
           'sátira-paródia',
           'ficção científica',
           'desporto',
           'espionagem',
           'super-heróis',
           'espada e feitiçaria',
           'juvenil',
           'guerra',
           'velho oeste'],
}
