# -*- coding: utf-8 -*-
# translations of genre names. Once we have real considerations about
# internationalization this probably will be elsewhere
GENRES = {
    'de': [u'Abenteuer',
           u'Drama',
           u'Humor',
           u'Sachgeschichten',
           u'Fürsprache',
           u'Tier',
           u'Anthropomorph',
           u'Flieger',
           u'Biografie',
           u'Auto',
           u'Kinder',
           u'Verbrechen',
           u'Detektive',
           u'Familienleben',
           u'Erotik',
           u'Fantasy',
           u'Mode',
           u'Historie',
           u'Geschichte',
           u'Horror/Spannung',
           u'Dschungel',
           u'Kampfkunst',
           u'Mathematik und Naturwissenschaft',
           u'Arzt',
           u'Militär',
           u'Natur',
           u'Religion',
           u'Liebe',
           u'Satire/Parodie',
           u'Science-Fiction',
           u'Sport',
           u'Spionage',
           u'Superhelden',
           u'Heroische Fantasy',
           u'Jugendliche',
           u'Krieg',
           u'Western'],
    'el': [u'περιπέτεια',
           u'δραματικό',
           u'χιούμορ',
           u'όχι μυθοπλασίας',
           u'',
           u'ζώα',
           u'ανθρωπομορφικά ζώα',
           u'αεροπορικό',
           u'ιογραφικό',
           u'αυτοκίνητα',
           u'παιδικό',
           u'αστυνομικό',
           u'μυστήριο-νουάρ',
           u'οικιακό',
           u'ερωτικό',
           u'φαντασία',
           u'μόδα',
           u'ιστορική φαντασία',
           u'ιστορικό',
           u'τρόμος-σασπένς',
           u'ζούγκλα',
           u'πολεμικές τέχνες',
           u'φυσική και μαθηματικά',
           u'ιατρικό',
           u'στρατιωτικό',
           u'φύση',
           u'θρησκευτικό',
           u'αισθηματικό',
           u'σάτιρα-παρωδία',
           u'επιστημονική φαντασία',
           u'αθλητικό',
           u'κατασκοπίας',
           u'υπερηρωικό',
           u'ηρωική φαντασία',
           u'νεανικό',
           u'πολεμικό',
           u'γουέστερν'],
    'en': [u'adventure',
           u'drama',
           u'humor',
           u'non-fiction',
           u'advocacy',
           u'animal',
           u'anthropomorphic-funny animals',
           u'aviation',
           u'biography',
           u'car',
           u'children',
           u'crime',
           u'detective-mystery',
           u'domestic',
           u'erotica',
           u'fantasy',
           u'fashion',
           u'historical',
           u'history',
           u'horror-suspense',
           u'jungle',
           u'martial arts',
           u'math & science',
           u'medical',
           u'military',
           u'nature',
           u'religious',
           u'romance',
           u'satire-parody',
           u'science fiction',
           u'sports',
           u'spy',
           u'superhero',
           u'sword and sorcery',
           u'teen',
           u'war',
           u'western-frontier'],
    'es': [u'aventura',
           u'drama',
           u'humor',
           u'hechos',
           u'propaganda',
           u'animales',
           u'antropomorfo',
           u'aviación',
           u'biografía',
           u'autos',
           u'infantil',
           u'crimen',
           u'policíaco',
           u'doméstico',
           u'erótico',
           u'fantasía',
           u'moda',
           u'histórico',
           u'historia',
           u'terror-suspenso',
           u'jungla',
           u'artes marciales',
           u'científico',
           u'medicina',
           u'militar',
           u'naturaleza',
           u'religión',
           u'amoroso',
           u'sátira-parodia',
           u'ciencia ficción',
           u'deportes',
           u'espionaje',
           u'super-héroes',
           u'espada y brujería',
           u'juvenil',
           u'guerra',
           u'oeste'],
    'fr': [u'aventure',
           u'drame',
           u'humour',
           u'non fictif',
           u'juridique',
           u'animaux',
           u'animaux anthropomorphes drôles',
           u'aviation',
           u'biographique',
           u'automobile',
           u'enfants',
           u'criminel',
           u'polar; policier',
           u'domestique',
           u'érotique',
           u'fantasy',
           u'mode',
           u'historique',
           u'histoire',
           u'horreur-suspense',
           u'jungle',
           u'arts martiaux',
           u'mathématiques et sciences',
           u'médical',
           u'militaire',
           u'nature',
           u'religieux',
           u'roman d\'amour',
           u'satire/parodie',
           u'science-fiction',
           u'sport',
           u'espionnage',
           u'super-héros',
           u'heroic fantasy',
           u'adolescents',
           u'guerre',
           u'western'],
    'it': [u'avventura',
           u'',
           u'umoristico',
           u'documentale',
           u'',
           u'animali',
           u'',
           u'',
           u'biografico',
           u'',
           u'',
           u'nero',
           u'poliziesco',
           u'',
           u'erotico',
           u'fantastico',
           u'',
           u'storico',
           u'',
           u'orrore',
           u'giungla',
           u'',
           u'scienza',
           u'',
           u'',
           u'',
           u'religioso',
           u'romantico',
           u'satira-parodia',
           u'fantascienza',
           u'sportive',
           u'spionaggio',
           u'supereroe',
           u'',
           u'',
           u'guerra',
           u''],
    'nl': [u'avontuur',
           u'drama',
           u'humor',
           u'feit',
           u'voorspraak',
           u'dieren',
           u'antropomorfisch',
           u'vliegeniers',
           u'biografisch',
           u'voertuigen',
           u'kinderen',
           u'misdaad',
           u'detective',
           u'gezinsleven',
           u'erotika',
           u'fantasy',
           u'mode',
           u'historisch',
           u'geschiedenis',
           u'horror/spanning',
           u'jungle',
           u'vechtkunst',
           u'wetenschap',
           u'medisch',
           u'militair',
           u'natuur',
           u'religie',
           u'romantiek',
           u'satire/parodie',
           u'science-fiction',
           u'sport',
           u'spionage',
           u'superhelden',
           u'sword-and-sorcery',
           u'tiener',
           u'oorlog',
           u'wilde westen'],
    'no': [u'eventyr',
           u'drama',
           u'humor',
           u'fakta',
           u'',
           u'dyr',
           u'antropomorfisme-funny animals',
           u'fly',
           u'biografi',
           u'automobil',
           u'barn',
           u'krim',
           u'detektiv-mysterium',
           u'',
           u'erotikk',
           u'fantasy-overnaturlig',
           u'mote',
           u'historisk',
           u'historie',
           u'skrekk',
           u'jungel',
           u'kampsport',
           u'matematikk og vitenskap',
           u'legeroman',
           u'militær',
           u'natur',
           u'religion',
           u'romantikk',
           u'satire-parodi',
           u'science fiction',
           u'sport',
           u'spionasje',
           u'superhelt',
           u'sword and sorcery',
           u'ungdom',
           u'krig',
           u'western'],
    'pt': [u'aventura',
           u'drama',
           u'humor',
           u'não-ficção',
           u'direito',
           u'animal',
           u'antropomorfismo',
           u'aviação',
           u'biografia',
           u'automóvel',
           u'infantil',
           u'crime',
           u'detective-mistério',
           u'doméstico',
           u'erotismo',
           u'fantasia',
           u'moda',
           u'histórico',
           u'história',
           u'terror-suspense',
           u'selva',
           u'artes marciais',
           u'matemática e ciência',
           u'medicina',
           u'militar',
           u'natureza',
           u'religião',
           u'romance',
           u'sátira-paródia',
           u'ficção científica',
           u'desporto',
           u'espionagem',
           u'super-heróis',
           u'espada e feitiçaria',
           u'juvenil',
           u'guerra',
           u'velho oeste'],
}
