# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 07:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexer',
            name='seen_privacy_policy',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
