# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 11:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_indexer_seen_privacy_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexer',
            options={'ordering': ['user__last_name', 'user__first_name'], 'permissions': (('can_upload_cover', 'Can upload covers'), ('can_reserve', 'Can reserve a record for add, edit or delete'), ('can_approve', 'Can approve a change to a record'), ('can_cancel', 'Can cancel a pending change they did not open'), ('can_mentor', 'Can mentor new indexers'), ('can_vote', 'Can vote in GCD elections'), ('can_publish', 'Can publish non-database content on the web site'), ('can_contact', 'Can see list of users who have opted-in'), ('on_board', 'Is on the Board of Directors'))},
        ),
    ]
