# Generated by Django 2.2.12 on 2020-12-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0033_add_characters'),
        ('indexer', '0003_contacting_for_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexer',
            name='no_show_sequences',
            field=models.ManyToManyField(db_table='gcd_indexer_no_show_sequences', related_name='indexers', to='gcd.StoryType'),
        ),
    ]
