# Generated by Django 2.2.12 on 2021-01-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_indexer_no_show_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexer',
            name='cover_letterer_creator_only',
            field=models.BooleanField(default=False),
        ),
    ]
