# Generated by Django 4.2.20 on 2025-04-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0006_indexer_use_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexer',
            name='reprint_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='indexer',
            name='variant_threshold',
            field=models.IntegerField(default=6),
        ),
    ]
