# Generated by Django 4.2.20 on 2025-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0007_summary_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexer',
            name='cache_size',
            field=models.IntegerField(default=3),
        ),
    ]
