# Generated by Django 5.2.9 on 2025-12-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0008_indexer_cache_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexer',
            name='items_per_page',
            field=models.IntegerField(default=-1),
        ),
    ]
