# -*- coding: utf-8 -*-


from django.db import models, migrations
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0001_initial'),
        ('gcd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGroupRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('year_began', models.IntegerField(null=True, blank=True)),
                ('year_ended', models.IntegerField(null=True, blank=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('keywords', models.TextField(default='', blank=True)),
                ('url', models.URLField(blank=True)),
                ('brand_group', models.ForeignKey(related_name='revisions', to='gcd.BrandGroup', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_brand_group_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BrandRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('year_began', models.IntegerField(null=True, blank=True)),
                ('year_ended', models.IntegerField(null=True, blank=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('keywords', models.TextField(default='', blank=True)),
                ('url', models.URLField(blank=True)),
                ('brand', models.ForeignKey(related_name='revisions', to='gcd.Brand', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_brand_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BrandUseRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=255, blank=True)),
                ('brand_use', models.ForeignKey(related_name='revisions', to='gcd.BrandUse', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_brand_use_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Changeset',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('state', models.IntegerField(db_index=True)),
                ('change_type', models.IntegerField(db_index=True)),
                ('migrated', models.BooleanField(default=False, db_index=True)),
                ('date_inferred', models.BooleanField(default=False)),
                ('imps', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('along_with', models.ManyToManyField(related_name='changesets_assisting', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(related_name='approved_changeset', to=settings.AUTH_USER_MODEL, null=True)),
                ('indexer', models.ForeignKey(related_name='changesets', to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.ManyToManyField(related_name='changesets_source', to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ChangesetComment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('text', models.TextField()),
                ('revision_id', models.IntegerField(null=True, db_index=True)),
                ('old_state', models.IntegerField()),
                ('new_state', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changeset', models.ForeignKey(related_name='comments', to='oi.Changeset')),
                ('commenter', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType', null=True)),
            ],
            options={
                'ordering': ['created'],
                'db_table': 'oi_changeset_comment',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CoverRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('marked', models.BooleanField(default=False)),
                ('is_replacement', models.BooleanField(default=False)),
                ('is_wraparound', models.BooleanField(default=False)),
                ('front_left', models.IntegerField(default=0, null=True)),
                ('front_right', models.IntegerField(default=0, null=True)),
                ('front_bottom', models.IntegerField(default=0, null=True)),
                ('front_top', models.IntegerField(default=0, null=True)),
                ('file_source', models.CharField(max_length=255, null=True)),
                ('changeset', models.ForeignKey(related_name='coverrevisions', to='oi.Changeset')),
                ('cover', models.ForeignKey(related_name='revisions', to='gcd.Cover', null=True)),
                ('issue', models.ForeignKey(related_name='cover_revisions', to='gcd.Issue')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_cover_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ImageRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.PositiveIntegerField(null=True, db_index=True)),
                ('image_file', models.ImageField(upload_to='img/gcd/new_generic_images//%m_%Y')),
                ('marked', models.BooleanField(default=False)),
                ('is_replacement', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='imagerevisions', to='oi.Changeset')),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType', null=True)),
                ('image', models.ForeignKey(related_name='revisions', to='gcd.Image', null=True)),
                ('type', models.ForeignKey(to='gcd.ImageType')),
            ],
            options={
                'ordering': ['created'],
                'db_table': 'oi_image_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IndiciaPublisherRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('year_began', models.IntegerField(null=True, blank=True)),
                ('year_ended', models.IntegerField(null=True, blank=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('keywords', models.TextField(default='', blank=True)),
                ('url', models.URLField(blank=True)),
                ('is_surrogate', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='indiciapublisherrevisions', to='oi.Changeset')),
                ('country', models.ForeignKey(related_name='indicia_publishers_revisions', to='stddata.Country')),
                ('indicia_publisher', models.ForeignKey(related_name='revisions', to='gcd.IndiciaPublisher', null=True)),
                ('parent', models.ForeignKey(related_name='indicia_publisher_revisions', blank=True, to='gcd.Publisher', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_indicia_publisher_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IssueRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('revision_sort_code', models.IntegerField(null=True)),
                ('reservation_requested', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=50)),
                ('title', models.CharField(default='', max_length=255, blank=True)),
                ('no_title', models.BooleanField(default=False)),
                ('volume', models.CharField(default='', max_length=50, blank=True)),
                ('no_volume', models.BooleanField(default=False)),
                ('display_volume_with_number', models.BooleanField(default=False)),
                ('variant_name', models.CharField(default='', max_length=255, blank=True)),
                ('publication_date', models.CharField(default='', max_length=255, blank=True)),
                ('key_date', models.CharField(default='', max_length=10, blank=True, validators=[django.core.validators.RegexValidator('^(17|18|19|20)\\d{2}(\\.|-)(0[0-9]|1[0-3])(\\.|-)\\d{2}$')])),
                ('year_on_sale', models.IntegerField(db_index=True, null=True, blank=True)),
                ('month_on_sale', models.IntegerField(db_index=True, null=True, blank=True)),
                ('day_on_sale', models.IntegerField(db_index=True, null=True, blank=True)),
                ('on_sale_date_uncertain', models.BooleanField(default=False)),
                ('indicia_frequency', models.CharField(default='', max_length=255, blank=True)),
                ('no_indicia_frequency', models.BooleanField(default=False)),
                ('price', models.CharField(default='', max_length=255, blank=True)),
                ('page_count', models.DecimalField(default=None, null=True, max_digits=10, decimal_places=3, blank=True)),
                ('page_count_uncertain', models.BooleanField(default=False)),
                ('editing', models.TextField(default='', blank=True)),
                ('no_editing', models.BooleanField(default=False)),
                ('notes', models.TextField(default='', blank=True)),
                ('keywords', models.TextField(default='', blank=True)),
                ('indicia_pub_not_printed', models.BooleanField(default=False)),
                ('no_brand', models.BooleanField(default=False)),
                ('isbn', models.CharField(default='', max_length=32, blank=True)),
                ('no_isbn', models.BooleanField(default=False)),
                ('barcode', models.CharField(default='', max_length=38, blank=True)),
                ('no_barcode', models.BooleanField(default=False)),
                ('rating', models.CharField(default='', max_length=255, blank=True)),
                ('no_rating', models.BooleanField(default=False)),
                ('date_inferred', models.BooleanField(default=False)),
                ('after', models.ForeignKey(related_name='after_revisions', blank=True, to='gcd.Issue', null=True)),
                ('brand', models.ForeignKey(related_name='issue_revisions', default=None, blank=True, to='gcd.Brand', null=True)),
                ('changeset', models.ForeignKey(related_name='issuerevisions', to='oi.Changeset')),
                ('indicia_publisher', models.ForeignKey(related_name='issue_revisions', default=None, blank=True, to='gcd.IndiciaPublisher', null=True)),
                ('issue', models.ForeignKey(related_name='revisions', to='gcd.Issue', null=True)),
                ('series', models.ForeignKey(related_name='issue_revisions', to='gcd.Series')),
                ('variant_of', models.ForeignKey(related_name='variant_revisions', to='gcd.Issue', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_issue_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OngoingReservation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('along_with', models.ManyToManyField(related_name='ongoing_assisting', to=settings.AUTH_USER_MODEL)),
                ('indexer', models.ForeignKey(related_name='ongoing_reservations', to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.ManyToManyField(related_name='ongoing_source', to=settings.AUTH_USER_MODEL)),
                ('series', models.OneToOneField(related_name='ongoing_reservation', to='gcd.Series')),
            ],
            options={
                'db_table': 'oi_ongoing_reservation',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PublisherRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('year_began', models.IntegerField(null=True, blank=True)),
                ('year_ended', models.IntegerField(null=True, blank=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('keywords', models.TextField(default='', blank=True)),
                ('url', models.URLField(blank=True)),
                ('is_master', models.BooleanField(default=True, db_index=True)),
                ('date_inferred', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='publisherrevisions', to='oi.Changeset')),
                ('country', models.ForeignKey(to='stddata.Country')),
                ('parent', models.ForeignKey(related_name='imprint_revisions', default=None, blank=True, to='gcd.Publisher', null=True)),
                ('publisher', models.ForeignKey(related_name='revisions', to='gcd.Publisher', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_publisher_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReprintRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(default='', max_length=255)),
                ('in_type', models.IntegerField(null=True, db_index=True)),
                ('out_type', models.IntegerField(null=True, db_index=True)),
                ('changeset', models.ForeignKey(related_name='reprintrevisions', to='oi.Changeset')),
                ('issue_reprint', models.ForeignKey(related_name='revisions', to='gcd.IssueReprint', null=True)),
                ('origin_issue', models.ForeignKey(related_name='origin_reprint_revisions', to='gcd.Issue', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_reprint_revision',
                'get_latest_by': 'created',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SeriesBondRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(default='', max_length=255, blank=True)),
                ('bond_type', models.ForeignKey(related_name='bond_revisions', to='gcd.SeriesBondType', null=True)),
                ('changeset', models.ForeignKey(related_name='seriesbondrevisions', to='oi.Changeset')),
                ('origin', models.ForeignKey(related_name='origin_bond_revisions', to='gcd.Series', null=True)),
                ('origin_issue', models.ForeignKey(related_name='origin_series_bond_revisions', to='gcd.Issue', null=True)),
                ('previous_revision', models.OneToOneField(related_name='next_revision', null=True, to='oi.SeriesBondRevision')),
                ('series_bond', models.ForeignKey(related_name='revisions', to='gcd.SeriesBond', null=True)),
                ('target', models.ForeignKey(related_name='target_bond_revisions', to='gcd.Series', null=True)),
                ('target_issue', models.ForeignKey(related_name='target_series_bond_revisions', to='gcd.Issue', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_series_bond_revision',
                'get_latest_by': 'created',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SeriesRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('reservation_requested', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('leading_article', models.BooleanField(default=False)),
                ('format', models.CharField(max_length=255, blank=True)),
                ('color', models.CharField(max_length=255, blank=True)),
                ('dimensions', models.CharField(max_length=255, blank=True)),
                ('paper_stock', models.CharField(max_length=255, blank=True)),
                ('binding', models.CharField(max_length=255, blank=True)),
                ('publishing_format', models.CharField(max_length=255, blank=True)),
                ('year_began', models.IntegerField()),
                ('year_ended', models.IntegerField(null=True, blank=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('publication_notes', models.TextField(blank=True)),
                ('tracking_notes', models.TextField(blank=True)),
                ('has_barcode', models.BooleanField(default=False)),
                ('has_indicia_frequency', models.BooleanField(default=False)),
                ('has_isbn', models.BooleanField(default=False)),
                ('has_issue_title', models.BooleanField(default=False)),
                ('has_volume', models.BooleanField(default=False)),
                ('has_rating', models.BooleanField(default=False)),
                ('is_comics_publication', models.BooleanField(default=False)),
                ('is_singleton', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('keywords', models.TextField(default='', blank=True)),
                ('date_inferred', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='seriesrevisions', to='oi.Changeset')),
                ('country', models.ForeignKey(related_name='series_revisions', to='stddata.Country')),
                ('imprint', models.ForeignKey(related_name='imprint_series_revisions', default=None, blank=True, to='gcd.Publisher', null=True)),
                ('language', models.ForeignKey(related_name='series_revisions', to='stddata.Language')),
                ('publication_type', models.ForeignKey(blank=True, to='gcd.SeriesPublicationType', null=True)),
                ('publisher', models.ForeignKey(related_name='series_revisions', to='gcd.Publisher')),
                ('series', models.ForeignKey(related_name='revisions', to='gcd.Series', null=True)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_series_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StoryRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255, blank=True)),
                ('title_inferred', models.BooleanField(default=False)),
                ('feature', models.CharField(max_length=255, blank=True)),
                ('sequence_number', models.IntegerField()),
                ('page_count', models.DecimalField(null=True, max_digits=10, decimal_places=3, blank=True)),
                ('page_count_uncertain', models.BooleanField(default=False)),
                ('script', models.TextField(blank=True)),
                ('pencils', models.TextField(blank=True)),
                ('inks', models.TextField(blank=True)),
                ('colors', models.TextField(blank=True)),
                ('letters', models.TextField(blank=True)),
                ('editing', models.TextField(blank=True)),
                ('no_script', models.BooleanField(default=False)),
                ('no_pencils', models.BooleanField(default=False)),
                ('no_inks', models.BooleanField(default=False)),
                ('no_colors', models.BooleanField(default=False)),
                ('no_letters', models.BooleanField(default=False)),
                ('no_editing', models.BooleanField(default=False)),
                ('job_number', models.CharField(max_length=25, blank=True)),
                ('genre', models.CharField(max_length=255, blank=True)),
                ('characters', models.TextField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('reprint_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('keywords', models.TextField(default='', blank=True)),
                ('date_inferred', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='storyrevisions', to='oi.Changeset')),
                ('issue', models.ForeignKey(related_name='story_revisions', to='gcd.Issue', null=True)),
                ('story', models.ForeignKey(related_name='revisions', to='gcd.Story', null=True)),
                ('type', models.ForeignKey(to='gcd.StoryType')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'db_table': 'oi_story_revision',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='origin_revision',
            field=models.ForeignKey(related_name='origin_reprint_revisions', to='oi.StoryRevision', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='origin_story',
            field=models.ForeignKey(related_name='origin_reprint_revisions', to='gcd.Story', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='previous_revision',
            field=models.OneToOneField(related_name='next_revision', null=True, to='oi.ReprintRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='reprint',
            field=models.ForeignKey(related_name='revisions', to='gcd.Reprint', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='reprint_from_issue',
            field=models.ForeignKey(related_name='revisions', to='gcd.ReprintFromIssue', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='reprint_to_issue',
            field=models.ForeignKey(related_name='revisions', to='gcd.ReprintToIssue', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='target_issue',
            field=models.ForeignKey(related_name='target_reprint_revisions', to='gcd.Issue', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='target_revision',
            field=models.ForeignKey(related_name='target_reprint_revisions', to='oi.StoryRevision', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='target_story',
            field=models.ForeignKey(related_name='target_reprint_revisions', to='gcd.Story', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='branduserevision',
            name='changeset',
            field=models.ForeignKey(related_name='branduserevisions', to='oi.Changeset'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='branduserevision',
            name='emblem',
            field=models.ForeignKey(related_name='use_revisions', to='gcd.Brand', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='branduserevision',
            name='publisher',
            field=models.ForeignKey(related_name='brand_use_revisions', to='gcd.Publisher', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='changeset',
            field=models.ForeignKey(related_name='brandrevisions', to='oi.Changeset'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='group',
            field=models.ManyToManyField(related_name='brand_revisions', to='gcd.BrandGroup'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='parent',
            field=models.ForeignKey(related_name='brand_revisions', blank=True, to='gcd.Publisher', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brandgrouprevision',
            name='changeset',
            field=models.ForeignKey(related_name='brandgrouprevisions', to='oi.Changeset'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brandgrouprevision',
            name='parent',
            field=models.ForeignKey(related_name='brand_group_revisions', blank=True, to='gcd.Publisher', null=True),
            preserve_default=True,
        ),
    ]
