# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0003_language_native_name'),
        ('gcd', '0003_creators'),
        ('contenttypes', '0001_initial'),
        ('oi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorArtInfluenceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('influence_name', models.CharField(max_length=200, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatorartinfluencerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='art_influence_revisions', to='gcd.Creator')),
                ('creator_artinfluence', models.ForeignKey(related_name='revisions', to='gcd.ArtInfluence', null=True)),
                ('influence_link', models.ForeignKey(related_name='influenced_revisions', blank=True, to='gcd.Creator', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_art_influence_revision',
                'verbose_name_plural': 'Creator Art Influence Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorAwardRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('award_name', models.CharField(max_length=255)),
                ('award_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('award_year_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('award', models.ForeignKey(blank=True, to='gcd.AwardType', null=True)),
                ('changeset', models.ForeignKey(related_name='creatorawardrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='award_revisions', to='gcd.Creator')),
                ('creator_award', models.ForeignKey(related_name='revisions', to='gcd.Award', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_award_revision',
                'verbose_name_plural': 'Creator Award Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorDataSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('revision_id', models.IntegerField(null=True, db_index=True)),
                ('source_description', models.TextField()),
                ('field', models.CharField(max_length=256)),
                ('changeset', models.ForeignKey(related_name='creatordatasourcerevisions', to='oi.Changeset')),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType', null=True)),
                ('creator_data_source', models.ForeignKey(related_name='revisions', to='gcd.CreatorDataSource', null=True)),
                ('source_type', models.ForeignKey(to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_data_source_revision',
                'verbose_name_plural': 'Creator Data Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorDegreeDetailRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('degree_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('degree_year_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatordegreedetailrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='degree_revisions', to='gcd.Creator')),
                ('creator_degree_detail', models.ForeignKey(related_name='revisions', to='gcd.CreatorDegreeDetail', null=True)),
                ('degree', models.ForeignKey(related_name='cr_degreedetails', to='gcd.Degree')),
                ('school', models.ForeignKey(related_name='cr_schooldetails', to='gcd.School', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_degree_detail_revision',
                'verbose_name_plural': 'Creator Degree Detail Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorMembershipRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('membership_year_began', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('membership_year_began_uncertain', models.BooleanField(default=False)),
                ('membership_year_ended', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('membership_year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatormembershiprevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='membership_revisions', to='gcd.Creator')),
                ('creator_membership', models.ForeignKey(related_name='revisions', to='gcd.Membership', null=True)),
                ('membership_type', models.ForeignKey(related_name='cr_membershiptype', blank=True, to='gcd.MembershipType', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_membership_revision',
                'verbose_name_plural': 'Creator Membership Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorNameDetailRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('changeset', models.ForeignKey(related_name='creatornamedetailrevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['type__id', 'created', '-id'],
                'db_table': 'oi_creator_name_detail_revision',
                'verbose_name_plural': 'Creator Name Detail Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorNonComicWorkRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('publication_title', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=200, null=True, blank=True)),
                ('work_title', models.CharField(max_length=255, null=True, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatornoncomicworkrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='non_comic_work_revisions', to='gcd.Creator')),
                ('creator_noncomicwork', models.ForeignKey(related_name='revisions', to='gcd.NonComicWork', null=True)),
                ('work_role', models.ForeignKey(related_name='cr_workrole', blank=True, to='gcd.NonComicWorkRole', null=True)),
                ('work_type', models.ForeignKey(related_name='cr_worktype', blank=True, to='gcd.NonComicWorkType', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_non_comic_work_revision',
                'verbose_name_plural': 'Creator NonComicWork Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('gcd_official_name', models.CharField(max_length=255, db_index=True)),
                ('birth_country_uncertain', models.BooleanField(default=False)),
                ('birth_province', models.CharField(max_length=50, null=True, blank=True)),
                ('birth_province_uncertain', models.BooleanField(default=False)),
                ('birth_city', models.CharField(max_length=200, null=True, blank=True)),
                ('birth_city_uncertain', models.BooleanField(default=False)),
                ('death_country_uncertain', models.BooleanField(default=False)),
                ('death_province', models.CharField(max_length=50, null=True, blank=True)),
                ('death_province_uncertain', models.BooleanField(default=False)),
                ('death_city', models.CharField(max_length=200, null=True, blank=True)),
                ('death_city_uncertain', models.BooleanField(default=False)),
                ('whos_who', models.URLField(null=True, blank=True)),
                ('bio', models.TextField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('birth_country', models.ForeignKey(related_name='cr_birth_country', blank=True, to='stddata.Country', null=True)),
                ('birth_date', models.ForeignKey(related_name='+', blank=True, to='stddata.Date', null=True)),
                ('changeset', models.ForeignKey(related_name='creatorrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='revisions', to='gcd.Creator', null=True)),
                ('data_source', models.ManyToManyField(to='oi.CreatorDataSourceRevision', null=True, blank=True)),
                ('death_country', models.ForeignKey(related_name='cr_death_country', blank=True, to='stddata.Country', null=True)),
                ('death_date', models.ForeignKey(related_name='+', blank=True, to='stddata.Date', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorSchoolDetailRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('school_year_began', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('school_year_began_uncertain', models.BooleanField(default=False)),
                ('school_year_ended', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('school_year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatorschooldetailrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='school_revisions', to='gcd.Creator')),
                ('creator_school_detail', models.ForeignKey(related_name='revisions', to='gcd.CreatorSchoolDetail', null=True)),
                ('school', models.ForeignKey(related_name='cr_school_details', to='gcd.School')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_school_detail_revision',
                'verbose_name_plural': 'Creator School Detail Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NameRelationRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('changeset', models.ForeignKey(related_name='namerelationrevisions', to='oi.Changeset')),
                ('gcd_official_name', models.ForeignKey(related_name='cr_gcd_official_name', to='oi.CreatorNameDetailRevision')),
                ('name_relation', models.ForeignKey(related_name='revisions', to='gcd.NameRelation', null=True)),
                ('rel_type', models.ForeignKey(related_name='cr_relation_type', blank=True, to='gcd.RelationType', null=True)),
                ('to_name', models.ForeignKey(related_name='cr_to_name', to='oi.CreatorNameDetailRevision')),
            ],
            options={
                'ordering': ('gcd_official_name', 'rel_type', 'to_name'),
                'db_table': 'oi_namerelation_revision',
                'verbose_name_plural': 'Name Relation Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NonComicWorkLinkRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('link', models.URLField(max_length=255)),
                ('changeset', models.ForeignKey(related_name='noncomicworklinkrevisions', to='oi.Changeset')),
                ('creator_noncomicworklink', models.ForeignKey(related_name='revisions', to='gcd.NonComicWorkLink', null=True)),
                ('non_comic_work', models.ForeignKey(related_name='cr_noncomicworklinks', to='oi.CreatorNonComicWorkRevision')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_non_comic_work_link_revision',
                'verbose_name_plural': 'NonComic Work Link Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NonComicWorkYearRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('work_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('work_year_uncertain', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='noncomicworkyearrevisions', to='oi.Changeset')),
                ('creator_noncomicworkyear', models.ForeignKey(related_name='revisions', to='gcd.NonComicWorkYear', null=True)),
                ('non_comic_work', models.ForeignKey(related_name='cr_noncomicworkyears', to='oi.CreatorNonComicWorkRevision')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_non_comic_work_year_revision',
                'verbose_name_plural': 'NonComic Work Year Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creator_names', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='creator_name_detail',
            field=models.ForeignKey(related_name='revisions', to='gcd.CreatorNameDetail', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='type',
            field=models.ForeignKey(related_name='cr_nametypes', blank=True, to='gcd.NameType', null=True),
            preserve_default=True,
        ),
        migrations.AlterModelOptions(
            name='imagerevision',
            options={'ordering': ['created', '-id']},
        ),
    ]
