# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True)),
                ('changeset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_locks', to='oi.Changeset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'oi_revision_lock',
            },
        ),
        migrations.AlterUniqueTogether(
            name='revisionlock',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
