# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0002_initial_data'),
        ('gcd', '0003_creators'),
        ('oi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('bio_source', models.ForeignKey(related_name='cr_bio_source', to='gcd.BioSource', null=True)),
                ('changeset', models.ForeignKey(related_name='biosourcerevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_bio_source_revision',
                'verbose_name_plural': 'Bio Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BirthCitySourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('birth_city_source', models.ForeignKey(related_name='cr_birth_city_source', to='gcd.BirthCitySource', null=True)),
                ('changeset', models.ForeignKey(related_name='birthcitysourcerevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_birth_city_source_revision',
                'verbose_name_plural': 'Birth City Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BirthCountrySourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('birth_country_source', models.ForeignKey(related_name='cr_birth_country_source', to='gcd.BirthCountrySource', null=True)),
                ('changeset', models.ForeignKey(related_name='birthcountrysourcerevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_birth_country_source_revision',
                'verbose_name_plural': 'Birth Country Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BirthDateSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('birth_date_source', models.ForeignKey(related_name='cr_birth_date_source', to='gcd.BirthDateSource', null=True)),
                ('changeset', models.ForeignKey(related_name='birthdatesourcerevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_birth_date_source_revision',
                'verbose_name_plural': 'Birth Date Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BirthMonthSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('birth_month_source', models.ForeignKey(related_name='cr_birth_month_source', to='gcd.BirthMonthSource', null=True)),
                ('changeset', models.ForeignKey(related_name='birthmonthsourcerevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_birth_month_source_revision',
                'verbose_name_plural': 'Birth Month Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BirthProvinceSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('birth_province_source', models.ForeignKey(related_name='cr_birth_province_source', to='gcd.BirthProvinceSource', null=True)),
                ('changeset', models.ForeignKey(related_name='birthprovincesourcerevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_birth_province_source_revision',
                'verbose_name_plural': 'Birth Province Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BirthYearSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('birth_year_source', models.ForeignKey(related_name='cr_birth_year_source', to='gcd.BirthYearSource', null=True)),
                ('changeset', models.ForeignKey(related_name='birthyearsourcerevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_birth_year_source_revision',
                'verbose_name_plural': 'Birth Year Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorArtInfluenceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('influence_name', models.CharField(max_length=200)),
                ('is_self_identify', models.BooleanField(default=False)),
                ('self_identify_influences_doc', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='creatorartinfluencerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creator_artinfluence', to='gcd.Creator')),
                ('creator_artinfluence', models.ForeignKey(related_name='revisions', to='gcd.ArtInfluence', null=True)),
                ('influence_link', models.ForeignKey(related_name='cr_influencelink', blank=True, to='gcd.Creator', null=True)),
                ('influence_source', models.ManyToManyField(related_name='cr_influencesource', null=True, to='gcd.SourceType', blank=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_art_influence_revision',
                'verbose_name_plural': 'Creator Art Influence Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorAwardRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('award_name', models.CharField(max_length=255)),
                ('award_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('award_year_uncertain', models.BooleanField(default=False)),
                ('award_source', models.ManyToManyField(related_name='cr_awardsource', null=True, to='gcd.SourceType', blank=True)),
                ('changeset', models.ForeignKey(related_name='creatorawardrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creator_award', to='gcd.Creator')),
                ('creator_award', models.ForeignKey(related_name='revisions', to='gcd.Award', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_award_revision',
                'verbose_name_plural': 'Creator Award Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorDegreeDetailRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('degree_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('degree_year_uncertain', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='creatordegreedetailrevisions', to='oi.Changeset')),
                ('creater_degree_detail', models.ForeignKey(related_name='cr_creater_degree_detail', to='gcd.CreatorDegreeDetail', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_degree_detail_revision',
                'verbose_name_plural': 'Creator Degree Detail Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorMembershipRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('membership_begin_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('membership_begin_year_uncertain', models.BooleanField(default=False)),
                ('membership_end_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('membership_end_year_uncertain', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='creatormembershiprevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creator_membership', to='gcd.Creator')),
                ('creator_membership', models.ForeignKey(related_name='revisions', to='gcd.Membership', null=True)),
                ('membership_source', models.ManyToManyField(related_name='cr_membershipsource', null=True, to='gcd.SourceType', blank=True)),
                ('membership_type', models.ForeignKey(related_name='cr_membershiptype', blank=True, to='gcd.MembershipType', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_membership_revision',
                'verbose_name_plural': 'Creator Membership Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorNameDetailsRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('description', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='creatornamedetailsrevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_name_details_revision',
                'verbose_name_plural': 'Creator Name Detail Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorNonComicWorkRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('publication_title', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=200, null=True, blank=True)),
                ('work_title', models.CharField(max_length=255, null=True, blank=True)),
                ('work_notes', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='creatornoncomicworkrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creator_noncomicwork', to='gcd.Creator')),
                ('creator_noncomicwork', models.ForeignKey(related_name='revisions', to='gcd.NonComicWork', null=True)),
                ('work_role', models.ForeignKey(related_name='cr_workrole', blank=True, to='gcd.NonComicWorkRole', null=True)),
                ('work_source', models.ManyToManyField(related_name='cr_worksource', null=True, to='gcd.SourceType', blank=True)),
                ('work_type', models.ForeignKey(related_name='cr_worktype', blank=True, to='gcd.NonComicWorkType', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_non_comic_work_revision',
                'verbose_name_plural': 'Creator NonComicWork Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('gcd_official_name', models.CharField(max_length=255, db_index=True)),
                ('birth_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('birth_year_uncertain', models.BooleanField(default=False)),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, null=True, choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')])),
                ('birth_month_uncertain', models.BooleanField(default=False)),
                ('birth_date', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('birth_date_uncertain', models.BooleanField(default=False)),
                ('death_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('death_year_uncertain', models.BooleanField(default=False)),
                ('death_month', models.PositiveSmallIntegerField(blank=True, null=True, choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')])),
                ('death_month_uncertain', models.BooleanField(default=False)),
                ('death_date', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('death_date_uncertain', models.BooleanField(default=False)),
                ('whos_who', models.URLField(null=True, blank=True)),
                ('birth_country_uncertain', models.BooleanField(default=False)),
                ('birth_province', models.CharField(max_length=50, null=True, blank=True)),
                ('birth_province_uncertain', models.BooleanField(default=False)),
                ('birth_city', models.CharField(max_length=200, null=True, blank=True)),
                ('birth_city_uncertain', models.BooleanField(default=False)),
                ('death_country_uncertain', models.BooleanField(default=False)),
                ('death_province', models.CharField(max_length=50, null=True, blank=True)),
                ('death_province_uncertain', models.BooleanField(default=False)),
                ('death_city', models.CharField(max_length=200, null=True, blank=True)),
                ('death_city_uncertain', models.BooleanField(default=False)),
                ('bio', models.TextField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('bio_source', models.ManyToManyField(related_name='cr_biosource', null=True, through='oi.BioSourceRevision', to='gcd.SourceType', blank=True)),
                ('birth_city_source', models.ManyToManyField(related_name='cr_birthcitysource', null=True, through='oi.BirthCitySourceRevision', to='gcd.SourceType', blank=True)),
                ('birth_country', models.ForeignKey(related_name='cr_birth_country', blank=True, to='stddata.Country', null=True)),
                ('birth_country_source', models.ManyToManyField(related_name='cr_birthcountrysource', null=True, through='oi.BirthCountrySourceRevision', to='gcd.SourceType', blank=True)),
                ('birth_date_source', models.ManyToManyField(related_name='cr_birthdatesource', null=True, through='oi.BirthDateSourceRevision', to='gcd.SourceType', blank=True)),
                ('birth_month_source', models.ManyToManyField(related_name='cr_birthmonthsource', null=True, through='oi.BirthMonthSourceRevision', to='gcd.SourceType', blank=True)),
                ('birth_province_source', models.ManyToManyField(related_name='cr_birthprovincesource', null=True, through='oi.BirthProvinceSourceRevision', to='gcd.SourceType', blank=True)),
                ('birth_year_source', models.ManyToManyField(related_name='cr_birthyearsource', null=True, through='oi.BirthYearSourceRevision', to='gcd.SourceType', blank=True)),
                ('changeset', models.ForeignKey(related_name='creatorrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='revisions', to='gcd.Creator', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorSchoolDetailRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('school_year_began', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('school_year_began_uncertain', models.BooleanField(default=False)),
                ('school_year_ended', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('school_year_ended_uncertain', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='creatorschooldetailrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creator_school', to='oi.CreatorRevision')),
                ('creator_school_detail', models.ForeignKey(related_name='cr_creator_school_detail', to='gcd.CreatorSchoolDetail', null=True)),
                ('school', models.ForeignKey(related_name='cr_school_details', to='gcd.School')),
                ('school_source', models.ManyToManyField(related_name='cr_schoolsource', null=True, to='gcd.SourceType', blank=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_school_detail_revision',
                'verbose_name_plural': 'Creator School Detail Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DeathCitySourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='deathcitysourcerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creatordeathcitysource', to='oi.CreatorRevision')),
                ('death_city_source', models.ForeignKey(related_name='cr_death_city_source', to='gcd.DeathCitySource', null=True)),
                ('source_type', models.ForeignKey(related_name='cr_creatordeathcitysourcetype', to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_death_city_source_revision',
                'verbose_name_plural': 'Death City Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DeathCountrySourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='deathcountrysourcerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creatordeathcountrysource', to='oi.CreatorRevision')),
                ('death_country_source', models.ForeignKey(related_name='cr_death_country_source', to='gcd.DeathCountrySource', null=True)),
                ('source_type', models.ForeignKey(related_name='cr_creatordeathcountrysourcetype', to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_death_country_source_revision',
                'verbose_name_plural': 'Death Country Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DeathDateSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='deathdatesourcerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creatordeathdatesource', to='oi.CreatorRevision')),
                ('death_date_source', models.ForeignKey(related_name='cr_death_date_source', to='gcd.DeathDateSource', null=True)),
                ('source_type', models.ForeignKey(related_name='cr_creatordeathdatesourcetype', to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_death_date_source_revision',
                'verbose_name_plural': 'Death Date Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DeathMonthSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='deathmonthsourcerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creatordeathmonthsource', to='oi.CreatorRevision')),
                ('death_month_source', models.ForeignKey(related_name='cr_death_month_source', to='gcd.DeathMonthSource', null=True)),
                ('source_type', models.ForeignKey(related_name='cr_creatordeathmonthsourcetype', to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_death_month_source_revision',
                'verbose_name_plural': 'Death Month Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DeathProvinceSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='deathprovincesourcerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creatordeathprovincesource', to='oi.CreatorRevision')),
                ('death_province_source', models.ForeignKey(related_name='cr_death_province_source', to='gcd.DeathProvinceSource', null=True)),
                ('source_type', models.ForeignKey(related_name='cr_creatordeathprovincesourcetype', to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_death_province_source_revision',
                'verbose_name_plural': 'Death Province Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DeathYearSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='deathyearsourcerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creatordeathyearsource', to='oi.CreatorRevision')),
                ('death_year_source', models.ForeignKey(related_name='cr_death_year_source', to='gcd.DeathYearSource', null=True)),
                ('source_type', models.ForeignKey(related_name='cr_creatordeathyearsourcetype', to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_death_year_source_revision',
                'verbose_name_plural': 'Death Year Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NameRelationRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('changeset', models.ForeignKey(related_name='namerelationrevisions', to='oi.Changeset')),
                ('gcd_official_name', models.ForeignKey(related_name='creator_revise_gcd_official_name', to='oi.CreatorNameDetailsRevision')),
                ('name_relation', models.ForeignKey(related_name='cr_name_relation', to='gcd.NameRelation', null=True)),
                ('rel_source', models.ManyToManyField(to='gcd.SourceType', null=True)),
                ('rel_type', models.ForeignKey(related_name='creator_revise_relation_type', blank=True, to='gcd.RelationType', null=True)),
                ('to_name', models.ForeignKey(related_name='creator_revise_to_name', to='oi.CreatorNameDetailsRevision')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_namerelation_revision',
                'verbose_name_plural': 'Name Relation Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NonComicWorkLinkRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('link', models.URLField(max_length=255)),
                ('changeset', models.ForeignKey(related_name='noncomicworklinkrevisions', to='oi.Changeset')),
                ('creator_noncomicworklink', models.ForeignKey(related_name='revisions', to='gcd.NonComicWorkLink', null=True)),
                ('non_comic_work', models.ForeignKey(related_name='cr_noncomicworklinks', to='oi.CreatorNonComicWorkRevision')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_non_comic_work_link_revision',
                'verbose_name_plural': 'NonComic Work Link Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NonComicWorkYearRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('work_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('work_year_uncertain', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(related_name='noncomicworkyearrevisions', to='oi.Changeset')),
                ('creator_noncomicworkyear', models.ForeignKey(related_name='revisions', to='gcd.NonComicWorkYear', null=True)),
                ('non_comic_work', models.ForeignKey(related_name='cr_noncomicworkyears', to='oi.CreatorNonComicWorkRevision')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_non_comic_work_year_revision',
                'verbose_name_plural': 'NonComic Work Year Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PortraitSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_description', models.TextField(null=True, blank=True)),
                ('changeset', models.ForeignKey(related_name='portraitsourcerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='cr_creatorportraitsource', to='oi.CreatorRevision')),
                ('portrait_source', models.ForeignKey(related_name='cr_portrait_source', to='gcd.PortraitSource', null=True)),
                ('source_type', models.ForeignKey(related_name='cr_creatorportraitsourcetype', to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_portrait_source_revision',
                'verbose_name_plural': 'Portrait Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_city_source',
            field=models.ManyToManyField(related_name='cr_deathcitysource', null=True, through='oi.DeathCitySourceRevision', to='gcd.SourceType', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_country',
            field=models.ForeignKey(related_name='cr_death_country', blank=True, to='stddata.Country', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_country_source',
            field=models.ManyToManyField(related_name='cr_deathcountrysource', null=True, through='oi.DeathCountrySourceRevision', to='gcd.SourceType', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_date_source',
            field=models.ManyToManyField(related_name='cr_deathdatesource', null=True, through='oi.DeathDateSourceRevision', to='gcd.SourceType', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_month_source',
            field=models.ManyToManyField(related_name='cr_deathmonthsource', null=True, through='oi.DeathMonthSourceRevision', to='gcd.SourceType', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_province_source',
            field=models.ManyToManyField(related_name='cr_deathprovincesource', null=True, through='oi.DeathProvinceSourceRevision', to='gcd.SourceType', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_year_source',
            field=models.ManyToManyField(related_name='cr_deathyearsource', null=True, through='oi.DeathYearSourceRevision', to='gcd.SourceType', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='degrees',
            field=models.ManyToManyField(related_name='cr_degreeinformation', null=True, through='oi.CreatorDegreeDetailRevision', to='gcd.Degree', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='portrait_source',
            field=models.ManyToManyField(related_name='cr_portraitsource', null=True, through='oi.PortraitSourceRevision', to='gcd.SourceType', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='schools',
            field=models.ManyToManyField(related_name='cr_schoolinformation', null=True, through='oi.CreatorSchoolDetailRevision', to='gcd.School', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailsrevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creator_names', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailsrevision',
            name='creator_name_detail',
            field=models.ForeignKey(related_name='cr_creator_name_details', to='gcd.CreatorNameDetails', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailsrevision',
            name='source',
            field=models.ManyToManyField(related_name='cr_namesources', null=True, to='gcd.SourceType', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailsrevision',
            name='type',
            field=models.ForeignKey(related_name='cr_nametypes', blank=True, to='gcd.NameType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatordegreedetailrevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creator_degree', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatordegreedetailrevision',
            name='degree',
            field=models.ForeignKey(related_name='cr_degreedetails', to='gcd.Degree'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatordegreedetailrevision',
            name='school',
            field=models.ForeignKey(related_name='cr_schooldetails', to='gcd.School', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthyearsourcerevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creatorbirthyearsource', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthyearsourcerevision',
            name='source_type',
            field=models.ForeignKey(related_name='cr_creatorbirthyearsourcetype', to='gcd.SourceType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthprovincesourcerevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creatorbirthprovincesource', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthprovincesourcerevision',
            name='source_type',
            field=models.ForeignKey(related_name='cr_creatorbirthprovincesourcetype', to='gcd.SourceType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthmonthsourcerevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creatorbirthmonthsource', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthmonthsourcerevision',
            name='source_type',
            field=models.ForeignKey(related_name='cr_creatorbirthmonthsourcetype', to='gcd.SourceType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthdatesourcerevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creatorbirthdatesource', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthdatesourcerevision',
            name='source_type',
            field=models.ForeignKey(related_name='cr_creatorbirthdatesourcetype', to='gcd.SourceType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthcountrysourcerevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creatorbirthcountrysource', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthcountrysourcerevision',
            name='source_type',
            field=models.ForeignKey(related_name='cr_creatorbirthcountrysourcetype', to='gcd.SourceType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthcitysourcerevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creatorbirthcitysource', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='birthcitysourcerevision',
            name='source_type',
            field=models.ForeignKey(related_name='cr_creatorbirthcitysourcetype', to='gcd.SourceType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosourcerevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creatorbiosource', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosourcerevision',
            name='source_type',
            field=models.ForeignKey(related_name='cr_creatorbiosourcetype', to='gcd.SourceType'),
            preserve_default=True,
        ),
        migrations.AlterModelOptions(
            name='imagerevision',
            options={'ordering': ['created', '-id']},
        ),
    ]
