# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0006_DataSource'),
        ('contenttypes', '0001_initial'),
        ('oi', '0003_CreatorNameDetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorDataSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('revision_id', models.IntegerField(null=True, db_index=True)),
                ('source_description', models.TextField()),
                ('field', models.CharField(max_length=256)),
                ('changeset', models.ForeignKey(related_name='creatordatasourcerevisions', to='oi.Changeset')),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType', null=True)),
                ('creator_data_source', models.ForeignKey(related_name='revisions', to='gcd.CreatorDataSource', null=True)),
                ('source_type', models.ForeignKey(to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_data_source_revision',
                'verbose_name_plural': 'Creator Data Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.RemoveField(
            model_name='biosourcerevision',
            name='bio_source',
        ),
        migrations.RemoveField(
            model_name='biosourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='biosourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='biosourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='birthcitysourcerevision',
            name='birth_city_source',
        ),
        migrations.RemoveField(
            model_name='birthcitysourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='birthcitysourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='birthcitysourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='birthcountrysourcerevision',
            name='birth_country_source',
        ),
        migrations.RemoveField(
            model_name='birthcountrysourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='birthcountrysourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='birthcountrysourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='birthdatesourcerevision',
            name='birth_date_source',
        ),
        migrations.RemoveField(
            model_name='birthdatesourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='birthdatesourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='birthdatesourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='birthmonthsourcerevision',
            name='birth_month_source',
        ),
        migrations.RemoveField(
            model_name='birthmonthsourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='birthmonthsourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='birthmonthsourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='birthprovincesourcerevision',
            name='birth_province_source',
        ),
        migrations.RemoveField(
            model_name='birthprovincesourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='birthprovincesourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='birthprovincesourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='birthyearsourcerevision',
            name='birth_year_source',
        ),
        migrations.RemoveField(
            model_name='birthyearsourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='birthyearsourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='birthyearsourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='deathcitysourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='deathcitysourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='deathcitysourcerevision',
            name='death_city_source',
        ),
        migrations.RemoveField(
            model_name='deathcitysourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='deathcountrysourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='deathcountrysourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='deathcountrysourcerevision',
            name='death_country_source',
        ),
        migrations.RemoveField(
            model_name='deathcountrysourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='deathdatesourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='deathdatesourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='deathdatesourcerevision',
            name='death_date_source',
        ),
        migrations.RemoveField(
            model_name='deathdatesourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='deathmonthsourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='deathmonthsourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='deathmonthsourcerevision',
            name='death_month_source',
        ),
        migrations.RemoveField(
            model_name='deathmonthsourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='deathprovincesourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='deathprovincesourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='deathprovincesourcerevision',
            name='death_province_source',
        ),
        migrations.RemoveField(
            model_name='deathprovincesourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='deathyearsourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='deathyearsourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='deathyearsourcerevision',
            name='death_year_source',
        ),
        migrations.RemoveField(
            model_name='deathyearsourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='portraitsourcerevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='portraitsourcerevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='portraitsourcerevision',
            name='portrait_source',
        ),
        migrations.RemoveField(
            model_name='portraitsourcerevision',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='creatornamedetailrevision',
            name='source',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='bio_source',
        ),
        migrations.DeleteModel(
            name='BioSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='birth_city_source',
        ),
        migrations.DeleteModel(
            name='BirthCitySourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='birth_country_source',
        ),
        migrations.DeleteModel(
            name='BirthCountrySourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='birth_date_source',
        ),
        migrations.DeleteModel(
            name='BirthDateSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='birth_month_source',
        ),
        migrations.DeleteModel(
            name='BirthMonthSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='birth_province_source',
        ),
        migrations.DeleteModel(
            name='BirthProvinceSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='birth_year_source',
        ),
        migrations.DeleteModel(
            name='BirthYearSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='death_city_source',
        ),
        migrations.DeleteModel(
            name='DeathCitySourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='death_country_source',
        ),
        migrations.DeleteModel(
            name='DeathCountrySourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='death_date_source',
        ),
        migrations.DeleteModel(
            name='DeathDateSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='death_month_source',
        ),
        migrations.DeleteModel(
            name='DeathMonthSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='death_province_source',
        ),
        migrations.DeleteModel(
            name='DeathProvinceSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='death_year_source',
        ),
        migrations.DeleteModel(
            name='DeathYearSourceRevision',
        ),
        migrations.RemoveField(
            model_name='creatorrevision',
            name='portrait_source',
        ),
        migrations.DeleteModel(
            name='PortraitSourceRevision',
        ),
        migrations.RemoveField(
            model_name='namerelationrevision',
            name='rel_source',
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='data_source',
            field=models.ManyToManyField(to='oi.CreatorDataSourceRevision', null=True, blank=True),
            preserve_default=True,
        ),
    ]
