# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0003_populate_previous_committed'),
        ('gcd', '0008_consolidate_reprints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reprintrevision',
            old_name='origin_story',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='reprintrevision',
            old_name='target_story',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='reprintrevision',
            name='in_type',
        ),
        migrations.RemoveField(
            model_name='reprintrevision',
            name='issue_reprint',
        ),
        migrations.RemoveField(
            model_name='reprintrevision',
            name='out_type',
        ),
        migrations.RemoveField(
            model_name='reprintrevision',
            name='reprint_from_issue',
        ),
        migrations.RemoveField(
            model_name='reprintrevision',
            name='reprint_to_issue',
        ),
    ]
