# -*- coding: utf-8 -*-


from django.db import models, migrations
import apps.oi.models


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0002_initial_data'),
        ('gcd', '0003_creators'),
        ('contenttypes', '0001_initial'),
        ('oi', '0003_migrate_reservations_to_locks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorArtInfluenceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('influence_name', models.CharField(max_length=200, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatorartinfluencerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='art_influence_revisions', to='gcd.Creator')),
                ('creator_art_influence', models.ForeignKey(related_name='revisions', to='gcd.CreatorArtInfluence', null=True)),
                ('influence_link', models.ForeignKey(related_name='influenced_revisions', blank=True, to='gcd.Creator', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_art_influence_revision',
                'verbose_name_plural': 'Creator Art Influence Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorAwardRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('award_name', models.CharField(max_length=255, blank=True)),
                ('no_award_name', models.BooleanField(default=False)),
                ('award_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('award_year_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('award', models.ForeignKey(blank=True, to='gcd.Award', null=True)),
                ('changeset', models.ForeignKey(related_name='creatorawardrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='award_revisions', to='gcd.Creator')),
                ('creator_award', models.ForeignKey(related_name='revisions', to='gcd.CreatorAward', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_award_revision',
                'verbose_name_plural': 'Creator Award Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorDegreeRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('degree_year', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('degree_year_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatordegreerevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='degree_revisions', to='gcd.Creator')),
                ('creator_degree', models.ForeignKey(related_name='revisions', to='gcd.CreatorDegree', null=True)),
                ('degree', models.ForeignKey(related_name='creator_degrees', to='gcd.Degree')),
                ('school', models.ForeignKey(related_name='creator_degrees', to='gcd.School', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_degree_revision',
                'verbose_name_plural': 'Creator Degree Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorMembershipRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('membership_year_began', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('membership_year_began_uncertain', models.BooleanField(default=False)),
                ('membership_year_ended', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('membership_year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatormembershiprevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='membership_revisions', to='gcd.Creator')),
                ('creator_membership', models.ForeignKey(related_name='revisions', to='gcd.CreatorMembership', null=True)),
                ('membership_type', models.ForeignKey(related_name='cr_membershiptype', blank=True, to='gcd.MembershipType', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_membership_revision',
                'verbose_name_plural': 'Creator Membership Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorNameDetailRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('changeset', models.ForeignKey(related_name='creatornamedetailrevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['type__id', 'created', '-id'],
                'db_table': 'oi_creator_name_detail_revision',
                'verbose_name_plural': 'Creator Name Detail Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorNonComicWorkRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('publication_title', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=200, blank=True)),
                ('work_title', models.CharField(max_length=255, blank=True)),
                ('work_years', models.TextField(blank=True)),
                ('work_urls', models.TextField(blank=True, validators=[apps.oi.models.MultiURLValidator()])),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatornoncomicworkrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='non_comic_work_revisions', to='gcd.Creator')),
                ('creator_non_comic_work', models.ForeignKey(related_name='revisions', to='gcd.CreatorNonComicWork', null=True)),
                ('work_role', models.ForeignKey(related_name='cr_workrole', blank=True, to='gcd.NonComicWorkRole', null=True)),
                ('work_type', models.ForeignKey(related_name='cr_worktype', blank=True, to='gcd.NonComicWorkType', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_non_comic_work_revision',
                'verbose_name_plural': 'Creator NonComicWork Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorRelationRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatorrelationrevisions', to='oi.Changeset')),
                ('creator_relation', models.ForeignKey(related_name='revisions', to='gcd.CreatorRelation', null=True)),
                ('from_creator', models.ForeignKey(related_name='from_creator_revisions', to='gcd.Creator')),
                ('relation_type', models.ForeignKey(related_name='revisions', to='gcd.RelationType')),
                ('to_creator', models.ForeignKey(related_name='to_creator_revisions', to='gcd.Creator')),
            ],
            options={
                'ordering': ('to_creator', 'relation_type', 'from_creator'),
                'db_table': 'oi_creator_relation_revision',
                'verbose_name_plural': 'Name Relation Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('gcd_official_name', models.CharField(max_length=255, db_index=True)),
                ('birth_country_uncertain', models.BooleanField(default=False)),
                ('birth_province', models.CharField(max_length=50, blank=True)),
                ('birth_province_uncertain', models.BooleanField(default=False)),
                ('birth_city', models.CharField(max_length=200, blank=True)),
                ('birth_city_uncertain', models.BooleanField(default=False)),
                ('death_country_uncertain', models.BooleanField(default=False)),
                ('death_province', models.CharField(max_length=50, blank=True)),
                ('death_province_uncertain', models.BooleanField(default=False)),
                ('death_city', models.CharField(max_length=200, blank=True)),
                ('death_city_uncertain', models.BooleanField(default=False)),
                ('whos_who', models.URLField(null=True, blank=True)),
                ('bio', models.TextField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('birth_country', models.ForeignKey(related_name='cr_birth_country', blank=True, to='stddata.Country', null=True)),
                ('birth_date', models.ForeignKey(related_name='+', blank=True, to='stddata.Date', null=True)),
                ('changeset', models.ForeignKey(related_name='creatorrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='revisions', to='gcd.Creator', null=True)),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_revision',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CreatorSchoolRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('school_year_began', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('school_year_began_uncertain', models.BooleanField(default=False)),
                ('school_year_ended', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('school_year_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(related_name='creatorschoolrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(related_name='school_revisions', to='gcd.Creator')),
                ('creator_school', models.ForeignKey(related_name='revisions', to='gcd.CreatorSchool', null=True)),
                ('school', models.ForeignKey(related_name='cr_schools', to='gcd.School')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_creator_school_revision',
                'verbose_name_plural': 'Creator School Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DataSourceRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('revision_id', models.IntegerField(null=True, db_index=True)),
                ('source_description', models.TextField()),
                ('field', models.CharField(max_length=256)),
                ('changeset', models.ForeignKey(related_name='datasourcerevisions', to='oi.Changeset')),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType', null=True)),
                ('data_source', models.ForeignKey(related_name='revisions', to='gcd.DataSource', null=True)),
                ('source_type', models.ForeignKey(to='gcd.SourceType')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_data_source_revision',
                'verbose_name_plural': 'Data Source Revisions',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='data_source',
            field=models.ManyToManyField(to='oi.DataSourceRevision', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_country',
            field=models.ForeignKey(related_name='cr_death_country', blank=True, to='stddata.Country', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='death_date',
            field=models.ForeignKey(related_name='+', blank=True, to='stddata.Date', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='creator',
            field=models.ForeignKey(related_name='cr_creator_names', to='oi.CreatorRevision'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='creator_name_detail',
            field=models.ForeignKey(related_name='revisions', to='gcd.CreatorNameDetail', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='type',
            field=models.ForeignKey(related_name='cr_nametypes', blank=True, to='gcd.NameType', null=True),
            preserve_default=True,
        ),
        migrations.AlterModelOptions(
            name='imagerevision',
            options={'ordering': ['created', '-id']},
        ),
    ]
