# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0006_award_editable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatorrelationrevision',
            options={'ordering': ('to_creator', 'relation_type', 'from_creator'), 'verbose_name_plural': 'Creator Relation Revisions'},
        ),
        migrations.AddField(
            model_name='awardrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='awardrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.AwardRevision'),
        ),
        migrations.AddField(
            model_name='brandgrouprevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='brandgrouprevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.BrandGroupRevision'),
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.BrandRevision'),
        ),
        migrations.AddField(
            model_name='branduserevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='branduserevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.BrandUseRevision'),
        ),
        migrations.AddField(
            model_name='coverrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='coverrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CoverRevision'),
        ),
        migrations.AddField(
            model_name='creatorartinfluencerevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatorartinfluencerevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorArtInfluenceRevision'),
        ),
        migrations.AddField(
            model_name='creatorawardrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatorawardrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorAwardRevision'),
        ),
        migrations.AddField(
            model_name='creatordegreerevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatordegreerevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorDegreeRevision'),
        ),
        migrations.AddField(
            model_name='creatormembershiprevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatormembershiprevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorMembershipRevision'),
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorNameDetailRevision'),
        ),
        migrations.AddField(
            model_name='creatornoncomicworkrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatornoncomicworkrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorNonComicWorkRevision'),
        ),
        migrations.AddField(
            model_name='creatorrelationrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatorrelationrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorRelationRevision'),
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatorrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorRevision'),
        ),
        migrations.AddField(
            model_name='creatorschoolrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='creatorschoolrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.CreatorSchoolRevision'),
        ),
        migrations.AddField(
            model_name='datasourcerevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='datasourcerevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.DataSourceRevision'),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='imagerevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.ImageRevision'),
        ),
        migrations.AddField(
            model_name='indiciapublisherrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='indiciapublisherrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.IndiciaPublisherRevision'),
        ),
        migrations.AddField(
            model_name='issuerevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='issuerevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.IssueRevision'),
        ),
        migrations.AddField(
            model_name='publisherrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='publisherrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.PublisherRevision'),
        ),
        migrations.AddField(
            model_name='reprintrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='seriesbondrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='seriesrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='seriesrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.SeriesRevision'),
        ),
        migrations.AddField(
            model_name='storyrevision',
            name='committed',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='storyrevision',
            name='previous_revision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.StoryRevision'),
        ),
    ]
