# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0006_award_editable'),
        ('oi', '0005_issuerevision_volume_not_printed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('award', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.Award')),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardrevisions', to='oi.Changeset')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_award_revision',
                'verbose_name_plural': 'Award Revisions',
            },
        ),
        migrations.AlterModelOptions(
            name='creatorrelationrevision',
            options={'ordering': ('to_creator', 'relation_type', 'from_creator'), 'verbose_name_plural': 'Creator Relation Revisions'},
        ),
    ]
