# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-27 11:34


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0011_add_sort_name_to_creatornamedetail'),
        ('oi', '0011_reorg_creatornamedetailrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_revisions', to='gcd.Creator'),
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='sort_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='creatornamedetailrevision',
            name='creator_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cr_creator_names', to='oi.CreatorRevision'),
        ),
    ]
