# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 14:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0013_receivedaward'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('oi', '0013_add_bibliography'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedAwardRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('award_name', models.CharField(blank=True, max_length=255)),
                ('no_award_name', models.BooleanField(default=False)),
                ('award_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('award_year_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcd.Award')),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedawardrevisions', to='oi.Changeset')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.ReceivedAwardRevision')),
                ('received_award', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.ReceivedAward')),
            ],
            options={
                'ordering': ['created', '-id'],
                'db_table': 'oi_received_award_revision',
                'verbose_name_plural': 'Received Award Revisions',
            },
        ),
    ]
