# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 18:44
from __future__ import unicode_literals

from django.db import migrations

def migrate_awards(apps, schema_editor):
    """
    Data migration to populate the ReceivedAward from CreatorAward.
    """
    # We can't import the model directly as it may be a newer
    # version than this migration expects.
    CreatorAwardRevision = apps.get_model('oi', 'CreatorAwardRevision')
    ReceivedAwardRevision = apps.get_model('oi', 'ReceivedAwardRevision')
    ContentType = apps.get_model('contenttypes', 'ContentType')
 
    creator_content_type = ContentType.objects.get(app_label='gcd',
                                                   model='creator')
 
    for creator_award in CreatorAwardRevision.objects.all():
        received_award = ReceivedAwardRevision(id=creator_award.id)
        received_award.received_award_id = creator_award.creator_award_id
        received_award.changeset_id = creator_award.changeset_id
        received_award.deleted = creator_award.deleted
        received_award.committed = creator_award.committed
        received_award.previous_revision_id = creator_award.previous_revision_id

        received_award.content_type_id = creator_content_type.id
        received_award.object_id = creator_award.creator_id
        received_award.award_id = creator_award.award_id
        received_award.award_name = creator_award.award_name
        received_award.no_award_name = creator_award.no_award_name
        received_award.award_year = creator_award.award_year
        received_award.award_year_uncertain = creator_award.award_year_uncertain
        received_award.notes = creator_award.notes

        received_award.save()

        # delete after/during changeset / revisions migration, not here
        #super(CreatorAward, creator_award).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0014_receivedawardrevision'),
    ]

    operations = [
        migrations.RunPython(migrate_awards),
    ]
