# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-30 09:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0015_cleanup_award_migration'),
        ('oi', '0014_receivedawardrevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorawardrevision',
            name='award',
        ),
        migrations.RemoveField(
            model_name='creatorawardrevision',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='creatorawardrevision',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='creatorawardrevision',
            name='creator_award',
        ),
        migrations.RemoveField(
            model_name='creatorawardrevision',
            name='previous_revision',
        ),
        migrations.DeleteModel(
            name='PreviewCreatorAward',
        ),
        migrations.CreateModel(
            name='PreviewReceivedAward',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('gcd.receivedaward',),
        ),
        migrations.DeleteModel(
            name='CreatorAwardRevision',
        ),
    ]
