# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-15 08:57


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0018_add_feature_relation'),
        ('oi', '0017_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRelationRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featurerelationrevisions', to='oi.Changeset')),
                ('feature_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.FeatureRelation')),
                ('from_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_feature_revisions', to='gcd.Feature')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.FeatureRelationRevision')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.FeatureRelationType')),
                ('to_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_feature_revisions', to='gcd.Feature')),
            ],
            options={
                'ordering': ('to_feature', 'relation_type', 'from_feature'),
                'db_table': 'oi_feature_relation_revision',
                'verbose_name_plural': 'Feature Relation Revisions',
            },
        ),
    ]
