# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 08:52


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0019_creator_story_credit'),
        ('oi', '0018_add_feature_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCreditRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_credited', models.BooleanField(db_index=True, default=False)),
                ('is_signed', models.BooleanField(db_index=True, default=False)),
                ('uncertain', models.BooleanField(db_index=True, default=False)),
                ('signed_as', models.CharField(max_length=255, blank=True)),
                ('credited_as', models.CharField(max_length=255, blank=True)),
                ('credit_name', models.CharField(max_length=255, blank=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storycreditrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CreatorNameDetail')),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CreditType')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.StoryCreditRevision')),
                ('story_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_credit_revisions', to='oi.StoryRevision')),
                ('story_credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.StoryCredit')),
            ],
            options={
                'ordering': ['credit_type__sort_code', 'id'],
                'db_table': 'oi_story_credit_revision',
            },
        ),
    ]
