# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-14 06:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0020_add_name_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatornamedetailrevision',
            options={'ordering': ['-is_official_name', 'type__id', 'created', '-id'], 'verbose_name_plural': 'Creator Name Detail Revisions'},
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='family_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creatornamedetailrevision',
            name='given_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
