# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-14 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0022_relation_creator_name'),
        ('oi', '0021_given_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorrelationrevision',
            name='creator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_relation_revisions', to='gcd.CreatorNameDetail'),
        ),
    ]
