# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0026_creator_issue_credit'),
        ('oi', '0024_use_feature_in_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCreditRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_credited', models.BooleanField(db_index=True, default=False)),
                ('uncertain', models.BooleanField(db_index=True, default=False)),
                ('credited_as', models.CharField(blank=True, max_length=255)),
                ('credit_name', models.CharField(blank=True, max_length=255)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuecreditrevisions', to='oi.Changeset')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CreatorNameDetail')),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CreditType')),
                ('issue_credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.IssueCredit')),
                ('issue_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_credit_revisions', to='oi.IssueRevision')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.IssueCreditRevision')),
            ],
            options={
                'db_table': 'oi_issue_credit_revision',
                'ordering': ['credit_type__sort_code', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='creatornamedetailrevision',
            name='sort_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='creatornamedetailrevision',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_name_details', to='gcd.NameType'),
        ),
    ]
