# Generated by Django 2.2.10 on 2020-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0025_creator_issue_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatornamedetailrevision',
            options={'ordering': ['sort_name', '-creator__birth_date__year', 'type__id'], 'verbose_name_plural': 'Creator Name Detail Revisions'},
        ),
        migrations.AddField(
            model_name='brandgrouprevision',
            name='year_overall_began',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandgrouprevision',
            name='year_overall_began_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandgrouprevision',
            name='year_overall_ended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandgrouprevision',
            name='year_overall_ended_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='year_overall_began',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='year_overall_began_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='year_overall_ended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandrevision',
            name='year_overall_ended_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indiciapublisherrevision',
            name='year_overall_began',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indiciapublisherrevision',
            name='year_overall_began_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indiciapublisherrevision',
            name='year_overall_ended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indiciapublisherrevision',
            name='year_overall_ended_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisherrevision',
            name='year_overall_began',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherrevision',
            name='year_overall_began_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisherrevision',
            name='year_overall_ended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherrevision',
            name='year_overall_ended_uncertain',
            field=models.BooleanField(default=False),
        ),
    ]
