# Generated by Django 2.2.10 on 2020-05-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0003_script'),
        ('gcd', '0028_add_printer'),
        ('oi', '0026_add_publisher_second_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('year_began', models.IntegerField(blank=True, null=True)),
                ('year_ended', models.IntegerField(blank=True, null=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('year_overall_began', models.IntegerField(blank=True, null=True)),
                ('year_overall_ended', models.IntegerField(blank=True, null=True)),
                ('year_overall_began_uncertain', models.BooleanField(default=False)),
                ('year_overall_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printerrevisions', to='oi.Changeset')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stddata.Country')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.PrinterRevision')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.Printer')),
            ],
            options={
                'db_table': 'oi_printer_revision',
                'ordering': ['-created', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IndiciaPrinterRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('year_began', models.IntegerField(blank=True, null=True)),
                ('year_ended', models.IntegerField(blank=True, null=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('year_overall_began', models.IntegerField(blank=True, null=True)),
                ('year_overall_ended', models.IntegerField(blank=True, null=True)),
                ('year_overall_began_uncertain', models.BooleanField(default=False)),
                ('year_overall_ended_uncertain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indiciaprinterrevisions', to='oi.Changeset')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicia_printers_revisions', to='stddata.Country')),
                ('indicia_printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.IndiciaPrinter')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicia_printer_revisions', to='gcd.Printer')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.IndiciaPrinterRevision')),
            ],
            options={
                'db_table': 'oi_indicia_printer_revision',
                'ordering': ['-created', '-id'],
            },
        ),
    ]
