# Generated by Django 2.2.12 on 2020-06-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0031_storycredit_signature'),
        ('oi', '0029_indicia_printer_per_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycreditrevision',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcd.CreatorSignature'),
        ),
    ]
