# Generated by Django 2.2.12 on 2020-11-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0030_storycreditrevision_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatornoncomicworkrevision',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_worktype', to='gcd.NonComicWorkType'),
        ),
    ]
