# Generated by Django 2.2.12 on 2021-01-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0034_publisher_code_number'),
        ('oi', '0032_add_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherCodeNumberRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishercodenumberrevisions', to='oi.Changeset')),
                ('issue_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_code_number_revisions', to='oi.IssueRevision')),
                ('number_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CodeNumberType')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.PublisherCodeNumberRevision')),
                ('publisher_code_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.PublisherCodeNumber')),
            ],
            options={
                'db_table': 'oi_issue_code_number_revision',
            },
        ),
    ]
