# Generated by Django 2.2.12 on 2020-12-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0034_grouprelation_grouprelationtype'),
        ('oi', '0032_add_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRelationRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouprelationrevisions', to='oi.Changeset')),
                ('from_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_group_revisions', to='gcd.Group')),
                ('group_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.GroupRelation')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.GroupRelationRevision')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.GroupRelationType')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_group_revisions', to='gcd.Group')),
            ],
            options={
                'verbose_name_plural': 'Group Relation Revisions',
                'db_table': 'oi_group_relation_revision',
                'ordering': ('to_group', 'relation_type', 'from_group'),
            },
        ),
    ]
