# Generated by Django 2.2.20 on 2021-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0037_character_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycreditrevision',
            name='is_sourced',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='storycreditrevision',
            name='sourced_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='issuecreditrevision',
            name='is_sourced',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='issuecreditrevision',
            name='sourced_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
