# Generated by Django 3.2.11 on 2022-08-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0044_universe'),
        ('oi', '0040_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewCharacter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gcd.character',),
        ),
        migrations.CreateModel(
            name='PreviewUniverse',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gcd.universe',),
        ),
        migrations.CreateModel(
            name='UniverseRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.NullBooleanField(db_index=True, default=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('multiverse', models.CharField(blank=True, db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('designation', models.CharField(blank=True, db_index=True, max_length=255)),
                ('year_first_published', models.IntegerField(blank=True, db_index=True, null=True)),
                ('year_first_published_uncertain', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universerevisions', to='oi.changeset')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.universerevision')),
                ('universe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.universe')),
            ],
            options={
                'db_table': 'oi_universe_revision',
                'ordering': ['created', '-id'],
            },
        ),
    ]
