# Generated by Django 3.2.19 on 2023-05-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0043_issuerevision_variant_cover_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerevision',
            name='disambiguation',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issuerevision',
            name='variant_cover_status',
            field=models.IntegerField(choices=[(1, 'No Difference'), (2, 'Only Scan Difference'), (3, 'Artwork Difference')], db_index=True, default=1),
        ),
    ]
