# Generated by Django 3.2.19 on 2023-09-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0048_universe_story'),
        ('oi', '0045_minor_variant_cover_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycharacterrevision',
            name='universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcd.universe'),
        ),
        migrations.AddField(
            model_name='storyrevision',
            name='universe',
            field=models.ManyToManyField(blank=True, to='gcd.Universe'),
        ),
    ]
