# Generated by Django 4.2.11 on 2024-07-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oi', '0052_use_group_name_in_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storygrouprevision',
            options={'ordering': ['group_name__sort_name']},
        ),
        migrations.AlterField(
            model_name='awardrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='brandgrouprevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='brandrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='branduserevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='characternamedetailrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='characterrelationrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='characterrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='coverrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatorartinfluencerevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatordegreerevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatormembershiprevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatornamedetailrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatornoncomicworkrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatorrelationrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatorrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatorschoolrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='creatorsignaturerevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='datasourcerevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='externallinkrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='featurelogorevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='featurerelationrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='featurerevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='groupmembershiprevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='groupnamedetailrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='grouprelationrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='grouprevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='imagerevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='indiciaprinterrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='indiciapublisherrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='issuecreditrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='issuerevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='printerrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='publishercodenumberrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='publisherrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='receivedawardrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='reprintrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='seriesbondrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='seriesrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='storycharacterrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='storycreditrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='storygrouprevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='storyrevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
        migrations.AlterField(
            model_name='universerevision',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset'),
        ),
    ]
