# Generated by Django 4.2.11 on 2024-07-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0053_alter_related_names_from_changeset'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelogorevision',
            name='image_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_logo_revisions', to='oi.imagerevision'),
        ),
    ]
