# Generated by Django 4.2.11 on 2024-08-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0054_featurelogorevision_image_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandrevision',
            name='image_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_emblem_revisions', to='oi.imagerevision'),
        ),
    ]
