# Generated by Django 4.2.20 on 2025-09-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0062_add_story_arc'),
        ('stddata', '0003_script'),
        ('oi', '0056_rename_year_created_featurerevision_year_first_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyrevision',
            name='story_arc',
            field=models.ManyToManyField(blank=True, to='gcd.storyarc'),
        ),
        migrations.CreateModel(
            name='StoryArcRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.BooleanField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('leading_article', models.BooleanField(default=False)),
                ('disambiguation', models.CharField(blank=True, db_index=True, default='', help_text='If needed a short phrase for the disambiguation of story arcs with a similar or identical name.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stddata.language')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.storyarcrevision')),
                ('story_arc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.storyarc')),
            ],
            options={
                'db_table': 'oi_story_arc_revision',
                'ordering': ['-created', '-id'],
            },
        ),
    ]
