# Generated by Django 4.2.20 on 2025-09-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0057_add_story_arc'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyarcrevision',
            name='year_first_published',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='storyarcrevision',
            name='year_first_published_uncertain',
            field=models.BooleanField(default=False),
        ),
    ]
