# Generated by Django 4.2.20 on 2025-09-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0064_add_story_arc_relation'),
        ('oi', '0058_add_year_to_story_arc'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryArcRelationRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.BooleanField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset')),
                ('from_story_arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_story_arc_revisions', to='gcd.storyarc')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.storyarcrelationrevision')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.storyarcrelationtype')),
                ('story_arc_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.storyarcrelation')),
                ('to_story_arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_story_arc_revisions', to='gcd.storyarc')),
            ],
            options={
                'verbose_name_plural': 'Story Arc Relation Revisions',
                'db_table': 'oi_story_arc_relation_revision',
                'ordering': ('to_story_arc', 'relation_type', 'from_story_arc'),
            },
        ),
    ]
