# Generated by Django 4.2.20 on 2025-10-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0065_brand_emblem_m2m'),
        ('oi', '0059_add_story_arc_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerevision',
            name='brand_emblem',
            field=models.ManyToManyField(blank=True, related_name='issue_revisions', to='gcd.brand'),
        ),
        migrations.AlterField(
            model_name='issuerevision',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_revisions_deprecated', to='gcd.brand'),
        ),
    ]
