# Generated by Django 4.2.20 on 2025-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0060_brand_emblem_m2m'),
        ('gcd', '0066_indicia_printer_not_printed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuerevision',
            old_name='no_indicia_printer',
            new_name='indicia_printer_not_printed',
        ),
        migrations.AddField(
            model_name='issuerevision',
            name='indicia_printer_sourced_by',
            field=models.CharField(blank=True, max_length=255),
            preserve_default=False,
        ),
    ]
