# Generated by Django 5.2.9 on 2026-01-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0067_add_character_order'),
        ('oi', '0061_indicia_printer_not_printed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterOrderRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.BooleanField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset')),
                ('character_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.characterorder')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.characterorderrevision')),
                ('story_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_order_revisions', to='oi.storyrevision')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.characterordertype')),
            ],
            options={
                'db_table': 'oi_character_order_revision',
            },
        ),
        migrations.CreateModel(
            name='CharacterThroughOrderRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField(db_index=True, default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oi.characterorderrevision')),
                ('story_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oi.storycharacterrevision')),
            ],
            options={
                'db_table': 'oi_character_through_order',
                'ordering': ['order_code'],
            },
        ),
        migrations.AddField(
            model_name='characterorderrevision',
            name='character_revisions',
            field=models.ManyToManyField(through='oi.CharacterThroughOrderRevision', to='oi.storycharacterrevision'),
        ),
    ]
