# Generated by Django 5.2.10 on 2026-06-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0068_remove_issue_brand_from_db_add_multiple_feature_names'),
        ('oi', '0062_add_character_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewFeature',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gcd.feature',),
        ),
        migrations.RemoveField(
            model_name='issuerevision',
            name='brand',
        ),
        migrations.CreateModel(
            name='FeatureNameDetailRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('committed', models.BooleanField(db_index=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('leading_article', models.BooleanField(default=False)),
                ('is_official_name', models.BooleanField(default=False)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='oi.changeset')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_revisions', to='gcd.feature')),
                ('feature_name_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='gcd.featurenamedetail')),
                ('feature_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_name_revisions', to='oi.featurerevision')),
                ('previous_revision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_revision', to='oi.featurenamedetailrevision')),
            ],
            options={
                'verbose_name_plural': 'Feature Name Detail Revisions',
                'db_table': 'oi_feature_name_detail_revision',
                'ordering': ['-created', '-id'],
            },
        ),
    ]
