# Generated by Django 5.2.10 on 2026-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0070_feature_logo_2_feature_name'),
        ('oi', '0064_add_feature_names_to_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelogorevision',
            name='feature_name',
            field=models.ManyToManyField(related_name='logo_revisions', to='gcd.featurenamedetail'),
        ),
    ]
