# Generated by Django 5.2.16 on 2026-08-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0065_feature_logo_2_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerevision',
            name='description',
            field=models.TextField(blank=True, help_text='concise description, including background and premise'),
        ),
    ]
