# Generated by Django 5.2.17 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oi', '0066_featurerevision_description'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'ALTER TABLE `oi_changeset_comment` '
                'ALGORITHM=INPLACE, LOCK=NONE, '
                'MODIFY `text` longtext CHARACTER SET utf8mb4 '
                'COLLATE utf8mb4_unicode_ci NOT NULL'
            ),
            reverse_sql=None,
            state_operations=[
                migrations.AlterField(
                    model_name='changesetcomment',
                    name='text',
                    field=models.TextField(
                        db_collation='utf8mb4_unicode_ci',
                    ),
                ),
            ],
        ),
    ]
