# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 05:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
