# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-05 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycomics', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='digital_used',
            field=models.BooleanField(default=False, verbose_name=b'track digitial versions'),
        ),
        migrations.AddField(
            model_name='collection',
            name='rating_used',
            field=models.BooleanField(default=False, verbose_name=b'rate comics'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, b'Poor'), (2, b'Fair'), (3, b'Good'), (4, b'Very Good'), (5, b'Excellent')], null=True),
        ),
    ]
