# Generated by Django 4.2.20 on 2025-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycomics', '0006_NullBooleanField_is_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='for_sale_default',
            field=models.BooleanField(default=False, verbose_name='default for sale status when adding items to this collection'),
        ),
    ]
