# Generated by Django 4.2.20 on 2025-05-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycomics', '0007_collection_for_sale_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='location_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mycomics.location', verbose_name='default location when adding items to this collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='purchase_location_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mycomics.purchaselocation', verbose_name='default purchase location when adding items to this collection'),
        ),
    ]
