# Generated by Django 4.2.20 on 2025-09-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0062_add_story_arc'),
        ('mycomics', '0008_collection_location_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=False, verbose_name='reading order is public and can be viewed by all')),
                ('was_read_used', models.BooleanField(default=False, verbose_name='show read status')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_orders', to='mycomics.collector')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('was_read', models.BooleanField(default=None, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.issue')),
                ('reading_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mycomics.readingorder')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gcd.story')),
            ],
            options={
                'db_table': 'mycomics_reading_order_item',
                'ordering': ['sequence_number'],
            },
        ),
    ]
