# Generated by Django 4.2.20 on 2025-09-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycomics', '0009_reading_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingorder',
            options={'ordering': ['name']},
        ),
    ]
