# Generated by Django 5.2.9 on 2025-12-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycomics', '0010_alter_readingorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingorder',
            name='public',
            field=models.BooleanField(default=False, help_text='If checked, other users will be able to view this reading list.', verbose_name='reading list is public'),
        ),
    ]
