# -*- coding: utf-8 -*-
from django.urls import path, register_converter
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from django.views.generic import base as bv

from apps.oi import views as oi_views
from apps.oi import covers as oi_covers
from apps.oi import import_export as oi_import
from apps.oi import coordinators as oi_coordinators


class SignedIntConverter:
    regex = '-?\\d+'

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return '%d' % value


register_converter(SignedIntConverter, 'signed_int')


urlpatterns = [
    # General-purpose new record add page.
    path('add/',
      login_required(
        bv.TemplateView.as_view(template_name='oi/edit/add.html',
        extra_context={'queue_name': 'add_new'})),
      name='add'),

    path('mentoring/', oi_views.mentoring,
      name='mentoring'),
    path('contacting/', oi_views.contacting,
      name='contacting'),


    path('award/add/',
     oi_views.add_award, name='add_award'),
    path('award/<int:award_id>/received_award/add/',
     oi_views.select_award_recipient, name='select_award_recipient'),
    re_path(r'^award/(?P<award_id>\d+)/received_award/(?P<model_name>\w+)/(?P<id>\d+)/add/$',
     oi_views.add_received_award, name='add_received_award'),

    # Creator URLs
    path('creator/add/',
     oi_views.add_creator, name='add_creator'),
    path('creator/<int:creator_id>/award/add/',
     oi_views.add_creator_award, name='add_creator_award'),
    path('creator/<int:creator_id>/influence/add/',
     oi_views.add_creator_art_influence, name='add_creator_art_influence'),
    path('creator/<int:creator_id>/membership/add/',
     oi_views.add_creator_membership, name='add_creator_membership'),
    path('creator/<int:creator_id>/non_comic_work/add/',
     oi_views.add_creator_non_comic_work, name='add_creator_non_comic_work'),
    path('creator/<int:creator_id>/relation/add/',
     oi_views.add_creator_relation, name='add_creator_relation'),
    path('creator/<int:creator_id>/school/add/',
     oi_views.add_creator_school, name='add_creator_school'),
    path('creator/<int:creator_id>/signature/add/',
     oi_views.add_creator_signature, name='add_creator_signature'),
    path('creator/<int:creator_id>/degree/add/',
     oi_views.add_creator_degree, name='add_creator_degree'),

    # Publisher URLs
    path('publisher/add/',
        oi_views.add_publisher,
        name='add_publisher'),
    path('indicia_publisher/add/parent/<int:parent_id>/',
        oi_views.add_indicia_publisher,
        name='add_indicia_publisher'),
    path('brand_group/add/parent/<int:parent_id>/',
        oi_views.add_brand_group,
        name='add_brand_group'),
    path('brand/add/publisher/<int:publisher_id>/',
        oi_views.add_brand,
        name='add_brand_via_publisher'),
    path('brand/add/group/<int:brand_group_id>/',
        oi_views.add_brand,
        name='add_brand_via_group'),
    path('brand_use/add/brand/<int:brand_id>/',
        oi_views.add_brand_use,
        name='add_brand_use'),
    path('brand_use/add/brand/<int:brand_id>/publisher/<int:publisher_id>/',
        oi_views.add_brand_use,
        name='add_brand_use'),

    # Printer URLs
    path('printer/add/',
        oi_views.add_printer,
        name='add_printer'),
    path('indicia_printer/add/parent/<int:parent_id>/',
        oi_views.add_indicia_printer,
        name='add_indicia_printer'),

    # Series URLs
    path('series/add/publisher/<int:publisher_id>/',
        oi_views.add_series,
        name='add_series'),
    path('series/<int:series_id>/reorder/',
        oi_views.reorder_series,
        name='reorder_series'),
    path('series/<int:series_id>/reorder/key_date/',
        oi_views.reorder_series_by_key_date,
        name='reorder_series_key_date'),
    path('series/<int:series_id>/reorder/issue_number/',
        oi_views.reorder_series_by_issue_number,
        name='reorder_series_issue_number'),
    path('series/<int:series_id>/edit_bonds/',
        oi_views.edit_series_bonds, name='edit_series_bonds'),
    path('series/revision/<int:series_revision_id>/move/<int:publisher_id>/',
        oi_views.move_series, name='move_series'),
    path('series_bond/add/<int:series_id>/',
        oi_views.add_series_bond, name='add_series_bond'),
    # Series Bond URLs
    path('series_bond/revision/<int:id>/',
        oi_views.edit_series_bond, name='edit_series_bond'),

    # Issue URLs
    path('series/<int:series_id>/add_issue/', oi_views.add_issue,
        name='add_issue'),
    path('series/<int:series_id>/add_issues/', oi_views.add_issues,
        name='add_issues'),
    re_path(r'^series/(?P<series_id>\d+)/add_issues/(?P<method>\w+)/$',
        oi_views.add_issues,
        name='add_multiple_issues'),
    path('issue/<int:issue_id>/add_variant_issue/', oi_views.add_variant_issue,
        name='add_variant_issue'),
    path('issue/<int:issue_id>/add_variant_issue/<int:cover_id>/',
        oi_views.add_variant_issue, {'edit_with_base': True},
        name='add_variant_issue'),
    path('issue/<int:issue_id>/edit_two_issues/',
        oi_views.edit_two_issues,
        name='edit_two_issues'),
    path('issue/<int:issue_one_id>/edit_with/<int:issue_two_id>/',
        oi_views.reserve_two_issues,
        name='reserve_two_issues'),
    path('issue/revision/<int:id>/migrate/',
        oi_views.migrate_issue_revision,
        name='migrate_issue_revision'),

    path('issue/<int:issue_id>/export_issue/',
        oi_import.export_issue_to_file,
        name='export_issue'),
    path('issue/<int:issue_id>/export_issue_csv/',
        oi_import.export_issue_to_file, {'use_csv': True},
        name='export_issue_csv'),
    path('issue_revision/<int:issue_id>/export_issue_revision/',
        oi_import.export_issue_to_file,  {'revision': True},
        name='export_issue_revision'),
    path('issue_revision/<int:issue_id>/export_issue_revision_csv/',
        oi_import.export_issue_to_file, {'use_csv': True, 'revision': True},
        name='export_issue_revision_csv'),

    path('issue/<int:issue_id>/import_issue/<int:changeset_id>/',
        oi_import.import_issue_from_file,
        name='import_issue'),
    path('issue/revision/<int:issue_revision_id>/add_variant_to_issue_revision/<int:changeset_id>',
        oi_views.add_variant_to_issue_revision,
        name='add_variant_to_issue_revision'),
    path('issue/revision/<int:issue_revision_id>/add_story/<int:changeset_id>',
        oi_views.add_story,
        name='add_story'),
    path('issue/revision/<int:issue_revision_id>/copy_story_revision/<int:changeset_id>',
        oi_views.copy_story_revision,
        name='copy_story_revision'),
    path('issue/revision/<int:issue_revision_id>/confirm_copy_story/<int:story_id>/<signed_int:sequence_number>/',
        oi_views.copy_sequence,
        name='confirm_copy_story'),
    path('issue/revision/<int:issue_revision_id>/confirm_copy_story_revision/<int:story_revision_id>/',
        oi_views.copy_story_revision,
        name='confirm_copy_story_revision'),
    path('issue/<int:issue_id>/import_stories/<int:changeset_id>/',
        oi_import.import_sequences_from_file,
        name='import_stories'),
    path('issue/<int:issue_id>/reorder_stories/<int:changeset_id>',
        oi_views.reorder_stories,
        name='reorder_stories'),
    path('issue/revision/<int:issue_revision_id>/move/<int:series_id>/',
        oi_views.move_issue, name='move_issue'),
    path('issue/revision/<int:issue_revision_id>/compare/<int:issue_id>/',
        oi_views.compare_issues_copy, name='compare_issues_copy'),

    path('bulk_issue_edit/',
        oi_views.edit_issues_in_bulk,
        name='edit_issues_in_bulk'),

    # Story URLs
    # can be changed to r'^(?P<model_name>\w+)/revision/(?P<id>\d+)/remove/
    # later if needed
    path('story/revision/<int:id>/remove/',
        oi_views.remove_story_revision,
        name='remove_story_revision'),
    path('story/revision/<int:id>/delete/',
        oi_views.toggle_delete_story_revision,
        name='toggle_delete_story_revision'),
    path('story/revision/<int:id>/move/',
        oi_views.move_story_revision,
        name='move_story_revision'),
    path('story/revision/<int:id>/migrate/',
        oi_views.migrate_story_revision,
        name='migrate_story_revision'),
    path('story/revision/<int:story_revision_id>/compare_story/<int:story_id>/',
        oi_views.compare_stories_copy, name='compare_stories_copy'),
    path('story/revision/<int:story_revision_id>/compare_revision/<int:other_revision_id>/',
        oi_views.compare_stories_copy, name='compare_revisions_copy'),
    path('story/revision/<int:story_revision_id>/select_compare/',
        oi_views.story_select_compare, name='story_select_compare'),

    # Story Arc URLs
    path('story_arc/add/',
      oi_views.add_story_arc, name='add_story_arc'),
    path('story_arc/<int:story_arc_id>/relation/add/',
      oi_views.add_story_arc_relation, name='add_story_arc_relation'),

    # Feature URLs
    path('feature/add/',
      oi_views.add_feature, name='add_feature'),
    path('feature/<int:feature_id>/logo/add/',
      oi_views.add_feature_logo, name='add_feature_logo'),
    path('feature/<int:feature_id>/relation/add/',
      oi_views.add_feature_relation, name='add_feature_relation'),

    # Universe URLs
    path('universe/add/',
      oi_views.add_universe, name='add_universe'),

    # Character URLs
    path('character/add/',
      oi_views.add_character, name='add_character'),
    path('group/add/',
      oi_views.add_group, name='add_group'),
    path('character/<int:character_id>/membership/add/',
      oi_views.add_group_membership, name='add_group_membership'),
    path('character/<int:character_id>/relation/add/',
      oi_views.add_character_relation, name='add_character_relation'),
    path('group/<int:group_id>/members/add/',
      oi_views.add_group_member, name='add_group_member'),
    path('group/<int:group_id>/relation/add/',
      oi_views.add_group_relation, name='add_group_relation'),

    # Image URLs
    re_path(r'^(?P<model_name>\w+)/(?P<id>\d+)/upload_image/(?P<image_type>\w+)/$',
        oi_covers.upload_image,
        name='upload_image'),
    re_path(r'^(?P<model_name>\w+)/(?P<id>\d+)/replace_image/(?P<image_id>\d+)/$',
        oi_covers.replace_image,
        name='replace_image'),
    path('mark_image_revision/<path:revision_id>/', oi_covers.mark_image,
      {'marked': True}, name='mark_image_revision'),
    path('unmark_image_revision/<path:revision_id>/', oi_covers.mark_image,
      {'marked': False}, name='unmark_image_revision'),
    path('mark_image/<path:image_id>/', oi_covers.mark_image,
      {'marked': True}, name='mark_cover'),
    path('unmark_image/<path:image_id>/', oi_covers.mark_image,
      {'marked': False}, name='unmark_cover'),

    # Cover URLs
    path('edit_covers/<int:issue_id>/', oi_covers.edit_covers,
      name='edit_covers'),
    path('upload_cover/<int:issue_id>/', oi_covers.upload_cover,
      name='upload_cover'),
    path('upload_variant/<int:issue_id>/', oi_covers.upload_variant,
      name='upload_variant'),
    path('flip_artwork_flag/<path:revision_id>/',
      oi_covers.flip_artwork_flag, name='flip_artwork_flag'),
    path('replace_cover/<int:cover_id>/', oi_covers.upload_cover,
      name='replace_cover'),
    path('gatefold_cover/',
      oi_covers.process_edited_gatefold_cover, name='gatefold_cover'),
    path('uploaded_cover/<int:revision_id>/', oi_covers.uploaded_cover,
      name='upload_cover_complete'),
    path('mark_cover_revision/<path:revision_id>/', oi_covers.mark_cover,
      {'marked': True}, name='mark_cover_revision'),
    path('unmark_cover_revision/<path:revision_id>/', oi_covers.mark_cover,
      {'marked': False}, name='unmark_cover_revision'),
    path('mark_cover/<path:cover_id>/', oi_covers.mark_cover,
      {'marked': True}, name='mark_cover'),
    path('unmark_cover/<path:cover_id>/', oi_covers.mark_cover,
      {'marked': False}, name='unmark_cover'),
    path('cover/changeset/<int:id>/move/', oi_views.move_cover,
      name='move_cover'),
    path('cover/<int:cover_id>/changeset/<int:id>/move/', oi_views.move_cover,
      name='move_cover'),
    path('cover/<int:cover_id>/changeset/<int:id>/undo_move',
      oi_views.undo_move_cover, name='undo_move_cover'),

    path('ongoing/', oi_views.ongoing, name='reserve_ongoing'),
    path('ongoing/<int:series_id>/delete/', oi_views.delete_ongoing,
        name='delete_ongoing'),

    path('issue/revision/<int:id>/list_reprints/',
      oi_views.list_issue_reprints, name='list_issue_reprints'),
    path('reserve_reprint/<int:reprint_id>/edit/<int:changeset_id>/',
      oi_views.reserve_reprint, name='reserve_reprint'),
    path('reprint/revision/<int:id>/side/<path:which_side>/',
      oi_views.edit_reprint, name='edit_reprint'),
    path('reprint/revision/<int:id>/',
      oi_views.edit_reprint, name='edit_reprint'),

    re_path(r'^story/revision/(?P<story_id>\d+)/add_reprint/(?P<changeset_id>\d+)/reprint_note/(?P<reprint_note>.+|)/$',
      oi_views.add_reprint, name='add_story_reprint'),
    path('story/revision/<int:story_id>/add_reprint/<int:changeset_id>/',
      oi_views.add_reprint, name='add_story_reprint'),

    path('issue/revision/<int:issue_id>/add_reprint/<int:changeset_id>/reprint_note/<path:reprint_note>/',
      oi_views.add_reprint, name='add_issue_reprint'),
    path('issue/revision/<int:issue_id>/add_reprint/<int:changeset_id>/',
      oi_views.add_reprint, name='add_issue_reprint'),

    path('reprint/revision/<path:reprint_revision_id>/storyrevision/<int:story_revision_id>/confirm_reprint/<int:changeset_id>/story/<int:story_two_id>/',
      oi_views.save_reprint, name='save_revision_story_reprint'),
    path('reprint/revision/<path:reprint_revision_id>/storyrevision/<int:story_revision_id>/confirm_reprint/<int:changeset_id>/issue/<int:issue_two_id>/',
      oi_views.save_reprint, name='save_revision_issue_reprint'),

    path('reprint/revision/<path:reprint_revision_id>/story/<int:story_one_id>/confirm_reprint/<int:changeset_id>/story/<int:story_two_id>/',
      oi_views.save_reprint, name='save_story_story_reprint'),
    path('reprint/revision/<path:reprint_revision_id>/story/<int:story_one_id>/confirm_reprint/<int:changeset_id>/issue/<int:issue_two_id>/',
      oi_views.save_reprint, name='save_story_issue_reprint'),

    path('reprint/revision/<path:reprint_revision_id>/issue/<int:issue_one_id>/confirm_reprint/<int:changeset_id>/story/<int:story_two_id>/',
      oi_views.save_reprint, name='save_issue_story_reprint'),
    path('reprint/revision/<path:reprint_revision_id>/issue/<int:issue_one_id>/confirm_reprint/<int:changeset_id>/issue/<int:issue_two_id>/',
      oi_views.save_reprint, name='save_issue_issue_reprint'),

    path('reprint/revision/<int:id>/remove/',
        oi_views.remove_reprint_revision, name='remove_reprint_revision'),
    path('reprint/revision/<int:id>/select_internal/issue/<int:issue_id>/changeset/<int:changeset_id>/side/<path:which_side>/',
      oi_views.select_internal_object, name='select_internal_issue'),
    path('reprint/revision/<int:id>/select_internal/story/<int:story_id>/changeset/<int:changeset_id>/side/<path:which_side>/',
      oi_views.select_internal_object, name='select_internal_story'),

    path('reprint/revision/<path:reprint_revision_id>/create_sequence/issue/<int:issue_id>/story/<int:story_id>/',
      oi_views.create_matching_sequence, name='create_matching_sequence'),
    path('reprint/revision/<path:reprint_revision_id>/create_edit_sequence/issue/<int:issue_id>/story/<int:story_id>/',
      oi_views.create_matching_sequence, {'edit' : True, 'qualifier': False}, name='create_edit_matching_sequence'),
    path('reprint/revision/<path:reprint_revision_id>/create_edit_sequence_qualifier/issue/<int:issue_id>/story/<int:story_id>/',
      oi_views.create_matching_sequence, {'edit' : True, 'qualifier': True}, name='create_edit_matching_sequence_qualifier'),

    # Generic URLs
    re_path(r'^(?P<model_name>\w+)/(?P<id>\d+)/reserve/$', oi_views.reserve,
        name='reserve_revision'),
    re_path(r'^(?P<model_name>\w+)/(?P<id>\d+)/delete/$', oi_views.delete,
        name='delete_revision'),
    re_path(r'^(?P<model_name>\w+)/revision/(?P<id>\d+)/edit/$',
        oi_views.edit_revision,
        name='edit_revision'),
    path('changeset/<int:id>/edit/', oi_views.edit, name='edit'),
    path('changeset/<int:id>/submit/', oi_views.submit, name='submit'),
    path('changeset/<int:id>/retract/', oi_views.retract, name='retract'),
    path('changeset/<int:id>/discard/', oi_views.discard, name='discard'),
    path('changeset/<int:id>/<int:has_comment>/confirm_discard/', oi_views.confirm_discard,
        name='confirm_discard'),
    path('changeset/<int:id>/assign/', oi_views.assign, name='assign'),
    path('changeset/<int:id>/release/', oi_views.release, name='release'),
    path('changeset/<int:id>/approve/', oi_views.approve, name='approve'),
    path('changeset/<int:id>/disapprove/', oi_views.disapprove,
        name='disapprove'),
    path('changeset/<int:id>/process/', oi_views.process, name='process'),
    re_path(r'^(?P<model_name>\w+)/revision/(?P<id>\d+)/process/$',
        oi_views.process_revision,
        name='process_revision'),
    path('changeset/<int:id>/compare/', oi_views.compare, name='compare'),
    re_path(r'^(?P<model_name>\w+)/revision/(?P<id>\d+)/preview/$', oi_views.preview,
        name='preview_revision'),

    # queue URLs
    path('queues/editing/', oi_views.show_queue,
       {'queue_name': 'editing',},
        name='editing'),
    path('queues/pending/', oi_views.show_queue,
       {'queue_name': 'pending',},
        name='pending'),
    path('queues/reviews/', oi_views.show_queue,
       {'queue_name': 'reviews',},
        name='reviewing'),
    path('queues/editor_log/', oi_views.show_queue,
       {'queue_name': 'editor_log',},
        name='editor_log'),
    path('queues/approved/', oi_views.show_queue,
       {'queue_name': 'approved',},
        name='approved'),
    path('queues/commented/', oi_views.show_queue,
       {'queue_name': 'commented',},
        name='commented'),
    path('queues/covers_pending/', oi_views.show_queue,
       {'queue_name': 'covers',},
        name='pending_covers'),

    re_path(r'^coordinator/clear_publisher_series',
      oi_coordinators.clear_reservations_one_week,
      {}, name='clear_publisher_series'),
    re_path(r'^coordinator/clear_issues',
      oi_coordinators.clear_reservations_three_weeks,
      {}, name='clear_issues'),
    path('coordinator/',
        bv.TemplateView.as_view(template_name='oi/edit/coordinators.html'),
        name='coordinators_toc'),
]

urlpatterns += [
    path('changeset/<int:id>/', bv.RedirectView.as_view(url='compare',
                                                             permanent=False)),
]
