# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import apps.gcd.models.image
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False, db_index=True)),
                ('year_ended_uncertain', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField()),
                ('url', models.URLField(default='', max_length=255, blank=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('issue_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BrandGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False, db_index=True)),
                ('year_ended_uncertain', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField()),
                ('url', models.URLField(default='', max_length=255, blank=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('issue_count', models.IntegerField(default=0)),
                ('keywords', taggit.managers.TaggableManager(to='taggit.Tag', through='taggit.TaggedItem', help_text='A comma-separated list of tags.', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'gcd_brand_group',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BrandUse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False, db_index=True)),
                ('year_ended_uncertain', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField()),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('emblem', models.ForeignKey(related_name='in_use', to='gcd.Brand')),
            ],
            options={
                'db_table': 'gcd_brand_use',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(unique=True, max_length=10)),
                ('name', models.CharField(max_length=255, db_index=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Countries',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CountStats',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=40, db_index=True)),
                ('count', models.IntegerField()),
                ('country', models.ForeignKey(to='gcd.Country', null=True)),
            ],
            options={
                'db_table': 'gcd_count_stats',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('marked', models.BooleanField(default=False)),
                ('limit_display', models.BooleanField(default=False)),
                ('is_wraparound', models.BooleanField(default=False)),
                ('front_left', models.IntegerField(default=0, null=True, blank=True)),
                ('front_right', models.IntegerField(default=0, null=True, blank=True)),
                ('front_bottom', models.IntegerField(default=0, null=True, blank=True)),
                ('front_top', models.IntegerField(default=0, null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_upload', models.DateTimeField(null=True, db_index=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
            ],
            options={
                'ordering': ['issue'],
                'get_latest_by': 'id',
                'permissions': (('can_upload_cover', 'can upload cover'),),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('error_key', models.CharField(max_length=40, serialize=False, editable=False, primary_key=True)),
                ('error_text', models.TextField(null=True, blank=True)),
                ('is_safe', models.BooleanField(default=False)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object_id', models.PositiveIntegerField(null=True, db_index=True)),
                ('image_file', models.ImageField(upload_to=apps.gcd.models.image.get_generic_image_path)),
                ('marked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType', null=True)),
            ],
            options={
                'db_table': 'gcd_image',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=50, db_index=True)),
                ('unique', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gcd_image_type',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ImpGrant',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('imps', models.IntegerField()),
                ('grant_type', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'gcd_imp_grant',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IndexCredit',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('run', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gcd_series_indexers',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Indexer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('interests', models.TextField(null=True, blank=True)),
                ('opt_in_email', models.BooleanField(default=False, db_index=True)),
                ('from_where', models.TextField(blank=True)),
                ('max_reservations', models.IntegerField(default=1)),
                ('max_ongoing', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=False, db_index=True)),
                ('is_banned', models.BooleanField(default=False, db_index=True)),
                ('deceased', models.BooleanField(default=False, db_index=True)),
                ('registration_key', models.CharField(max_length=40, null=True, editable=False, db_index=True)),
                ('registration_expires', models.DateField(db_index=True, null=True, blank=True)),
                ('imps', models.IntegerField(default=0)),
                ('issue_detail', models.IntegerField(default=1)),
                ('notify_on_approve', models.BooleanField(default=True, db_index=True)),
                ('collapse_compare_view', models.BooleanField(default=False, db_index=True)),
                ('show_wiki_links', models.BooleanField(default=True, db_index=True)),
                ('country', models.ForeignKey(related_name='indexers', to='gcd.Country')),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
                'permissions': (('can_upload_cover', 'Can upload covers'), ('can_reserve', 'Can reserve a record for add, edit or delete'), ('can_approve', 'Can approve a change to a record'), ('can_cancel', 'Can cancel a pending change they did not open'), ('can_mentor', 'Can mentor new indexers'), ('can_vote', 'Can vote in GCD elections'), ('can_publish', 'Can publish non-database content on the web site'), ('on_board', 'Is on the Board of Directors')),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IndiciaPublisher',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False, db_index=True)),
                ('year_ended_uncertain', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField()),
                ('url', models.URLField(default='', max_length=255, blank=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('is_surrogate', models.BooleanField(default=False, db_index=True)),
                ('issue_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(to='gcd.Country')),
                ('keywords', taggit.managers.TaggableManager(to='taggit.Tag', through='taggit.TaggedItem', help_text='A comma-separated list of tags.', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'gcd_indicia_publisher',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('number', models.CharField(max_length=50, db_index=True)),
                ('title', models.CharField(max_length=255, db_index=True)),
                ('no_title', models.BooleanField(default=False, db_index=True)),
                ('volume', models.CharField(max_length=50, db_index=True)),
                ('no_volume', models.BooleanField(default=False, db_index=True)),
                ('display_volume_with_number', models.BooleanField(default=False, db_index=True)),
                ('isbn', models.CharField(max_length=32, db_index=True)),
                ('no_isbn', models.BooleanField(default=False, db_index=True)),
                ('valid_isbn', models.CharField(max_length=13, db_index=True)),
                ('variant_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=38, db_index=True)),
                ('no_barcode', models.BooleanField(default=False)),
                ('rating', models.CharField(default=b'', max_length=255, db_index=True)),
                ('no_rating', models.BooleanField(default=False, db_index=True)),
                ('publication_date', models.CharField(max_length=255)),
                ('key_date', models.CharField(max_length=10, db_index=True)),
                ('on_sale_date', models.CharField(max_length=10, db_index=True)),
                ('on_sale_date_uncertain', models.BooleanField(default=False)),
                ('sort_code', models.IntegerField(db_index=True)),
                ('indicia_frequency', models.CharField(max_length=255)),
                ('no_indicia_frequency', models.BooleanField(default=False, db_index=True)),
                ('price', models.CharField(max_length=255)),
                ('page_count', models.DecimalField(null=True, max_digits=10, decimal_places=3)),
                ('page_count_uncertain', models.BooleanField(default=False)),
                ('editing', models.TextField()),
                ('no_editing', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField()),
                ('indicia_pub_not_printed', models.BooleanField(default=False)),
                ('no_brand', models.BooleanField(default=False, db_index=True)),
                ('is_indexed', models.IntegerField(default=0, db_index=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('brand', models.ForeignKey(to='gcd.Brand', null=True)),
                ('indicia_publisher', models.ForeignKey(to='gcd.IndiciaPublisher', null=True)),
                ('keywords', taggit.managers.TaggableManager(to='taggit.Tag', through='taggit.TaggedItem', help_text='A comma-separated list of tags.', verbose_name='Tags')),
            ],
            options={
                'ordering': ['series', 'sort_code'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IssueReprint',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notes', models.TextField(max_length=255)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('origin_issue', models.ForeignKey(related_name='to_issue_reprints', to='gcd.Issue')),
                ('target_issue', models.ForeignKey(related_name='from_issue_reprints', to='gcd.Issue')),
            ],
            options={
                'db_table': 'gcd_issue_reprint',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(unique=True, max_length=10)),
                ('name', models.CharField(max_length=255, db_index=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MigrationStoryStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('reprint_needs_inspection', models.BooleanField(default=False, db_index=True)),
                ('reprint_confirmed', models.BooleanField(default=False, db_index=True)),
                ('reprint_original_notes', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gcd_migration_story_status',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('year_began', models.IntegerField(null=True, db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False, db_index=True)),
                ('year_ended_uncertain', models.BooleanField(default=False, db_index=True)),
                ('notes', models.TextField()),
                ('url', models.URLField(default='', max_length=255, blank=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('imprint_count', models.IntegerField(default=0)),
                ('brand_count', models.IntegerField(default=0, db_index=True)),
                ('indicia_publisher_count', models.IntegerField(default=0, db_index=True)),
                ('series_count', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('is_master', models.BooleanField(default=False, db_index=True)),
                ('country', models.ForeignKey(to='gcd.Country')),
                ('keywords', taggit.managers.TaggableManager(to='taggit.Tag', through='taggit.TaggedItem', help_text='A comma-separated list of tags.', verbose_name='Tags')),
                ('parent', models.ForeignKey(related_name='imprint_set', to='gcd.Publisher', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RecentIndexedIssue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('issue', models.ForeignKey(to='gcd.Issue')),
                ('language', models.ForeignKey(to='gcd.Language', null=True)),
            ],
            options={
                'db_table': 'gcd_recent_indexed_issue',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Reprint',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notes', models.TextField(max_length=255)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReprintFromIssue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notes', models.TextField(max_length=255)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('origin_issue', models.ForeignKey(related_name='to_reprints', to='gcd.Issue')),
            ],
            options={
                'db_table': 'gcd_reprint_from_issue',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReprintToIssue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notes', models.TextField(max_length=255)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
            ],
            options={
                'db_table': 'gcd_reprint_to_issue',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.IntegerField(db_index=True)),
                ('expires', models.DateField(null=True, blank=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('indexer', models.ForeignKey(related_name='reservation_set', to='gcd.Indexer')),
                ('issue', models.ForeignKey(related_name='reservation_set', to='gcd.Issue')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('sort_name', models.CharField(max_length=255, db_index=True)),
                ('format', models.CharField(default='', max_length=255)),
                ('color', models.CharField(default='', max_length=255)),
                ('dimensions', models.CharField(default='', max_length=255)),
                ('paper_stock', models.CharField(default='', max_length=255)),
                ('binding', models.CharField(default='', max_length=255)),
                ('publishing_format', models.CharField(default='', max_length=255)),
                ('notes', models.TextField()),
                ('year_began', models.IntegerField(db_index=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(default=False)),
                ('year_ended_uncertain', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False, db_index=True)),
                ('publication_dates', models.CharField(max_length=255)),
                ('issue_count', models.IntegerField()),
                ('publication_notes', models.TextField()),
                ('tracking_notes', models.TextField()),
                ('has_barcode', models.BooleanField(default=False)),
                ('has_indicia_frequency', models.BooleanField(default=False)),
                ('has_isbn', models.BooleanField(default=False)),
                ('has_issue_title', models.BooleanField(default=False)),
                ('has_volume', models.BooleanField(default=False)),
                ('has_rating', models.BooleanField(default=False)),
                ('is_comics_publication', models.BooleanField(default=False)),
                ('is_singleton', models.BooleanField(default=False)),
                ('has_gallery', models.BooleanField(default=False, db_index=True)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('open_reserve', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('country', models.ForeignKey(to='gcd.Country')),
                ('first_issue', models.ForeignKey(related_name='first_issue_series_set', to='gcd.Issue', null=True)),
                ('keywords', taggit.managers.TaggableManager(to='taggit.Tag', through='taggit.TaggedItem', help_text='A comma-separated list of tags.', verbose_name='Tags')),
                ('language', models.ForeignKey(to='gcd.Language')),
                ('last_issue', models.ForeignKey(related_name='last_issue_series_set', to='gcd.Issue', null=True)),
            ],
            options={
                'ordering': ['sort_name', 'year_began'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SeriesBond',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notes', models.TextField(max_length=255)),
                ('reserved', models.BooleanField(default=False, db_index=True)),
            ],
            options={
                'db_table': 'gcd_series_bond',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SeriesBondType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'gcd_series_bond_type',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SeriesPublicationType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, db_index=True)),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'gcd_series_publication_type',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=255)),
                ('title_inferred', models.BooleanField(default=False, db_index=True)),
                ('feature', models.CharField(max_length=255)),
                ('sequence_number', models.IntegerField()),
                ('page_count', models.DecimalField(null=True, max_digits=10, decimal_places=3, db_index=True)),
                ('page_count_uncertain', models.BooleanField(default=False, db_index=True)),
                ('script', models.TextField()),
                ('pencils', models.TextField()),
                ('inks', models.TextField()),
                ('colors', models.TextField()),
                ('letters', models.TextField()),
                ('editing', models.TextField()),
                ('no_script', models.BooleanField(default=False, db_index=True)),
                ('no_pencils', models.BooleanField(default=False, db_index=True)),
                ('no_inks', models.BooleanField(default=False, db_index=True)),
                ('no_colors', models.BooleanField(default=False, db_index=True)),
                ('no_letters', models.BooleanField(default=False, db_index=True)),
                ('no_editing', models.BooleanField(default=False, db_index=True)),
                ('job_number', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=255)),
                ('characters', models.TextField()),
                ('synopsis', models.TextField()),
                ('reprint_notes', models.TextField()),
                ('notes', models.TextField()),
                ('reserved', models.BooleanField(default=False, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False, db_index=True)),
                ('issue', models.ForeignKey(to='gcd.Issue')),
                ('keywords', taggit.managers.TaggableManager(to='taggit.Tag', through='taggit.TaggedItem', help_text='A comma-separated list of tags.', verbose_name='Tags')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StoryType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=50, db_index=True)),
                ('sort_code', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['sort_code'],
                'db_table': 'gcd_story_type',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.ForeignKey(to='gcd.StoryType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='seriesbond',
            name='bond_type',
            field=models.ForeignKey(to='gcd.SeriesBondType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='seriesbond',
            name='origin',
            field=models.ForeignKey(related_name='to_series_bond', to='gcd.Series'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='seriesbond',
            name='origin_issue',
            field=models.ForeignKey(related_name='to_series_issue_bond', to='gcd.Issue', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='seriesbond',
            name='target',
            field=models.ForeignKey(related_name='from_series_bond', to='gcd.Series'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='seriesbond',
            name='target_issue',
            field=models.ForeignKey(related_name='from_series_issue_bond', to='gcd.Issue', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='series',
            name='publication_type',
            field=models.ForeignKey(blank=True, to='gcd.SeriesPublicationType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='series',
            name='publisher',
            field=models.ForeignKey(to='gcd.Publisher'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprinttoissue',
            name='origin',
            field=models.ForeignKey(related_name='to_issue_reprints', to='gcd.Story'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprinttoissue',
            name='target_issue',
            field=models.ForeignKey(related_name='from_reprints', to='gcd.Issue'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprintfromissue',
            name='target',
            field=models.ForeignKey(related_name='from_issue_reprints', to='gcd.Story'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprint',
            name='origin',
            field=models.ForeignKey(related_name='to_reprints', to='gcd.Story'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='reprint',
            name='target',
            field=models.ForeignKey(related_name='from_reprints', to='gcd.Story'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='migrationstorystatus',
            name='story',
            field=models.OneToOneField(related_name='migration_status', to='gcd.Story'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='issue',
            name='series',
            field=models.ForeignKey(to='gcd.Series'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='issue',
            name='variant_of',
            field=models.ForeignKey(related_name='variant_set', to='gcd.Issue', null=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('series', 'sort_code')]),
        ),
        migrations.AddField(
            model_name='indiciapublisher',
            name='parent',
            field=models.ForeignKey(to='gcd.Publisher'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='indexer',
            name='languages',
            field=models.ManyToManyField(related_name='indexers', db_table=b'gcd_indexer_languages', to='gcd.Language'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='indexer',
            name='mentor',
            field=models.ForeignKey(related_name='mentees', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='indexer',
            name='user',
            field=models.OneToOneField(to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='indexcredit',
            name='indexer',
            field=models.ForeignKey(related_name='index_credit_set', to='gcd.Indexer'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='indexcredit',
            name='series',
            field=models.ForeignKey(related_name='index_credit_set', to='gcd.Series'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='impgrant',
            name='indexer',
            field=models.ForeignKey(related_name='imp_grant_set', to='gcd.Indexer'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.ForeignKey(to='gcd.ImageType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cover',
            name='issue',
            field=models.ForeignKey(to='gcd.Issue'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='countstats',
            name='language',
            field=models.ForeignKey(to='gcd.Language', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='branduse',
            name='publisher',
            field=models.ForeignKey(to='gcd.Publisher'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brandgroup',
            name='parent',
            field=models.ForeignKey(to='gcd.Publisher'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brand',
            name='group',
            field=models.ManyToManyField(to='gcd.BrandGroup', db_table=b'gcd_brand_emblem_group', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brand',
            name='keywords',
            field=taggit.managers.TaggableManager(to='taggit.Tag', through='taggit.TaggedItem', help_text='A comma-separated list of tags.', verbose_name='Tags'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='brand',
            name='parent',
            field=models.ForeignKey(blank=True, to='gcd.Publisher', null=True),
            preserve_default=True,
        ),
    ]
