# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0004_gcd_base_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereprint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 28, 2, 44, 54, 943021)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuereprint',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 2, 28, 2, 45, 2, 630018)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 28, 2, 45, 12, 913561)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprint',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 2, 28, 2, 45, 18, 928727)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprintfromissue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 28, 2, 45, 26, 240250)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprintfromissue',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 2, 28, 2, 45, 30, 655008)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprinttoissue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 28, 2, 45, 34, 767502)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprinttoissue',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 2, 28, 2, 45, 39, 838775)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesbond',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 28, 2, 45, 45, 494445)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesbond',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 2, 28, 2, 45, 49, 358886)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branduse',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='branduse',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
