# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0005_standard_link_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='open_reserve',
        ),
    ]
