# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0006_remove_series_open_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprint',
            name='origin_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_to_issue_reprints', to='gcd.Issue'),
        ),
        migrations.AddField(
            model_name='reprint',
            name='target_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_from_issue_reprints', to='gcd.Issue'),
        ),
        migrations.AlterField(
            model_name='reprint',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_reprints', to='gcd.Story'),
        ),
        migrations.AlterField(
            model_name='reprint',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_reprints', to='gcd.Story'),
        ),
    ]
