# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-14 18:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0009_cleanup_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branduse',
            name='reserved',
        ),
        migrations.AlterField(
            model_name='branduse',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='branduse',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
