# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-03 21:00


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0011_add_sort_name_to_creatornamedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblioEntry',
            fields=[
                ('story_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gcd.Story')),
                ('page_began', models.IntegerField(null=True)),
                ('page_ended', models.IntegerField(null=True)),
                ('abstract', models.TextField()),
                ('doi', models.TextField()),
            ],
            options={
                'db_table': 'gcd_biblio_entry',
            },
            bases=('gcd.story',),
        ),
        migrations.AddField(
            model_name='series',
            name='has_about_comics',
            field=models.BooleanField(default=False),
        ),
    ]
