# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 02:23
from __future__ import unicode_literals

from django.db import migrations

def migrate_awards(apps, schema_editor):
    """
    Data migration to populate the ReceivedAward from CreatorAward.
    """
    # We can't import the model directly as it may be a newer
    # version than this migration expects.
    CreatorAward = apps.get_model('gcd', 'CreatorAward')
    ReceivedAward = apps.get_model('gcd', 'ReceivedAward')
    ContentType = apps.get_model('contenttypes', 'ContentType')
 
    creator_content_type = ContentType.objects.get(app_label='gcd',
                                                   model='creator')
 
    for creator_award in CreatorAward.objects.all():
        received_award = ReceivedAward(id=creator_award.id)
        received_award.content_type = creator_content_type
        received_award.object_id = creator_award.creator.pk
        received_award.award = creator_award.award
        received_award.award_name = creator_award.award_name
        received_award.no_award_name = creator_award.no_award_name
        received_award.award_year = creator_award.award_year
        received_award.award_year_uncertain = creator_award.award_year_uncertain
        received_award.notes = creator_award.notes
        received_award.deleted = creator_award.deleted
        received_award.save()
        
        if creator_award.data_source.count() > 0:
            for source in creator_award.data_source.all():
                received_award.data_source.add(source)
                creator_award.data_source.remove(source)

        # delete after/during changeset / revisions migration, not here
        #super(CreatorAward, creator_award).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0013_receivedaward'),
    ]

    operations = [
        migrations.RunPython(migrate_awards),
    ]
