# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-30 09:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0013_receivedaward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatoraward',
            name='award',
        ),
        migrations.RemoveField(
            model_name='creatoraward',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='creatoraward',
            name='data_source',
        ),
        migrations.AlterField(
            model_name='receivedaward',
            name='award_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
