# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-15 08:57


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0017_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField()),
                ('from_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_related_feature', to='gcd.Feature')),
            ],
            options={
                'ordering': ('to_feature', 'relation_type', 'from_feature'),
                'db_table': 'gcd_feature_relation',
                'verbose_name_plural': 'Feature Relations',
            },
        ),
        migrations.CreateModel(
            name='FeatureRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('reverse_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gcd_feature_relation_type',
            },
        ),
        migrations.AddField(
            model_name='featurerelation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_type', to='gcd.FeatureRelationType'),
        ),
        migrations.AddField(
            model_name='featurerelation',
            name='to_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_related_feature', to='gcd.Feature'),
        ),
    ]
