# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-13 18:18


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0018_add_feature_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sort_code', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['sort_code'],
                'db_table': 'gcd_credit_type',
            },
        ),
        migrations.CreateModel(
            name='StoryCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('is_credited', models.BooleanField(db_index=True, default=False)),
                ('is_signed', models.BooleanField(db_index=True, default=False)),
                ('uncertain', models.BooleanField(db_index=True, default=False)),
                ('signed_as', models.CharField(max_length=255)),
                ('credited_as', models.CharField(max_length=255)),
                ('credit_name', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CreatorNameDetail')),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CreditType')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='gcd.Story')),
            ],
            options={
                'db_table': 'gcd_story_credit',
            },
        ),
    ]
