# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-14 06:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0020_add_name_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatornamedetail',
            name='family_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creatornamedetail',
            name='given_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterModelOptions(
            name='creatornamedetail',
            options={'ordering': ['sort_name', '-creator__birth_date__year', 'type__id'], 'verbose_name_plural': 'CreatorName Details'},
        ),
    ]
