# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-15 21:12
from django.db import migrations

def migrate_offical(apps, schema_editor):
    CreatorNameDetail = apps.get_model('gcd', 'CreatorNameDetail')
    for creator in CreatorNameDetail.objects.filter(deleted=False,
                                                    type__id=1):
        creator.is_official_name = True
        creator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0022_relation_creator_name'),
    ]

    operations = [
        migrations.RunPython(migrate_offical),
    ]
