# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-16 11:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0023_migrate_gcd_official_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='feature_logo',
            field=models.ManyToManyField(to='gcd.FeatureLogo'),
        ),
        migrations.AddField(
            model_name='story',
            name='feature_object',
            field=models.ManyToManyField(to='gcd.Feature'),
        ),
    ]
