# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 23:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0024_use_feature_in_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('sort_name',)},
        ),
        migrations.AlterModelOptions(
            name='featurelogo',
            options={'ordering': ('sort_name',), 'verbose_name_plural': 'Feature Logos'},
        ),
        migrations.AlterField(
            model_name='nametype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
