# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0025_name_type_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('is_credited', models.BooleanField(db_index=True, default=False)),
                ('uncertain', models.BooleanField(db_index=True, default=False)),
                ('credited_as', models.CharField(max_length=255)),
                ('credit_name', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CreatorNameDetail')),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CreditType')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='gcd.Issue')),
            ],
            options={
                'db_table': 'gcd_issue_credit',
            },
        ),
        migrations.AlterField(
            model_name='creatorartinfluence',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_influences', to='gcd.Creator'),
        ),
        migrations.AlterField(
            model_name='creatorartinfluence',
            name='influence_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influenced_creators', to='gcd.Creator'),
        ),
    ]
