# Generated by Django 2.2.10 on 2020-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0026_creator_issue_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='year_overall_began',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='year_overall_began_uncertain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='year_overall_ended',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='year_overall_ended_uncertain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='brandgroup',
            name='year_overall_began',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='brandgroup',
            name='year_overall_began_uncertain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='brandgroup',
            name='year_overall_ended',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='brandgroup',
            name='year_overall_ended_uncertain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='indiciapublisher',
            name='year_overall_began',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='indiciapublisher',
            name='year_overall_began_uncertain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='indiciapublisher',
            name='year_overall_ended',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='indiciapublisher',
            name='year_overall_ended_uncertain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='year_overall_began',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='year_overall_began_uncertain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='year_overall_ended',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='year_overall_ended_uncertain',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
