# Generated by Django 2.2.10 on 2020-05-15 20:19

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('stddata', '0003_script'),
        ('gcd', '0027_add_publisher_second_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('year_began', models.IntegerField(db_index=True, null=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True, default=False)),
                ('year_ended_uncertain', models.BooleanField(db_index=True, default=False)),
                ('year_overall_began', models.IntegerField(db_index=True, null=True)),
                ('year_overall_ended', models.IntegerField(null=True)),
                ('year_overall_began_uncertain', models.BooleanField(db_index=True, default=False)),
                ('year_overall_ended_uncertain', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField()),
                ('url', models.URLField(blank=True, default='', max_length=255)),
                ('indicia_printer_count', models.IntegerField(db_index=True, default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stddata.Country')),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndiciaPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('year_began', models.IntegerField(db_index=True, null=True)),
                ('year_ended', models.IntegerField(null=True)),
                ('year_began_uncertain', models.BooleanField(db_index=True, default=False)),
                ('year_ended_uncertain', models.BooleanField(db_index=True, default=False)),
                ('year_overall_began', models.IntegerField(db_index=True, null=True)),
                ('year_overall_ended', models.IntegerField(null=True)),
                ('year_overall_began_uncertain', models.BooleanField(db_index=True, default=False)),
                ('year_overall_ended_uncertain', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField()),
                ('url', models.URLField(blank=True, default='', max_length=255)),
                ('issue_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stddata.Country')),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.Printer')),
            ],
            options={
                'db_table': 'gcd_indicia_printer',
                'ordering': ['name'],
            },
        ),
    ]
