# Generated by Django 2.2.12 on 2020-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0029_creatorsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='indicia_printer',
            field=models.ManyToManyField(to='gcd.IndiciaPrinter'),
        ),
        migrations.AddField(
            model_name='issue',
            name='no_indicia_printer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='has_indicia_printer',
            field=models.BooleanField(default=False),
        ),
    ]
