# Generated by Django 2.2.12 on 2020-12-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0033_add_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('reverse_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Group Relation Types',
                'db_table': 'gcd_group_relation_type',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='GroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField()),
                ('from_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_related_group', to='gcd.Group')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_type', to='gcd.GroupRelationType')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_related_group', to='gcd.Group')),
            ],
            options={
                'verbose_name_plural': 'Group Relations',
                'db_table': 'gcd_group_relation',
                'ordering': ('to_group', 'relation_type', 'from_group'),
            },
        ),
    ]
