# Generated by Django 2.2.12 on 2021-01-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0033_add_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeNumberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'gcd_code_number_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublisherCodeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_number', to='gcd.Issue')),
                ('number_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CodeNumberType')),
            ],
            options={
                'db_table': 'gcd_issue_code_number',
            },
        ),
    ]
