# Generated by Django 2.2.12 on 2021-02-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0034_publisher_code_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='has_publisher_code_number',
            field=models.BooleanField(default=False),
        ),
    ]
