# Generated by Django 2.2.12 on 2021-02-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0035_series_has_publisher_code_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='disambiguation',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
