# Generated by Django 2.2.20 on 2021-08-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0037_generic_feature_brand_emblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sort_code', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'gcd_character_role',
                'ordering': ['sort_code'],
            },
        ),
        migrations.AddField(
            model_name='characternamedetail',
            name='is_official_name',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StoryCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('is_flashback', models.BooleanField(db_index=True, default=False)),
                ('is_origin', models.BooleanField(db_index=True, default=False)),
                ('is_death', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.CharacterNameDetail')),
                ('group', models.ManyToManyField(to='gcd.Group')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcd.CharacterRole')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearing_characters', to='gcd.Story')),
            ],
            options={
                'db_table': 'gcd_story_character',
                'ordering': ['character__sort_name'],
            },
        ),
    ]
