# Generated by Django 2.2.20 on 2021-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0038_character_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycredit',
            name='is_sourced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='storycredit',
            name='sourced_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuecredit',
            name='is_sourced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='issuecredit',
            name='sourced_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
