# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 22:13
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0039_sourced_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reprint',
            name='reserved',
        ),
        migrations.AddField(
            model_name='reprint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 3, 20, 41, 50, 854236)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprint',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='reprint',
            name='origin_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_to_issue_reprints', to='gcd.Issue'),
        ),
        migrations.AddField(
            model_name='reprint',
            name='target_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_from_issue_reprints', to='gcd.Issue'),
        ),
        migrations.AlterField(
            model_name='reprint',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_all_reprints', to='gcd.Story'),
        ),
        migrations.AlterField(
            model_name='reprint',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_all_reprints', to='gcd.Story'),
        ),

    ]
