# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0041_consolidate_reprints'),
        ('oi', '0039_one_reprint_data_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereprint',
            name='origin_issue',
        ),
        migrations.RemoveField(
            model_name='issuereprint',
            name='target_issue',
        ),
        migrations.RemoveField(
            model_name='reprintfromissue',
            name='origin_issue',
        ),
        migrations.RemoveField(
            model_name='reprintfromissue',
            name='target',
        ),
        migrations.RemoveField(
            model_name='reprinttoissue',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='reprinttoissue',
            name='target_issue',
        ),
        migrations.AlterField(
            model_name='reprint',
            name='origin_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_all_reprints', to='gcd.Issue'),
        ),
        migrations.AlterField(
            model_name='reprint',
            name='target_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_all_reprints', to='gcd.Issue'),
        ),
        migrations.DeleteModel(
            name='IssueReprint',
        ),
        migrations.DeleteModel(
            name='ReprintFromIssue',
        ),
        migrations.DeleteModel(
            name='ReprintToIssue',
        ),
    ]
