# Generated by Django 3.2.11 on 2022-01-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0042_delete_other_reprint_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('matching', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'External Sites',
                'db_table': 'gcd_external_site',
                'ordering': ('site',),
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('link', models.URLField(max_length=2000)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.externalsite')),
            ],
            options={
                'verbose_name_plural': 'External Links',
                'db_table': 'gcd_external_link',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='external_link',
            field=models.ManyToManyField(to='gcd.ExternalLink'),
        ),
        migrations.AddField(
            model_name='creator',
            name='external_link',
            field=models.ManyToManyField(to='gcd.ExternalLink'),
        ),
        migrations.AddField(
            model_name='issue',
            name='external_link',
            field=models.ManyToManyField(to='gcd.ExternalLink'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='external_link',
            field=models.ManyToManyField(to='gcd.ExternalLink'),
        ),
    ]
