# Generated by Django 3.2.11 on 2023-05-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0044_universe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ('site__site',), 'verbose_name_plural': 'External Links'},
        ),
    ]
