# Generated by Django 3.2.11 on 2023-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0045_alter_externallink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='variant_cover_status',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'No Difference'), (2, 'Only Scan Difference'), (3, 'Artwork Difference')], db_index=True, default=3),
        ),
    ]
