# Generated by Django 3.2.19 on 2023-05-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0046_issue_variant_cover_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatornamedetail',
            options={'ordering': ['sort_name', '-creator__birth_date__year', 'type_id'], 'verbose_name_plural': 'CreatorName Details'},
        ),
        migrations.AddField(
            model_name='feature',
            name='disambiguation',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='variant_cover_status',
            field=models.IntegerField(choices=[(1, 'No Difference'), (2, 'Only Scan Difference'), (3, 'Artwork Difference')], db_index=True, default=3),
        ),
    ]
