# Generated by Django 3.2.19 on 2023-10-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0048_universe_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='universe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='gcd.universe'),
        ),
    ]
