# Generated by Django 3.2.24 on 2024-03-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0052_add_universe_for_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('sort_name', 'year_first_published', 'disambiguation'), 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='characternamedetail',
            options={'ordering': ['sort_name', 'character__year_first_published', 'character__disambiguation'], 'verbose_name_plural': 'CharacterName Details'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('sort_name', 'year_first_published', 'disambiguation'), 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ('character__sort_name', 'group__sort_name', 'year_joined'), 'verbose_name_plural': 'Group Memberships'},
        ),
        migrations.AlterModelOptions(
            name='universe',
            options={'ordering': ('verse', 'designation', 'name'), 'verbose_name_plural': 'Universes'},
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='external_link',
        ),
        migrations.CreateModel(
            name='GroupNameDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_name', models.CharField(db_index=True, default='', max_length=255)),
                ('is_official_name', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_names', to='gcd.group')),
            ],
            options={
                'verbose_name_plural': 'GroupName Details',
                'db_table': 'gcd_group_name_detail',
                'ordering': ['sort_name', 'group__year_first_published', 'group__disambiguation'],
            },
        ),
    ]
