# Generated by Django 3.2.24 on 2024-03-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0053_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycharacter',
            name='group_name',
            field=models.ManyToManyField(to='gcd.GroupNameDetail'),
        ),
        migrations.AddField(
            model_name='storygroup',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcd.groupnamedetail'),
        ),
    ]
