# Generated by Django 3.2.24 on 2024-04-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0054_use_group_name_in_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storygroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcd.group'),
        ),
        migrations.AlterField(
            model_name='storygroup',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.groupnamedetail'),
        ),
    ]
