# Generated by Django 4.2.11 on 2024-07-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0055_switch_group_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storygroup',
            options={'ordering': ['group_name__sort_name']},
        ),
    ]
