# Generated by Django 4.2.20 on 2025-04-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0056_alter_storygroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branduse',
            options={'ordering': ['emblem__name', 'year_began']},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('sort_name', 'language__name')},
        ),
        migrations.AddField(
            model_name='feature',
            name='external_link',
            field=models.ManyToManyField(to='gcd.externallink'),
        ),
    ]
