# Generated by Django 4.2.20 on 2025-04-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0057_external_link_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='external_link',
            field=models.ManyToManyField(to='gcd.externallink'),
        ),
    ]
