# Generated by Django 4.2.20 on 2025-04-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0059_series_external_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storygroup',
            name='group',
        ),
    ]
