# Generated by Django 4.2.20 on 2025-09-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0003_script'),
        ('gcd', '0061_rename_year_created_feature_year_first_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryArc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_name', models.CharField(db_index=True, max_length=255)),
                ('disambiguation', models.CharField(db_index=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stddata.language')),
            ],
            options={
                'db_table': 'gcd_story_arc',
                'ordering': ('sort_name', 'language__name'),
            },
        ),
        migrations.AddField(
            model_name='story',
            name='story_arc',
            field=models.ManyToManyField(to='gcd.storyarc'),
        ),
    ]
