# Generated by Django 4.2.20 on 2025-09-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0063_add_year_to_story_arc'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryArcRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('reverse_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gcd_story_arc_relation_type',
            },
        ),
        migrations.CreateModel(
            name='StoryArcRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField()),
                ('from_story_arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_related_story_arc', to='gcd.storyarc')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_type', to='gcd.storyarcrelationtype')),
                ('to_story_arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_related_story_arc', to='gcd.storyarc')),
            ],
            options={
                'verbose_name_plural': 'Story Arc Relations',
                'db_table': 'gcd_story_arc_relation',
                'ordering': ('to_story_arc', 'relation_type', 'from_story_arc'),
            },
        ),
    ]
