# Generated by Django 4.2.20 on 2025-10-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0064_add_story_arc_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='brand_emblem',
            field=models.ManyToManyField(to='gcd.brand'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_deprecated', to='gcd.brand'),
        ),
    ]
