# Generated by Django 4.2.20 on 2025-12-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0065_brand_emblem_m2m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='no_indicia_printer',
            new_name='indicia_printer_not_printed',
        ),
        migrations.AddField(
            model_name='issue',
            name='indicia_printer_sourced_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
