# Generated by Django 5.2.9 on 2026-01-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0066_indicia_printer_not_printed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'gcd_character_order_type',
            },
        ),
        migrations.CreateModel(
            name='CharacterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_orders', to='gcd.story')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.characterordertype')),
            ],
            options={
                'db_table': 'gcd_character_order',
            },
        ),
        migrations.CreateModel(
            name='CharacterThroughOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField(db_index=True, default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.characterorder')),
                ('story_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcd.storycharacter')),
            ],
            options={
                'db_table': 'gcd_character_through_order',
            },
        ),
        migrations.AddField(
            model_name='characterorder',
            name='characters',
            field=models.ManyToManyField(through='gcd.CharacterThroughOrder', to='gcd.storycharacter'),
        ),
    ]
