# Generated by Django 5.2 on 2026-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0066_indicia_printer_not_printed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='series',
            index=models.Index(
                fields=['deleted', 'sort_name', 'year_began', 'id'],
                name='gcd_series_v2_browse_idx',
            ),
        ),
    ]
