# Generated by Django 5.2 on 2026-05-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0067_series_api_v2_browse_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='character',
            index=models.Index(
                fields=[
                    'deleted',
                    'sort_name',
                    'year_first_published',
                    'disambiguation',
                    'id',
                ],
                name='gcd_character_v2_browse_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(
                fields=[
                    'deleted',
                    'sort_name',
                    'year_first_published',
                    'disambiguation',
                    'id',
                ],
                name='gcd_group_v2_browse_idx',
            ),
        ),
    ]
