# Generated by Django 5.2.10 on 2026-06-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0067_add_character_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='brand',
        ),
        migrations.CreateModel(
            name='FeatureNameDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_name', models.CharField(db_index=True, default='', max_length=255)),
                ('is_official_name', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_names', to='gcd.feature')),
            ],
            options={
                'db_table': 'gcd_feature_detail_name',
                'ordering': ('sort_name', 'feature__year_first_published'),
            },
        ),
    ]
