# Generated by Django 5.2.10 on 2026-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0068_remove_issue_brand_from_db_add_multiple_feature_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='feature_name',
            field=models.ManyToManyField(to='gcd.featurenamedetail'),
        ),
    ]
