# Generated by Django 5.2 on 2026-05-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0068_character_group_api_v2_browse_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(
                fields=['deleted', 'modified', 'id'],
                name='gcd_issue_v2_modified_idx',
            ),
        ),
    ]
