# Generated by Django 5.2.10 on 2026-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0069_add_feature_names_to_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelogo',
            name='feature_name',
            field=models.ManyToManyField(db_table='gcd_feature_logo_2_feature_name', to='gcd.featurenamedetail'),
        ),
    ]
