# Generated by Django 5.2 on 2026-05-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0069_issue_api_v2_modified_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(
                fields=['deleted', 'series', 'sort_code', 'id'],
                name='gcd_issue_v2_browse_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(
                fields=['deleted', 'variant_of', 'sort_code', 'id'],
                name='gcd_issue_v2_variant_idx',
            ),
        ),
    ]
