# Generated by Django 5.2 on 2026-05-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0070_issue_api_v2_browse_variant_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='character',
            index=models.Index(
                fields=[
                    'deleted',
                    'language',
                    'sort_name',
                    'year_first_published',
                    'disambiguation',
                    'id',
                ],
                name='gcd_char_v2_lang_browse_idx',
            ),
        ),
    ]
