# Generated by Django 5.2.16 on 2026-08-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0070_feature_logo_2_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
