# Generated by Django 5.2 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0071_character_api_v2_language_browse_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(
                fields=['deleted', 'issue', 'sequence_number', 'id'],
                name='gcd_story_v2_browse_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(
                fields=['deleted', 'modified', 'id'],
                name='gcd_story_v2_modified_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='reprint',
            index=models.Index(
                fields=['origin_issue', 'target_issue', 'id'],
                name='gcd_reprint_v2_browse_idx',
            ),
        ),
    ]
