# -*- coding: utf-8 -*-
from datetime import date
from django.conf.urls import url
from django.conf import settings
from django.views.generic import base as bv
from haystack.forms import FacetedSearchForm
from haystack.views import search_view_factory
from apps.gcd.views.search_haystack import PaginatedFacetedSearchView, \
    GcdSearchQuerySet

from apps.gcd import views as gcd_views
import apps.gcd.views.details
import apps.gcd.views.search
import apps.gcd.views.redirect

urlpatterns = [
    ###########################################################################
    # GCD URLs.
    #
    # General forms, where <entity> is publisher, series or issue and
    # <credit> is writer, penciller, etc.:
    #   gcd/<entity>/<id>/ shows details for the given entity.
    #   gcd/<entity>/name/<name> searches for entities by name.
    #   gcd/<credit>/name/<name> searches for stories by the named credit.
    #
    # In many cases a suffix of /sort/<sort type>/ is an optional extension.
    # In such cases, the form specifying the sort type must be listed first
    # or else it will never be used because the shorter form will always match.
    ###########################################################################

    url(r'^$', gcd_views.index, name='home'),
    url(r'^search/$', gcd_views.search.search, name='basic_search'),
    url(r'^search/advanced/$', gcd_views.search.advanced_search,
      name='advanced_search'),
    url(r'^search/advanced/process/csv/$', gcd_views.search.process_advanced,
      {'export_csv': True}, name='process_advanced_search_csv'),
    url(r'^search/advanced/process/$', gcd_views.search.process_advanced,
      name='process_advanced_search'),
    url(r'^search/name/$',
      gcd_views.search.name_search_hx,
      name='name_search_hx'),

    url(r'^(?P<model_name>\w+)/(?P<id>\d+)/history/$',
     gcd_views.details.change_history, name='change_history'),

    # Publisher
    url(r'^publisher/(?P<publisher_id>\d+)/$',
      gcd_views.details.publisher, name='show_publisher'),
    url(r'^publisher/name/(?P<publisher_name>.+)/sort/(?P<sort>.+)/$',
     gcd_views.search.publisher_by_name, name='publisher_by_name'),
    url(r'^publisher/name/(?P<publisher_name>.+)/$',
     gcd_views.search.publisher_by_name, name='publisher_by_name'),
    url(r'^publisher/search/$',
      gcd_views.search.publisher_search_hx,
      name='publisher_search_hx'),
    url(r'^publisher/(?P<publisher_id>\d+)/indicia_publishers/$',
     gcd_views.details.indicia_publishers),
    url(r'^publisher/(?P<publisher_id>\d+)/brands/$',
      gcd_views.details.brands),
    url(r'^publisher/(?P<publisher_id>\d+)/brand_uses/$',
      gcd_views.details.brand_uses),
    url(r'^publisher/(?P<publisher_id>\d+)/issues/$',
      gcd_views.details.show_publisher_issues),
    url(r'^publisher/(?P<publisher_id>\d+)/current_series/$',
      gcd_views.details.show_publisher_current_series),
    url(r'^publisher/(?P<publisher_id>\d+)/monthly_covers_on_sale/$',
      gcd_views.details.publisher_monthly_covers,
      {'use_on_sale': True }, name='publisher_monthly_covers_on_sale'),
    url(r'^publisher/(?P<publisher_id>\d+)/monthly_covers_on_sale/year/(?P<year>\d{4})/month/(?P<month>\d{1,2})/$',
      gcd_views.details.publisher_monthly_covers,
      {'use_on_sale': True }, name='publisher_monthly_covers_on_sale'),
    url(r'^publisher/(?P<publisher_id>\d+)/monthly_covers_pub_date/$',
      gcd_views.details.publisher_monthly_covers,
      {'use_on_sale': False }, name='publisher_monthly_covers_pub_date'),
    url(r'^publisher/(?P<publisher_id>\d+)/monthly_covers_pub_date/year/(?P<year>\d{4})/month/(?P<month>\d{1,2})/$',
      gcd_views.details.publisher_monthly_covers,
      {'use_on_sale': False }, name='publisher_monthly_covers_pub_date'),
    url(r'^publisher/(?P<publisher_id>\d+)/monthly_issues_on_sale/$',
      gcd_views.details.publisher_monthly_covers,
      {'use_on_sale': True, 'overview': True }, name='publisher_monthly_issues_on_sale'),
    url(r'^publisher/(?P<publisher_id>\d+)/monthly_issues_on_sale/year/(?P<year>\d{4})/month/(?P<month>\d{1,2})/$',
      gcd_views.details.publisher_monthly_covers,
      {'use_on_sale': True, 'overview': True }, name='publisher_monthly_issues_on_sale'),
    url(r'^publisher/(?P<publisher_id>\d+)/monthly_issues_pub_date/$',
      gcd_views.details.publisher_monthly_covers,
      {'use_on_sale': False, 'overview': True }, name='publisher_monthly_issues_pub_date'),
    url(r'^publisher/(?P<publisher_id>\d+)/monthly_issues_pub_date/year/(?P<year>\d{4})/month/(?P<month>\d{1,2})/$',
      gcd_views.details.publisher_monthly_covers,
      {'use_on_sale': False, 'overview': True }, name='publisher_monthly_issues_pub_date'),

    url(r'^brand_group/(?P<brand_group_id>\d+)/$',
      gcd_views.details.brand_group, name='show_brand_group'),
    url(r'^brand_group/name/(?P<brand_group_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.brand_group_by_name,
      name='brand_group_by_name'),
    url(r'^brand_group/name/(?P<brand_group_name>.+)/$',
      gcd_views.search.brand_group_by_name,
      name='brand_group_by_name'),

    url(r'^brand/(?P<brand_id>\d+)/$',
      gcd_views.details.brand, name='show_brand'),
    url(r'^brand/name/(?P<brand_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.brand_by_name, name='brand_by_name'),
    url(r'^brand/name/(?P<brand_name>.+)/$',
      gcd_views.search.brand_by_name, name='brand_by_name'),

    url(r'^brand_emblem/(?P<brand_id>\d+)/$',
      gcd_views.details.brand, name='show_brand'),
    url(r'^brand_emblem/name/(?P<brand_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.brand_by_name, name='brand_by_name'),
    url(r'^brand_emblem/name/(?P<brand_name>.+)/$',
      gcd_views.search.brand_by_name, name='brand_by_name'),

    url(r'^indicia_publisher/(?P<indicia_publisher_id>\d+)/$',
      gcd_views.details.indicia_publisher, name='show_indicia_publisher'),
    url(r'^indicia_publisher/name/(?P<ind_pub_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.indicia_publisher_by_name,
      name='indicia_publisher_by_name'),
    url(r'^indicia_publisher/name/(?P<ind_pub_name>.+)/$',
      gcd_views.search.indicia_publisher_by_name,
      name='indicia_publisher_by_name'),

    # Printer
    url(r'^printer/(?P<printer_id>\d+)/$',
      gcd_views.details.printer, name='show_printer'),
    url(r'^printer/(?P<printer_id>\d+)/issues/$',
      gcd_views.details.printer_issues, name='printer_issues'),
    url(r'^printer/search/$',
      gcd_views.search.printer_search_hx,
      name='printer_search_hx'),
    url(r'^indicia_printer/(?P<indicia_printer_id>\d+)/$',
      gcd_views.details.indicia_printer, name='show_indicia_printer'),
    url(r'^indicia_printer/(?P<indicia_printer_id>\d+)/issues/$',
        gcd_views.details.indicia_printer_issues, name='indicia_printer_issues'),

    url(r'^award/(?P<award_id>\d+)/$',
      gcd_views.details.award, name='show_award'),
    url(r'^award/name/(?P<award_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.award_by_name, name='award_by_name'),
    url(r'^award/name/(?P<award_name>.+)/$',
      gcd_views.search.award_by_name, name='award_by_name'),

    url(r'^school/(?P<school_id>\d+)/$',
      gcd_views.details.school, name='show_school'),

    url(r'^creator/(?P<creator_id>\d+)/$',
      gcd_views.details.creator, name='show_creator'),
    url(r'^creator/name/(?P<creator_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.creator_by_name,
      name='creator_by_name'),
    url(r'^creator/search/$',
      gcd_views.search.creator_search_hx,
      name='creator_search_hx'),
    url(r'^creator/(?P<creator_id>\d+)/sequences/$',
      gcd_views.details.creator_sequences, name='creator_sequences'),
    url(r'^creator/(?P<creator_id>\d+)/series/$',
      gcd_views.details.creator_series, name='creator_series'),
    url(r'^creator/(?P<creator_id>\d+)/characters/$',
      gcd_views.details.creator_characters, name='creator_characters'),
    url(r'^creator/(?P<creator_id>\d+)/creators/$',
      gcd_views.details.creator_creators, name='creator_creators'),
    url(r'^creator/(?P<creator_id>\d+)/creator/(?P<co_creator_id>\d+)/issues/$',
      gcd_views.details.checklist_by_id, name='creator_cocreator_issues'),
    url(r'^creator/(?P<creator_id>\d+)/features/$',
      gcd_views.details.creator_features, name='creator_features'),
    url(r'^creator/(?P<creator_id>\d+)/series/(?P<series_id>\d+)/issues/$',
      gcd_views.details.creator_issues, name='creator_series_issues'),
    url(r'^creator/(?P<creator_id>\d+)/edited_issues/$',
      gcd_views.details.creator_edited_issues, name='creator_edited_issues'),
    url(r'^creator/(?P<creator_id>\d+)/series/(?P<series_id>\d+)/sequences/$',
      gcd_views.details.creator_sequences, name='creator_series_sequences'),
    url(r'^creator/(?P<creator_id>\d+)/character/(?P<character_id>\d+)/issues/$',
      gcd_views.details.checklist_by_id, name='creator_character_issues'),
    url(r'^creator/(?P<creator_id>\d+)/feature/(?P<feature_id>\d+)/issues/$',
      gcd_views.details.checklist_by_id, name='creator_feature_issues'),
    url(r'^creator/(?P<creator_id>\d+)/overview/$',
      gcd_views.details.creator_overview, name='creator_overview'),
    url(r'^creator/name/(?P<creator_name>.+)/$',
      gcd_views.search.creator_by_name,
      name='creator_by_name'),
    url(r'^creator_name/(?P<creator_id>\d+)/sequences/$',
        gcd_views.details.creator_sequences, {'creator_name': True },
        name='creator_name_sequences'),

    url(r'^creator_membership/(?P<creator_membership_id>\d+)/$',
      gcd_views.details.creator_membership, name='show_creator_membership'),
    url(r'^creator_membership/name/(?P<creator_membership_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.creator_membership_by_name,
      name='creator_membership_by_name'),
    url(r'^creator_membership/name/(?P<creator_membership_name>.+)/$',
      gcd_views.search.creator_membership_by_name,
      name='creator_membership_by_name'),

    url(r'^received_award/(?P<received_award_id>\d+)/$',
      gcd_views.details.received_award, name='show_received_award'),
    url(r'^received_award/name/(?P<received_award_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.received_award_by_name,
      name='received_award_by_name'),
    url(r'^received_award/name/(?P<received_award_name>.+)/$',
      gcd_views.search.received_award_by_name,
      name='received_award_by_name'),

    url(r'^creator_art_influence/(?P<creator_art_influence_id>\d+)/$',
      gcd_views.details.creator_art_influence, name='show_creator_art_influence'),
    url(r'^creator_art_influence/name/(?P<creator_art_influence_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.creator_art_influence_by_name,
      name='creator_art_influence_by_name'),
    url(r'^creator_art_influence/name/(?P<creator_art_influence_name>.+)/$',
      gcd_views.search.creator_art_influence_by_name,
      name='creator_art_influence_by_name'),

    url(r'^creator_non_comic_work/(?P<creator_non_comic_work_id>\d+)/$',
      gcd_views.details.creator_non_comic_work, name='show_creator_non_comic_work'),
    url(r'^creator_non_comic_work/name/(?P<creator_non_comic_work_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.creator_non_comic_work_by_name,
      name='creator_non_comic_work_by_name'),
    url(r'^creator_non_comic_work/name/(?P<creator_non_comic_work_name>.+)/$',
      gcd_views.search.creator_non_comic_work_by_name,
      name='creator_non_comic_work_by_name'),

    url(r'^creator_relation/(?P<creator_relation_id>\d+)/$',
      gcd_views.details.creator_relation, name='show_creator_relation'),

    url(r'^creator_school/(?P<creator_school_id>\d+)/$',
      gcd_views.details.creator_school, name='show_creator_school'),
    url(r'^creator_degree/(?P<creator_degree_id>\d+)/$',
      gcd_views.details.creator_degree, name='show_creator_degree'),

    url(r'^creator_signature/(?P<creator_signature_id>\d+)/$',
      gcd_views.details.creator_signature, name='show_creator_signature'),
    url(r'^creator_signature/(?P<creator_id>\d+)/sequences/$',
        gcd_views.details.creator_sequences, {'signature': True},
        name='creator_signature_sequences'),

    url(r'^imprint/(?P<imprint_id>\d+)/$', gcd_views.details.imprint,
      name='show_imprint'),

    # Series
    url(r'^series/(?P<series_id>\d+)/$',
      gcd_views.details.series, name='show_series'),
    url(r'^series/name/(?P<series_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.series_by_name, name='series_by_name'),
    url(r'^series/(?P<series_id>\d+)/details/$',
      gcd_views.details.series_details,
      name='series_details'),
    url(r'^series/(?P<series_id>\d+)/details/timeline/$',
      gcd_views.details.series_details,
      {'by_date': True },
      name='series_timeline'),
    url(r'^series/(?P<series_id>\d+)/details/creator_list/$',
      gcd_views.details.series_creatorlist, name='series_creatorlist'),
    url(r'^series/(?P<series_id>\d+)/issues_to_migrate/$',
      gcd_views.details.series_issues_to_migrate,
      name='series_migrate'),

    # Series and Issue
    url(r'^series/name/(?P<series_name>.+)/issue/(?P<issue_nr>.+)/$',
      gcd_views.search.series_and_issue),
    url(r'^series/name/(?P<series_name>.+)/$',
      gcd_views.search.series_by_name, name='series_by_name'),
    url(r'^series/search/$',
      gcd_views.search.series_search_hx,
      name='series_search_hx'),

    # Series index and cover status / gallery
    url(r'^series/(?P<series_id>\d+)/status/$',
      gcd_views.details.status, name='series_status'),

    url(r'^series/(?P<series_id>\d+)/covers/$',
      gcd_views.details.covers, name='series_covers'),
    url(r'^series/(?P<series_id>\d+)/overview/$',
      gcd_views.details.series_overview, name='series_overview'),

    url(r'^series/(?P<series_id>\d+)/scans/$',
      gcd_views.details.scans, name='series_scan_table'),

    # Issue
    url(r'^issue/(?P<issue_id>\d+)/modal/$',
      gcd_views.details.show_issue_modal, name='show_issue_modal'),
    url(r'^issue/(?P<issue_id>\d+)/$',
      gcd_views.details.issue, name='show_issue'),
    url(r'^issue/$', gcd_views.details.issue_form, name='issue_select_form'),
    # ISBNs don't have 'name' in the path, but otherwise work the same
    url(r'^isbn/name/(?P<isbn>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.issue_by_isbn_name),
    url(r'^isbn/name/(?P<isbn>.+)/$',
      gcd_views.search.issue_by_isbn_name),
    url(r'^isbn/search/$',
      gcd_views.search.issue_by_isbn_hx),
    url(r'^isbn/(?P<isbn>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.issue_by_isbn, name='issue_by_isbn'),
    url(r'^isbn/(?P<isbn>.+)/$',
      gcd_views.search.issue_by_isbn, name='issue_by_isbn'),
    # barcodes don't have 'name' in the path, but otherwise work the same
    url(r'^barcode/name/(?P<barcode>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.issue_by_barcode_name),
    url(r'^barcode/name/(?P<barcode>.+)/$',
      gcd_views.search.issue_by_barcode_name),
    url(r'^barcode/search/$',
      gcd_views.search.issue_by_barcode_hx),
    url(r'^barcode/(?P<barcode>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.issue_by_barcode, name='issue_by_barcode'),
    url(r'^barcode/(?P<barcode>.+)/$',
      gcd_views.search.issue_by_barcode, name='issue_by_barcode'),

    # Single Cover
    url(r'^issue/(?P<issue_id>\d+)/cover/(?P<size>\d+)/$',
      gcd_views.details.cover, name='issue_cover_view'),

    # Images for Issue
    url(r'^issue/(?P<issue_id>\d+)/image/$',
      gcd_views.details.issue_images, name='issue_images'),

    # Credits
    url(r'^credit/(?P<credit_id>\d+)/source/$',
      gcd_views.details.credit_source, name='credit_source'),
    # Stories
    url(r'^story/(?P<story_id>\d+)/(?P<credit_type>.+)/history/$',
      gcd_views.details.credit_type_history, name='credit_type_history'),
    url(r'^story/(?P<story_id>\d+)/modal/$',
      gcd_views.details.show_story_modal, name='show_story_modal'),

    # Feature
    url(r'^feature/(?P<feature_id>\d+)/issues/$',
      gcd_views.details.feature_issuelist_by_id, name='feature_issuelist_by_id'),
    url(r'^feature/(?P<feature_id>\d+)/overview/$',
      gcd_views.details.feature_overview, name='feature_overview'),
    url(r'^feature/(?P<feature_id>\d+)/creators/$',
      gcd_views.details.feature_creatorlist, name='feature_creatorlist'),
    url(r'^feature/(?P<feature_id>\d+)/sequences/$',
      gcd_views.details.feature_sequences, name='feature_sequences'),
    url(r'^feature/(?P<feature_id>\d+)/covers/$',
      gcd_views.details.feature_covers, name='feature_covers'),
    url(r'^feature/(?P<feature_id>\d+)/$',
      gcd_views.details.feature, name='show_feature'),
    url(r'^feature_logo/(?P<feature_logo_id>\d+)/issues/$',
      gcd_views.details.feature_logo_issuelist_by_id, name='feature_logo_issuelist_by_id'),
    url(r'^feature_logo/(?P<feature_logo_id>\d+)/sequences/$',
      gcd_views.details.feature_logo_sequences, name='feature_logo_sequences'),
    url(r'^feature_logo/(?P<feature_logo_id>\d+)/$',
      gcd_views.details.feature_logo, name='show_feature_logo'),
    url(r'^feature_relation/(?P<feature_relation_id>\d+)/$',
      gcd_views.details.feature_relation, name='show_feature_relation'),

    url(r'^universe/(?P<universe_id>\d+)/$',
      gcd_views.details.universe, name='show_universe'),
    # Character
    url(r'^character/search/$',
      gcd_views.search.character_search_hx,
      name='character_search_hx'),
    url(r'^character/(?P<character_id>\d+)/issues/$',
      gcd_views.details.character_issues, name='character_issues'),
    url(r'^character/(?P<character_id>\d+)/issues/layer/up/$',
      gcd_views.details.character_issues, {'layer': 1}, name='character_issues_up'),
    url(r'^character/(?P<character_id>\d+)/issues/layer/down/$',
      gcd_views.details.character_issues, {'layer': -1}, name='character_issues_down'),
    url(r'^character/(?P<character_id>\d+)/creators/$',
      gcd_views.details.character_creators, name='character_creators'),
    url(r'^character/(?P<character_id>\d+)/sequences/$',
      gcd_views.details.character_sequences, name='character_sequences'),
    url(r'^character/(?P<character_id>\d+)/covers/$',
      gcd_views.details.character_covers, name='character_covers'),
    url(r'^character/(?P<character_id>\d+)/$',
      gcd_views.details.character, name='show_character'),
    url(r'^character_relation/(?P<character_relation_id>\d+)/$',
      gcd_views.details.character_relation, name='show_character_relation'),
    url(r'^group/search/$',
      gcd_views.search.group_search_hx,
      name='group_search_hx'),
    url(r'^group/(?P<group_id>\d+)/issues/$',
      gcd_views.details.group_issues, name='group_issues'),
    url(r'^group/(?P<group_id>\d+)/creators/$',
      gcd_views.details.group_creators, name='group_creators'),
    url(r'^group/(?P<group_id>\d+)/sequences/$',
      gcd_views.details.group_sequences, name='group_sequences'),
    url(r'^group/(?P<group_id>\d+)/$',
      gcd_views.details.group, name='show_group'),
    url(r'^group_relation/(?P<group_relation_id>\d+)/$',
      gcd_views.details.group_relation, name='show_group_relation'),
    url(r'^group_membership/(?P<group_membership_id>\d+)/$',
      gcd_views.details.group_membership, name='show_group_membership'),

    # Keywords
    url(r'^keyword/(?P<keyword>.+)/(?P<model_name>.+)/$',
      gcd_views.details.keyword, name='show_keyword'),
    url(r'^keyword/(?P<keyword>.+)/$',
      gcd_views.details.keyword, name='show_keyword'),

    # Attribute searches
    url(r'^character/name/(?P<character_name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.character_by_name, name='character_by_name'),
    url(r'^character/name/(?P<character_name>.+)/$',
      gcd_views.search.character_by_name, name='character_by_name'),

    url(r'^writer/name/(?P<writer>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.writer_by_name, name='writer_by_name'),
    url(r'^writer/name/(?P<writer>.+)/$',
      gcd_views.search.writer_by_name, name='writer_by_name'),

    url(r'^penciller/name/(?P<penciller>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.penciller_by_name, name='penciller_by_name'),
    url(r'^penciller/name/(?P<penciller>.+)/$',
      gcd_views.search.penciller_by_name, name='penciller_by_name'),

    url(r'^inker/name/(?P<inker>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.inker_by_name, name='inker_by_name'),
    url(r'^inker/name/(?P<inker>.+)/$',
      gcd_views.search.inker_by_name, name='inker_by_name'),

    url(r'^colorist/name/(?P<colorist>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.colorist_by_name, name='colorist_by_name'),
    url(r'^colorist/name/(?P<colorist>.+)/$',
      gcd_views.search.colorist_by_name, name='colorist_by_name'),

    url(r'^letterer/name/(?P<letterer>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.letterer_by_name, name='letterer_by_name'),
    url(r'^letterer/name/(?P<letterer>.+)/$',
      gcd_views.search.letterer_by_name, name='letterer_by_name'),

    url(r'^editor/name/(?P<editor>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.editor_by_name, name='editor_by_name'),
    url(r'^editor/name/(?P<editor>.+)/$',
      gcd_views.search.editor_by_name, name='editor_by_name'),

    url(r'^story/name/(?P<title>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.story_by_title, name='story_by_title'),
    url(r'^story/name/(?P<title>.+)/$',
      gcd_views.search.story_by_title, name='story_by_title'),

    url(r'^feature/name/(?P<feature>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.story_by_feature, name='story_by_feature'),
    url(r'^feature/name/(?P<feature>.+)/$',
      gcd_views.search.story_by_feature, name='story_by_feature'),

    url(r'^credit/name/(?P<name>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.story_by_credit, name='story_by_credit'),
    url(r'^credit/name/(?P<name>.+)/$',
      gcd_views.search.story_by_credit, name='story_by_credit'),

    # Special display pages
    url(r'^checklist/name/(?P<creator>.+)/country/(?P<country>.+)/$',
      gcd_views.details.checklist_by_name, name='checklist_by_name'),
    url(r'^checklist/name/(?P<creator>.+)/language/(?P<language>.+)/$',
      gcd_views.details.checklist_by_name, name='checklist_by_name'),
    url(r'^checklist/name/(?P<creator>.+)/$',
      gcd_views.details.checklist_by_name, name='checklist_by_name'),
    url(r'^creator_migrate_checklist/name/(?P<creator>.+)/$',
      gcd_views.details.checklist_by_name, {'to_be_migrated': True},
      name='creator_migrate_checklist'),
    url(r'^checklist/(?P<creator_name_id>\d+)/character/(?P<character_id>\d+)/$',
      gcd_views.details.creator_name_checklist, name='creator_name_checklist'),
    url(r'^checklist/(?P<creator_name_id>\d+)/group/(?P<group_id>\d+)/$',
      gcd_views.details.creator_name_checklist, name='creator_name_checklist'),
    url(r'^checklist/(?P<creator_name_id>\d+)/feature/(?P<feature_id>\d+)/$',
      gcd_views.details.creator_name_checklist, name='creator_name_checklist'),
    url(r'^checklist/(?P<creator_name_id>\d+)/series/(?P<series_id>\d+)/$',
      gcd_views.details.creator_name_checklist, name='creator_name_checklist'),
    url(r'^checklist/(?P<creator_id>\d+)/country/(?P<country>.+)/$',
      gcd_views.details.checklist_by_id, name='checklist_by_id'),
    url(r'^checklist/(?P<creator_id>\d+)/language/(?P<language>.+)/$',
      gcd_views.details.checklist_by_id, name='checklist_by_id'),
    url(r'^checklist/(?P<creator_id>\d+)/$',
      gcd_views.details.checklist_by_id, name='checklist_by_id'),
   url(r'^cover_checklist/(?P<creator_id>\d+)/country/(?P<country>.+)/$',
      gcd_views.details.cover_checklist_by_id, name='cover_checklist_by_id'),
    url(r'^cover_checklist/(?P<creator_id>\d+)/language/(?P<language>.+)/$',
      gcd_views.details.cover_checklist_by_id, name='cover_checklist_by_id'),
    url(r'^cover_checklist/(?P<creator_id>\d+)/$',
      gcd_views.details.cover_checklist_by_id, name='cover_checklist_by_id'),

    # Note that Jobs don't have 'name' in the path, but otherwise work the same.
    url(r'^job_number/name/(?P<number>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.story_by_job_number_name),
    url(r'^job_number/name/(?P<number>.+)/$',
      gcd_views.search.story_by_job_number_name),
    url(r'^job_number/(?P<number>.+)/sort/(?P<sort>.+)/$',
      gcd_views.search.story_by_job_number, name='story_by_job_number'),
    url(r'^job_number/(?P<number>.+)/$',
      gcd_views.search.story_by_job_number, name='story_by_job_number'),

    # show covers/changes from a particular date
    url(r'^daily_covers/$',
      gcd_views.details.daily_covers, name='covers_today'),
    url(r'^daily_covers/(?P<show_date>.+)/$',
      gcd_views.details.daily_covers, name='covers_by_date'),
    url(r'^my_daily_covers/$',
      gcd_views.details.daily_covers, {'user': True},
      name='my_covers_today'),
    url(r'^my_daily_covers/(?P<show_date>.+)/$',
      gcd_views.details.daily_covers, {'user': True},
      name='my_covers_by_date'),
    url(r'^daily_changes/$',
      gcd_views.details.daily_changes, name='changes_today'),
    url(r'^daily_changes/(?P<show_date>.+)/$',
      gcd_views.details.daily_changes, name='changes_by_date'),
    url(r'^my_daily_changes/$',
      gcd_views.details.daily_changes, {'user': True},
      name='my_changes_today'),
    url(r'^my_daily_changes/(?P<show_date>.+)/$',
      gcd_views.details.daily_changes, {'user': True},
      name='my_changes_by_date'),
    url(r'^on_sale_weekly/$',
      gcd_views.details.on_sale_weekly, name='on_sale_this_week'),
    url(r'^on_sale_weekly/no_variant/$',
      gcd_views.details.on_sale_weekly, {'variant': False},
      name='on_sale_this_week_no_variant'),
    url(r'^on_sale_weekly/(?P<year>\d{4})/week/(?P<week>\d{1,2})/$',
      gcd_views.details.on_sale_weekly, name='on_sale_weekly'),
    url(r'^on_sale_weekly/(?P<year>\d{4})/week/(?P<week>\d{1,2})/no_variant/$',
      gcd_views.details.on_sale_weekly, {'variant': False},
      name='on_sale_weekly_no_variant'),
    url(r'^on_sale_monthly/$',
      gcd_views.details.on_sale_monthly, name='on_sale_this_month'),
    url(r'^on_sale_monthly/no_variant/$',
      gcd_views.details.on_sale_monthly, {'variant': False},
      name='on_sale_this_month_no_variant'),
    url(r'^on_sale_monthly/(?P<year>\d{4})/month/(?P<month>\d{1,2})/$',
      gcd_views.details.on_sale_monthly, name='on_sale_monthly'),
    url(r'^on_sale_monthly/(?P<year>\d{4})/month/(?P<month>\d{1,2})/no_variant/$',
      gcd_views.details.on_sale_monthly, {'variant': False},
      name='on_sale_monthly_no_variant'),
    url(r'^international_stats_language/$',
      gcd_views.details.int_stats_language,
      name='international_stats_language'),
    url(r'^international_stats_country/$',
      gcd_views.details.int_stats_country,
      name='international_stats_country'),

    # list covers marked for replacement
    url(r'^covers_to_replace/$',
      gcd_views.details.covers_to_replace),
    url(r'^covers_to_replace/with/(?P<starts_with>.+)/$',
     gcd_views.details.covers_to_replace),

    # calendar
    url(r'^calendar/$',
     bv.TemplateView.as_view(template_name='gcd/status/calendar.html')),
    url(r'daily_creators/offset/(?P<offset>[-+]?\d{1,3})/$',
      gcd_views.details.daily_creators),
    url(r'daily_creators/$', gcd_views.details.daily_creators,
     name='daily_creators'),

    # GCD comics history award
    url(r'^gcd_history_award/$',
      bv.TemplateView.as_view(template_name='gcd/gcd_history_award.html'),
      name='gcd_history_award'),

    # redirects of old lasso pages
    url(r'^publisher_details.lasso/$', gcd_views.redirect.publisher),
    url(r'^series.lasso/$', gcd_views.redirect.series),
    url(r'^indexstatus.lasso/$', gcd_views.redirect.series_status),
    url(r'^scans.lasso/$', gcd_views.redirect.series_scans),
    url(r'^covers.lasso/$', gcd_views.redirect.series_covers),
    url(r'^details.lasso/$', gcd_views.redirect.issue),
    url(r'^coverview.lasso/$', gcd_views.redirect.issue_cover),
    url(r'^daily_covers.lasso/$', gcd_views.redirect.daily_covers),
    url(r'^search.lasso/$', gcd_views.redirect.search),
]

# haystack search
sqs = GcdSearchQuerySet().facet('facet_model_name').facet('country') \
                         .facet('language').facet('publisher')\
                         .facet('feature').facet('type')\
                         .date_facet('date', start_date=date(1000, 1, 1),
                                     end_date=date(3000, 1, 1), gap_by='year')

urlpatterns += [url(r'^searchNew/',
                search_view_factory(
                  view_class=PaginatedFacetedSearchView,
                  form_class=FacetedSearchForm, searchqueryset=sqs),
                name='haystack_search'),
]

urlpatterns += [
    url(r'^international_stats/$',
     bv.RedirectView.as_view(url='/international_stats_language/',
                             permanent=True)),
    url('^covers_for_replacement.lasso/$',
      bv.RedirectView.as_view(url='/covers_to_replace/',
                              permanent=True)),
    url('^index.lasso/$', bv.RedirectView.as_view(url='/', permanent=True)),
    url('^donate.lasso/$', bv.RedirectView.as_view(url='/donate/',
                                                permanent=True)),
    url(r'^graphics/covers/', bv.RedirectView.as_view(url=None, permanent=True)),
    url('^coversubmit/index.lasso/$', bv.RedirectView.as_view(url=None,
                                                           permanent=True)),
    url(r'^creator_checklist/name/(?P<creator>.+)/country/(?P<country>.+)/$',
      bv.RedirectView.as_view(
        url='/checklist/name/%(creator)s/country/%(country)s/',
        permanent=True)),
    url(r'^creator_checklist/name/(?P<creator>.+)/language/(?P<language>.+)/$',
      bv.RedirectView.as_view(
        url='/checklist/name/%(creator)s/language/%(language)s/',
        permanent=True)),
    url(r'^creator_checklist/name/(?P<creator>.+)/$',
      bv.RedirectView.as_view(url='/checklist/name/%(creator)s/',
                              permanent=True))
]
