# Generated by Django 2.2.12 on 2020-11-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_length_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='permission',
            field=models.ForeignKey(limit_choices_to={'codename__in': ('can_vote', 'on_board')}, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='agenda_items',
            field=models.ManyToManyField(limit_choices_to={'state': True}, related_name='topics', to='voting.AgendaItem'),
        ),
    ]
