# Generated by Django 3.2.11 on 2023-05-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_housekeeping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='state',
            field=models.BooleanField(choices=[(None, 'Pending'), (True, 'Open'), (False, 'Closed')], null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='result',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='vote_type',
            field=models.ForeignKey(help_text='Pass / Fail types will automatically create their own Options if none are specified directly. For other types, add Options below.', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='voting.votetype'),
        ),
        migrations.AlterField(
            model_name='votetype',
            name='max_votes',
            field=models.IntegerField(blank=True, default=1, help_text='Having more votes than winners sets up ranked choice voting. Leave max votes blank to allow as many ranks as options.', null=True),
        ),
    ]
