# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0002_initial_data'),
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('indexer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_credit_set', to='indexer.Indexer')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_credit_set', to='gcd.Series')),
            ],
            options={
                'db_table': 'legacy_series_indexers',
            },
        ),
        migrations.CreateModel(
            name='MigrationStoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reprint_needs_inspection', models.BooleanField(db_index=True, default=False)),
                ('reprint_confirmed', models.BooleanField(db_index=True, default=False)),
                ('reprint_original_notes', models.TextField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='migration_status', to='gcd.Story')),
            ],
            options={
                'db_table': 'legacy_migration_story_status',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_index=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('indexer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='indexer.Indexer')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='gcd.Issue')),
            ],
        ),
    ]
